### ISSUE TITLE
It will be great if you can provide tested yaml and config 

### ISSUE THREAD

**Issue by kumaritanushree** [distribworks/dkron#1002]
It will be great if you can provide tested yaml for dkron cluster deployment on cloud and configuration file. 

config with multiple dkron server

**Comment by victorcoder** [comment]
Hi @kumaritanushree, the example config included as comments in the default config file, see https://dkron.io/basics/configuration/ should give you an idea of how it should be configured.

Let us know if you have further questions

**Comment by kumaritanushree** [comment]
Hi all

It will be great if you can help on #1001. I am stuck on this from long
time.

Thanks
Tanushree
