### ISSUE TITLE
Dkron stops for no reason

### ISSUE THREAD

**Issue by seanfulton** [distribworks/dkron#1015]
I guess my previous post/description did not get posted so I will post it again:

We are running a three-node cluster with dkron-3.8.1.  Periodically jobs simply stop running across the whole cluster. The error logs contain entries like this:

_addr="10.10.4.172:6868"
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="job: Error quering for running executions" error="context deadline exceeded" node=nj-dcos02-cl01
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="grpc: error dialing." error="context deadline exceeded" method=GetActiveExecutions node=nj-dcos02-cl01 server
_addr="10.10.4.172:6868"
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="job: Error quering for running executions" error="context deadline exceeded" node=nj-dcos02-cl01
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="grpc: error dialing." error="context deadline exceeded" method=GetActiveExecutions node=nj-dcos02-cl01 server
_addr="10.10.4.172:6868"
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="job: Error quering for running executions" error="context deadline exceeded" node=nj-dcos02-cl01
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="grpc: error dialing." error="context deadline exceeded" method=GetActiveExecutions node=nj-dcos02-cl01 server
_addr="10.10.4.172:6868"
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="job: Error quering for running executions" error="context deadline exceeded" node=nj-dcos02-cl01
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="grpc: error dialing." error="context deadline exceeded" method=GetActiveExecutions node=nj-dcos02-cl01 server
_addr="10.10.4.172:6868"
Aug 22 05:05:10 nj-dcos02-cl01 dkron: time="2021-08-22T05:05:10-04:00" level=error msg="job: Error quering for running executions" error="context deadline exceeded" node=nj-dcos02-cl01
Aug 22 

There is no alert to the administrators what happened or that dkron has stopped working. It just stops running jobs.

Any idea what is causing this or how to get alerted that there is a condition that needs to be addressed? Restarting the cluster seems to resolve it but I can't restart the cluster if I don't know it's hung.

sean

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Specifications:**
 - OS: [e.g. linux]
 - Version [e.g. 2.0.1]

**Additional context**

**Comment by victorcoder** [comment]
Is there an active leader when you reach this state?

**Comment by seanfulton** [comment]
A full restart of the cluster after upgrading all the nodes seems to have fixed it. Can you point me to docs for the correct way to upgrade a running cluster?

**Comment by victorcoder** [comment]
@seanfulton did you follow this procedure? https://dkron.io/usage/upgrade/#backup--restore
