### ISSUE TITLE
Questions about performance, scalability, and execution data

### ISSUE THREAD

**Issue by smullins3000** [distribworks/dkron#1018]
This is neither a bug nor a feature request but I couldn't find a better venue to ask a couple of questions. I've dug through the available documentation to the best of my ability but haven't found answer to these.

1) Is there any performance and/or scalability data available? 
I'd like to understand a bit how to determine how many nodes we're likely to need given X jobs and Y executions per second.

2) Data retention
Over time the execution data relating to the executions of the jobs will continue to grow. Given that Dkron uses an embedded DB storing the data to the local disk I have concerns about what will happen over time. 

Thanks!

**Comment by yvanoers** [comment]
Regarding 1:
Not that I'm aware of. There are a lot of variables that come into play, such as available resources on nodes, how much resources different jobs require and how the cluster is set up. A cluster with dedicated servers and dedicated agents will scale differently from one where servers are also be agents.
Even if there was data, it wouldn't be an easy task to extrapolate figures for a specific use case.

Regarding 2:
Only the last 100 executions are stored for each job. Older executions are automatically purged.

**Comment by victorcoder** [comment]
Hi @smullins3000 I run some benchmarks from time to time but nothing formal, everything that @yvanoers said applies.

Closing because the question has been answered.

**Comment by smullins3000** [comment]
Thank you both very much!
