### ISSUE TITLE
Why not initialize agent's reconcileCh channel?

### ISSUE THREAD

**Issue by idamiaoo** [distribworks/dkron#1023]
**Describe the bug**
Why not initialize agent's reconcileCh channel?

**Screenshots**

![image](https://user-images.githubusercontent.com/13446772/138015859-0b9750c5-9d37-494f-9237-a95a10c5ac93.png)

**Comment by victorcoder** [comment]
Honestly, I don't know, did you find any issue?

**Comment by lyiheng** [comment]
> Honestly, I don't know, did you find any issue?

no yet, It just causes the raft cluster update to be not real-time.
