### ISSUE TITLE
Nodes randomly going on and out of failed status

### ISSUE THREAD

**Issue by educlos** [distribworks/dkron#1030]
**Describe the bug**
Our setup is the following: 3 nodes in server mode, and lots of others to run the jobs.
More and more we have nodes that randomly change status, from `alive` to `failed` and vice versa, without warning, leading to jobs missing execution because of "no target node available".
We tried checking the logs in debug mode but found nothing, both on the servers nodes and on the ones changing status.
We setup dkron as a service, and when we notice a node stays in `failed` status long enough restarting the service put it back `alive`. In any case the service is always considered as active and alive, even when the node is in `failed` status.

```
[Unit]
Description=Dkron Agent

[Service]
User=root
ExecStart=/bin/bash -c '/usr/bin/dkron agent >> /var/log/dkron.log 2> /var/log/dkron-errors.log'
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

**To Reproduce**
Unfortunately none that we found so far

**Expected behavior**
When a node goes into `failed` status there is something on the logs explains why
Ideally it might nice to be able to receive an alert or something to tell us that a node changes status

** Specifications:**
 - OS: Ubuntu 18.04 / 20.04
 - Version dkron-pro, 3.1.7

**Comment by vcastellm** [comment]
I understand that the nodes that are flapping are the non-server ones? or do the servers also are changing status?

Does this issue started suddenly, without any reason or it was happening long ago? any change in your infra?

If using a cloud provider, all nodes in the same region?

You can try to tune the `--profile` param, setting it to "wan"

**Comment by educlos** [comment]
I haven't seen the servers changing status, but I'm not always checking it. 

I'm not sure when exactly it started, but we really noticed it more and more recently (linked to the update to 3.1.7?)

We are using cloud, and it looks like the nodes that are the most affected are the ones on the regions that are the most distant than the one the servers are. We're investigating networking, and we'll try using `wan` for the `--profile`, see if it helps

**Comment by educlos** [comment]
Update: we tested with `--profile wan`, and the result is the same, the nodes also go into `failed` status.
Something we're seeing on the logs is
```
memberlist: Marking YYY as failed, suspect timeout reached (1 peer confirmations)
```
does this means the nodes need to talk to each other, to confirm they are alive? If yes, on which port are they doing so?

**Comment by vcastellm** [comment]
the port is `8946` https://dkron.io/basics/getting-started/#usage  yes the nodes need to talk to each other to form a cluster.

**Comment by educlos** [comment]
@vcastellm  Is there a way to tell the nodes not to talk to each others but only to some specific ones?
We have nodes in multiple networks, and while they can all talk to the servers, they can't all talk to each other, and I think that's what's causing the issue.
It would be nice if we could set the nodes to only talk to the ones on the same network, or to the ones with the same value for a specific tag for instance.

**Comment by vcastellm** [comment]
That's not currently possible @educlos, Dkron uses serf library for clustering and it use a gossip protocol for that https://www.serf.io/docs/internals/gossip.html each node needs to talk p2p to other nodes.
