### ISSUE TITLE
http executor timeout cannot be configured to int type

### ISSUE THREAD

**Issue by cj506817364** [distribworks/dkron#1051]
**Describe the bug**

http executor.timeout cannot be configured to int type

## curl
curl 'http://192.168.1.70:8092/v1/jobs/every-5m-http-hello' \
  -X 'PUT' \
  -H 'Connection: keep-alive' \
  -H 'accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Origin: http://192.168.1.70:8092' \
  -H 'Referer: http://192.168.1.70:8092/ui/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cookie: jenkins-timestamper-offset=-28800000; remember-me=dXdhNGQ6MTY0NDM4NzY4MTczNTozNjY0OTdkY2I2MzY2ZWVjM2UyMDdlZmE3YjNjYWVlNTIwOTk3NjdmYTBiYmE5YWYxZjFmNzJhOTc2NWUxZDE0; JSESSIONID.ef921eb7=node0i94zbx9wkt1nf1hi58cxqdn493.node0; screenResolution=1792x1120' \
  --data-raw '{"id":"every-5m-http-hello","name":"every-5m-http-hello","displayname":"","timezone":"","schedule":"@every 5m","owner":"keter test","owner_email":"jin.chen@uwa4d.com","success_count":2249,"error_count":8,"last_success":"2022-01-28T04:11:59.160727111Z","last_error":"2022-01-28T04:06:59.01548827Z","disabled":false,"tags":null,"metadata":null,"retries":1,"dependent_jobs":null,"parent_job":"","processors":{},"concurrency":"forbid","executor":"http","executor_config":{"method":"GET","url":"http://192.168.1.70:8199/internal/webscript/hello","timeout":30},"status":"success","next":"2022-01-28T04:16:59Z","ephemeral":false,"expires_at":null}' \
  --compressed \
  --insecure

## resp
Unable to parse payload: json: cannot unmarshal number into Go struct field Job.executor_config of type string.

<img width="1119" alt="1" src="https://user-images.githubusercontent.com/33059555/151486711-88e7ac8c-ed4f-41a7-995e-dbfe84e5d718.png">
<img width="1073" alt="2" src="https://user-images.githubusercontent.com/33059555/151486716-506190ba-58e2-4d19-8c20-8ed4b47af515.png">
<img width="1069" alt="3" src="https://user-images.githubusercontent.com/33059555/151486720-2ac59432-1882-4ee2-bd9a-8d25bc8659ed.png">

**Comment by vcastellm** [comment]
Executor config should be always expressed in strings try `"timeout": "30"`
