### ISSUE TITLE
Memory leak: http connections keep opened

### ISSUE THREAD

**Issue by arvatoth-vcc** [distribworks/dkron#1062]
**Describe the bug**
We have got a dkron-3.1.10 inside Kubernetes cluster with single deployment (single pod only). We are using only one http executor which started at every 30 seconds. Every check opens a new http connection and all of previous keep established.

**Expected behavior**
Close previous established tcp connections or re-use them and do not open new to same endpoint.

**Screenshots**
![image](https://user-images.githubusercontent.com/6705008/155955023-3fadbb2d-516d-462c-87f0-bbaff8763923.png)

** Specifications:**
 - OS: Kubernetes v1.21.9 under Ubuntu 18.04 Bionic
 - Version dkron-3.1.0

**Additional context**
Lot of established tcp connections:

![image](https://user-images.githubusercontent.com/6705008/155955174-fce6c023-9f58-4ecc-8729-156582c1e57a.png)

Running inside the pod:

![image](https://user-images.githubusercontent.com/6705008/155956143-7b260a4c-eb78-4b18-9a44-a205595e8434.png)

Thank you!

**Comment by vcastellm** [comment]
Under my observations the number of open connections with hundreds of http jobs, the connections reach a stable point. How many jobs are you trying to run?

**Comment by arvatoth-vcc** [comment]
Only one job with one http executor. I think http executor sends `Connection: keep-alive` HTTP requests, but not reuse that.

**Comment by vcastellm** [comment]
Can you provide metrics or logs?

**Comment by vcastellm** [comment]
Can you confirm if this still happens in latest version?

**Comment by arvatoth-vcc** [comment]
I have just refreshed version to 3.2.2, I can refer in a few days.

**Comment by arvatoth-vcc** [comment]
![image](https://user-images.githubusercontent.com/6705008/226304981-0f895023-57fb-4e86-9fc9-d24540854fd9.png)

Unfortunately version upgrade did not solve the memleak problem.

**Comment by vcastellm** [comment]
Closing this because the workaround was merged
