### ISSUE TITLE
Does dkron support to config custom datebase?

### ISSUE THREAD

**Issue by eriklee1895** [distribworks/dkron#1075]
Hi，I want to deploy dkron on a cloud machine, I want to know how to use a custom database to save dkron data?

**Comment by vcastellm** [comment]
No, dkron uses its own internal storage, you can backup the data directory but the recommendation is to use a cluster to ensure HA and export a backup from time to time using https://dkron.io/usage/upgrade/#backup--restore

Another approach is to consider it as an ephemeral store, considering the source of truth your custom automation using the API, for example your applications
