### ISSUE TITLE
Job can't be read or run for some time after creating

### ISSUE THREAD

**Issue by renom** [distribworks/dkron#1080]
If `GET /jobs/{created_job_name}` or `POST /jobs/{created_job_name}` is performed immediately after creating the job, Dkron returns 404 error.

**Comment by vcastellm** [comment]
This is by design, it needs some time to propagate the changes over all nodes of the cluster.

**Comment by yvanoers** [comment]
I'm guessing that wouldn't be as trivial as it sounds (though I didn't look).
Out of curiosity: What is the use case?

**Comment by cobolbaby** [comment]
We built a task management platform based on dkron rest api. Whether the interface implementation is synchronous or asynchronous has a greater impact on the upper-layer application.

**Comment by renom** [comment]
> Out of curiosity: What is the use case?

Running the job immediately after creating. For example when expression `@every` is used and the required schedule is "every three hours starting now".
