### ISSUE TITLE
How to config cluster when nodes behind NAT?

### ISSUE THREAD

**Issue by eriklee1895** [distribworks/dkron#1088]
To form a cluster, we should configure server nodes with the address of its peers like:
```
# dkron.yml
server: true
bootstrap-expect: 3
join:
- 10.19.3.9
- 10.19.4.64
- 10.19.7.215
```

Now, I have some nodes behind NAT, so I want to know how to configure the ip address and port?

**Comment by vcastellm** [comment]
Nodes need to be able to see each other using IP, you need to give the nodes a reachable IP

**Comment by eriklee1895** [comment]
Thanks, I tried to set `advertise-addr` and `advertise-rpc-port` as external IP, it works
