### ISSUE TITLE
No Leader Problem: "dkron: 'dp-0542d8d317-0-0' and 'dp-0542d8d317-0-2' are both in bootstrap mode. Only one node should be in bootstrap mode, not adding Raft peer."

### ISSUE THREAD

**Issue by eriklee1895** [distribworks/dkron#1092]
I have 3 nodes in cluster, each node has this dkron.yml config:
```
server: true
bootstrap-expect: 1
log-level: debug
retry-join:
   - 10.225.119.90:9261
   - 10.225.94.12:9645
  ```
when 3 nodes started, there's no leader elected:
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/11907963/164244558-4b655221-6e9a-41ae-b8a0-8c5b5bafea1a.png">

I found log has this error:
"dkron: 'dp-0542d8d317-0-0' and 'dp-0542d8d317-0-2' are both in bootstrap mode. Only one node should be in bootstrap mode, not adding Raft peer."

Can you tell me what config is wrong?

**Comment by vcastellm** [comment]
You need to start the cluster with just 1 server in bootstrap mode if you use `bootstrap-expect: 1` then you can join other machines.

If you want to bootstrap a cluster with 3 nodes from the start, you need to set `bootstrap-expect: 3` and start all of them.

Feel free to reopen in case it doesn't work
