### ISSUE TITLE
Multiple commands are not supported

### ISSUE THREAD

**Issue by zhbUp** [distribworks/dkron#1093]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhbUp** [comment]
![image](https://user-images.githubusercontent.com/31853133/164977136-927164ca-a6dc-42c3-bc3d-a317372f9258.png)

In the above configuration, only sh abc.sh can be executed, and subsequent commands cannot be executed

**Comment by vcastellm** [comment]
You need to specify `shell: "true"` in the executor config
