### ISSUE TITLE
File and directory deletion wildcards are not supported

### ISSUE THREAD

**Issue by zhbUp** [distribworks/dkron#1094]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhbUp** [comment]
![image](https://user-images.githubusercontent.com/31853133/164976994-8aee8a75-981f-4658-83f4-bdf9eb193911.png)

There is a directory abc and a file abc.txt under the linux path  /home/ap/test

**Comment by vcastellm** [comment]
Try setting `"shell": "true"` in executor config
