### ISSUE TITLE
about retries

### ISSUE THREAD

**Issue by jianmaikj** [distribworks/dkron#1148]
**Describe the solution you'd like**
1. How to determine if a task failed in dkron? If I execute an http request task, can it determine whether it is successful or not based on the http response?
2. How to set a specified interval for failure retry?

thanks

**Comment by vcastellm** [comment]
1. Every executor has its own implementation on how to determine if the task failed, in the case of the http executor check the documentation page on the options for expect https://dkron.io/docs/usage/executors/http
2. It's not possible right now, retries are immediate.
