### ISSUE TITLE
Headers in executor config

### ISSUE THREAD

**Issue by ValentinaDrozdova** [distribworks/dkron#1181]
When specifying headers in the executor config, this header is not displayed in the request

**Comment by nikunj-badjatya** [comment]
Hi @ValentinaDrozdova 
How are you passing headers in http executor config ?
For me, I tried various combinations around this but it aint working and I am seeing "HTTP 415 Unsupported Media Type" on the server side.

Any ideas ?
`"[\"Content-Type: application/json\"]"` doesnt seem to work as explained in the doc.https://dkron.io/docs/usage/executors/http

**Comment by nikunj-badjatya** [comment]
> Hi @ValentinaDrozdova How are you passing headers in http executor config ? For me, I tried various combinations around this but it aint working and I am seeing "HTTP 415 Unsupported Media Type" on the server side.
> 
> Any ideas ? `"[\"Content-Type: application/json\"]"` doesnt seem to work as explained in the doc.https://dkron.io/docs/usage/executors/http

I got this figured out. It should look like this in dkron UI.
`"headers":"["Content-Type: application\/json"]"`
Or like this
`"headers":"["Content-Type: application/json"]"`

Both works.
