### ISSUE TITLE
Job duplicated scheduling in cluster mode

### ISSUE THREAD

**Issue by eriklee1895** [distribworks/dkron#1182]
**Describe the bug**
I have set dkron as cluster mode, which has 3 nodes, each dkron.yml is like this:
`advertise-addr: 10.174.255.198:9388
advertise-rpc-port: 9438
bootstrap-expect: 3
disable-usage-stats: true
join:
- 10.225.112.140:9624
- 10.225.78.183:9743
- 10.174.255.198:9388
log-level: debug
server: true`

I expect the job is only scheduled once when time up. But actually the job is scheduled 3 times(each node tiggered once).
I wonder if my parameters are incorrectly configured?

**To Reproduce**
1. setup a dkron cluster, whic has 3 nodes
`advertise-addr: 10.174.255.198:9388
advertise-rpc-port: 9438
bootstrap-expect: 3
disable-usage-stats: true
join:
- 10.225.112.140:9624
- 10.225.78.183:9743
- 10.174.255.198:9388
log-level: debug
server: true`

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/11907963/188349615-c6cc6eb4-ccf5-45bb-94f0-75c489fdbbaf.png">

2. create a job
Job config：
`
{
  "id": "test",
  "name": "test",
  "displayname": "test",
  "timezone": "Asia/Shanghai",
  "schedule": "@every 10s",
  "owner": "",
  "owner_email": "",
  "success_count": 36,
  "error_count": 0,
  "last_success": "2022-09-05T02:28:57.035292593Z",
  "last_error": null,
  "disabled": false,
  "tags": null,
  "metadata": null,
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": {},
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "date"
  },
  "status": "success",
  "next": "2022-09-05T02:29:07Z",
  "ephemeral": false,
  "expires_at": null
}
`

3. wait job tigger

**Expected behavior**
The job only scheduled once each period.

**Screenshots**
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/11907963/188349898-80c5d8fc-2b66-422d-867f-b67e3b29173a.png">

The job is scheduled by each node.

** Specifications:**
 - OS: ubuntu 20.04
 - Version: 3.0

**Comment by nikunjbadjatya** [comment]
This is by design as far as I know.
https://dkron.io/docs/usage/target-nodes-spec 
You will have to specify the tags while creating the job.

**Comment by eriklee1895** [comment]
Thank you @nikunjbadjatya 
I have tried to set tag for my job to limit running on only one node, it works!

**Comment by vcastellm** [comment]
Thanks for pointing that out @nikunjbadjatya

**Comment by sananguliyev** [comment]
> Thank you @nikunjbadjatya I have tried to set tag for my job to limit running on only one node, it works!

@eriklee1895 could you please give the sample job config. I am trying the tag but it still runs on all nodes.

**Comment by vcastellm** [comment]
@sananguliyev use
```
tags: {"role": "dkron:1"}
```

Check http://test.dkron.io:8080/ui/#/jobs/single-target/show

**Comment by lvphps** [comment]
concurrency forbid
