### ISSUE TITLE
Allow Capital alphabets for scheduler name.

### ISSUE THREAD

**Issue by suriya-xflowpay** [distribworks/dkron#1186]
We want to attach object IDs  to the scheduler name , which is basically alphanumeric characters consisting of both capital and small letters.

Right now, scheduler name is not accepting capital letters. It would be easier for debugging if we attach the Id, so this feature would be very useful for us and others as well. 

Great work btw :) , thank you for doing this.

**Comment by suriya-xflowpay** [comment]
Sure, but there is no search on displayName, or is there?

**Comment by suriya-xflowpay** [comment]
okay will try that, but any reason as to why this is not allowed?

**Comment by vcastellm** [comment]
Hey @suriya-xflowpay, it's because ids are intended to be like internal ids and url friendly, could have used UUIDs honestly, but not worth the change at this point.

Also take a look to meta data https://dkron.io/docs/usage/metatags
