### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by yoshida-git-ai** [distribworks/dkron#1196]
The official website says that "API Authentication" is disabled for the free plan, but can I use it if I have an access token?

It says that "Web UI authentication" is also invalid, so I would like to know in detail what kind of restrictions there are.

I have an access token and plan to do "GET" and "POST"

**Comment by yvanoers** [comment]
Everything in the OSS (free) version is accessible, there is no authentication mechanism in place.
Similarly authentication on the web UI does not exist, there is no login, the dashboard is directly accessible.

Hope this answers your question, closing the issue. Feel free to reopen if you have further questions.
