### ISSUE TITLE
when use domain in retry-join, it seem like dkron can't update the ip when dns changed.

### ISSUE THREAD

**Issue by yxxhero** [distribworks/dkron#1213]
**Describe the bug**
when using domains in retry-join, it seems like dkron can't update the IP when DNS changed.

**To Reproduce**
kubernetes headless service

**Expected behavior**
dkron can use the latest ip.

**Screenshots**
```
time="2022-10-25T23:56:47Z" level=info msg="2022-10-25T23:56:47.713Z [DEBUG] raft: voting for self: term=21693 id=dkron-server-0"
time="2022-10-25T23:56:47Z" level=info msg="2022-10-25T23:56:47.716Z [DEBUG] raft: asking for vote: term=21693 from=dkron-server-1 address=172.22.241.6:6868"
time="2022-10-25T23:56:47Z" level=info msg="2022-10-25T23:56:47.716Z [DEBUG] raft: asking for vote: term=21693 from=dkron-server-2 address=172.22.241.5:6868"
time="2022-10-25T23:56:47Z" level=info msg="2022-10-25T23:56:47.716Z [DEBUG] raft: calculated votes needed: needed=2 term=21693"
time="2022-10-25T23:56:47Z" level=info msg="2022-10-25T23:56:47.716Z [DEBUG] raft: vote granted: from=dkron-server-0 term=21693 tally=1"
time="2022-10-25T23:56:48Z" level=info msg="2022-10-25T23:56:48.423Z [ERROR] raft: failed to make requestVote RPC: target=\"{Voter dkron-server-2 172.22.241.5:6868}\" error=\"dial tcp 172.22.241.5:6868: i/o timeout\" term=21672"
```
172.22.241.5 172.22.241.5 are old IPs.

** Specifications:**
 - OS: [e.g. linux] linux 
 - Version [e.g. 2.0.1] 3.2.0

**Additional context**

**Comment by vcastellm** [comment]
You can use domains to resolve IPs but IPs should be fixed because Raft members use IPs to maintain the cluster details.

You can use a single node setup or assign fixed IPs.

**Comment by yxxhero** [comment]
@vcastellm hello. could I ask a question?
Can Raft members use domain to maintain the cluster details?

**Comment by vcastellm** [comment]
This is something that will need some investigation, but currently it's not supported.

**Comment by yxxhero** [comment]
@vcastellm Thanks very much. If domain issues are resolved, I think it will run well on k8s.

**Comment by yxxhero** [comment]
consul and vault can run on k8s. they will provide some ideas.

**Comment by vcastellm** [comment]
Yeah I need to dig deeper into that, thx!
