### ISSUE TITLE
Support retry-join in AWS ECS Tasks

### ISSUE THREAD

**Issue by destornillador** [distribworks/dkron#1221]
Hello Team. 

First of all, thank you for still maintaining the project.

**Is your feature request related to a problem? Please describe.**
I am migrating Dkron from AWS EC2 to AWS ECS Fargate. In EC2 I have a three-node cluster, with auto-join config enabled. As far as I could see, it is impossible to create a cluster if your nodes run in AWS ECS. 

**Describe the solution you'd like**
I would like to have a three-node cluster running in AWS ECS. Every time a container is destroyed, a new one auto-joins the cluster.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vcastellm** [comment]
Hi @destornillador first you'll need to setup the tasks so they have static ip's then you can create a config with the server IPs in it.
