### ISSUE TITLE
Bringing up on Docker Swarm doesn't work

### ISSUE THREAD

**Issue by mcowart123** [distribworks/dkron#1246]
**Describe the bug**
When trying to bring up a simple cluster (1 server/1 agent) on our production docker swarm cluster the agent can never connect to the server; it even tries connecting to the wrong IP address. Doing the exact same thing on our standalone test box (minus the deploy restrictions in the compose file) works flawlessly. I even added a placement restriction for the swam to force them to the same node and it doesn't work.

**To Reproduce**
Production swarm stack file:

`
version: '3.8'

services:
  dkron-server:
    image: centricdocker.azurecr.io/thirdparty/dkron
    ports:
      - "10120:8080"      
    volumes:
      - /var/apps/docker-shared/shared-dkron/root:/root
      - /media/scripts:/media/scripts
      - /var/apps/docker-shared/shared-dkron/dkron-server/data:/data
    command: dkron agent --server --log-level=debug --bootstrap-expect=1 --data-dir=/data --node-name dkron-primary
    stop_grace_period: 3m
    deploy:
     replicas: 1
     placement:
        constraints:
        - node.labels.dkron==allowed

  dkron-agent:
    image: centricdocker.azurecr.io/thirdparty/dkron
    depends_on:
      - dkron-server
    volumes:
      - /var/apps/docker-shared/shared-dkron/root:/root
      - /media/scripts:/media/scripts
    command: dkron agent --retry-join=dkron-server:8946 --log-level=debug --tag agent=true
    stop_grace_period: 3m
    deploy:
     replicas: 1
     placement:
        constraints:
        - node.labels.dkron==allowed
`
Does not work.

Standalone server stack file:
`
version: '3.8'

services:
  dkron-server:
    image: centricdocker.azurecr.io/thirdparty/dkron
    ports:
      - "10120:8080"      
    volumes:
      - /var/apps/docker-shared/shared-dkron/root:/root
      - /media/scripts:/media/scripts
      - /var/apps/docker-shared/shared-dkron/dkron-server/data:/data
    command: dkron agent --server --log-level=debug --bootstrap-expect=1 --data-dir=/data --node-name dkron-primary
    stop_grace_period: 3m    

  dkron-agent:
    image: centricdocker.azurecr.io/thirdparty/dkron
    depends_on:
      - dkron-server
    volumes:
      - /var/apps/docker-shared/shared-dkron/root:/root
      - /media/scripts:/media/scripts
    command: dkron agent --retry-join=dkron-server:8946 --log-level=debug --tag agent=true
    stop_grace_period: 3m
`
This works perfectly.

**Expected behavior**
The swarm should work and the agent should try to connect to the correct internal IP of 10.0.61.9, but it is trying to connect to 10.0.61.2 instead. The server/web-ui is up.

**Screenshots**
<img width="2078" alt="web-ui" src="https://user-images.githubusercontent.com/11339815/208487322-b004f4e9-05ae-49d7-bae4-a36520d2ff02.png">
<img width="1790" alt="stack_layout" src="https://user-images.githubusercontent.com/11339815/208487355-58f1f0b8-b654-4092-8960-6ce8c8801abd.png">
<img width="1520" alt="server_container_ip" src="https://user-images.githubusercontent.com/11339815/208487378-3e834b31-119a-4138-9a0b-d7b14af528ef.png">
<img width="1292" alt="server_container_logs" src="https://user-images.githubusercontent.com/11339815/208487398-bf8e180b-3a6e-4b4b-98cb-ff010946c378.png">
<img width="1411" alt="agent_container_logs" src="https://user-images.githubusercontent.com/11339815/208487416-d12fa233-43be-452d-86af-91e29d401392.png">

** Specifications:**
 - OS: Linux
 - VersionLatest

**Comment by kennykarnama** [comment]
I think it is related to docker swarm IP resolve: https://github.com/moby/moby/issues/41766

**Comment by vcastellm** [comment]
Long time since I used docker swarm, but not sure if this is a Dkron error, I guess it should be related to swarm, so closing this at this time.

Feel free to reopen in case it's related to Dkron.
