### ISSUE TITLE
timeout POSTing jobs - panic invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jzalmanovich** [distribworks/dkron#1265]
**Describe the bug**
as the load slightly increases we are experiencing timeout on creating jobs and seeing this error in the logs of all the nodes
**To Reproduce**
small load of several hundreds jobs in a time frame of about 10 to 15 minutes

**Expected behavior**
no timeouts and no errors in the logs

**Screenshots**
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: #033[31m2023/02/01 19:49:44 [Recovery] 2023/02/01 - 19:49:44 panic recovered:
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: runtime error: invalid memory address or nil pointer dereference
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:212 (0x434cba)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/signal_unix.go:734 (0x44dad2)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/work/dkron/dkron/dkron/api.go:248 (0x1d83f88)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1db05a2)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/work/dkron/dkron/dkron/api.go:128 (0x1db0585)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d82e4e)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82e34)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc446d9)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc446c0)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc437b3)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc43772)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39ee9)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc39ecf)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc399bb)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:2867 (0x723882)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:1932 (0x71ecac)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s:1371 (0x46d8e0)
Feb  1 19:49:44 dkron-vmss-node00000C dkron[332873]: #033[0m
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: #033[31m2023/02/01 19:49:46 [Recovery] 2023/02/01 - 19:49:46 panic recovered:
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: runtime error: invalid memory address or nil pointer dereference
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:212 (0x434cba)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/signal_unix.go:734 (0x44dad2)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/work/dkron/dkron/dkron/api.go:248 (0x1d83f88)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1db05a2)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/work/dkron/dkron/dkron/api.go:128 (0x1db0585)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d82e4e)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82e34)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc446d9)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc446c0)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc437b3)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc43772)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39ee9)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc39ecf)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc399bb)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:2867 (0x723882)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:1932 (0x71ecac)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s:1371 (0x46d8e0)
Feb  1 19:49:46 dkron-vmss-node00000C dkron[332873]: #033[0m

Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: 2023/02/01 19:52:18 [Recovery] 2023/02/01 - 19:52:18 panic recovered:
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: runtime error: invalid memory address or nil pointer dereference
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/panic.go:212 (0x434cba)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/signal_unix.go:734 (0x44dad2)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/work/dkron/dkron/dkron/api.go:272 (0x1d8432b)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1db05a2)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/work/dkron/dkron/dkron/api.go:128 (0x1db0585)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x1d82e4e)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/work/dkron/dkron/dkron/api.go:134 (0x1d82e34)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc446d9)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0xc446c0)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc437b3)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0xc43772)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0xc39ee9)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0xc39ecf)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0xc399bb)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:2867 (0x723882)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /opt/hostedtoolcache/go/1.16.8/x64/src/net/http/server.go:1932 (0x71ecac)
Feb 01 19:52:18 dkron-vmss-node00000A dkron[360393]: /opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s:1371 (0x46d8e0)

![image](https://user-images.githubusercontent.com/41348183/216180528-95c61c10-35fb-4bac-b168-c2cc4ef73ea2.png)

** Specifications:**
 root@dkron-vmss-node00000C:~# uname -a 
Linux dkron-vmss-node00000C 5.15.0-1031-azure #38~20.04.1-Ubuntu SMP Mon Jan 9 18:23:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@dkron-vmss-node00000C:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

**Additional context**
5 nodes cluster
![image](https://user-images.githubusercontent.com/41348183/216184747-cc46502f-7686-402b-afcb-5ee4f9578704.png)

**Comment by jzalmanovich** [comment]
leader node is keep changing seeing this in the logs

cluster leadership lost" node=dkron-vmss-node00000E
Feb 02 12:53:26 dkron-vmss-node00000E dkron[452903]: time="2023-02-02T12:53:26Z" level=info msg="dkron: monitoring leadership" node=dkron-vmss-node00000E
Feb 02 12:53:26 dkron-vmss-node00000E dkron[452903]: time="2023-02-02T12:53:26Z" level=info msg="dkron: cluster leadership acquired" node=dkron-vmss-node00000E
Feb 02 12:53:26 dkron-vmss-node00000E dkron[452903]: time="2023-02-02T12:53:26Z" level=info msg="dkron: monitoring leadership" node=dkron-vmss-node00000E
Feb 02 12:53:26 dkron-vmss-node00000E dkron[452903]: time="2023-02-02T12:53:26Z" level=info msg="agent: Starting scheduler" node=dkron-vmss-node00000E
Feb 02 12:53:27 dkron-vmss-node00000E dkron[452903]: time="2023-02-02T12:53:27Z" level=fatal msg="dkron: failed to establish leadership" error="cron is already configured, can not start scheduler" node=dkron-vmss-node00000E
Feb 02 12:53:28 dkron-vmss-node00000E systemd[1]: dkron.service: Main process exited, code=exited, status=1/FAILURE

**Comment by jzalmanovich** [comment]
The issue was resolved after upgrading to stronger servers.

**Comment by zhaozhenxiang** [comment]
This is the crash log.
`
time="2025-05-16T08:02:17+08:00" level=fatal msg="agent: error applying SetExecutionType" error="timed out enqueuing operation" node=mongous
time="2025-05-16T08:02:17+08:00" level=fatal msg="agent: error applying SetExecutionType" error="timed out enqueuing operation" node=mongous
time="2025-05-16T08:02:17+08:00" level=fatal msg="agent: error applying SetExecutionType" error="timed out enqueuing operation" node=mongous
time="2025-05-16T08:02:18+08:00" level=info msg="No valid config found: Applying default values." error="Config File \"dkron\" Not Found in \"[/etc/dkron /.dkron /src/install/dkron_3.2.1/config]\""
`
The startup command is
dkron agent --server --bootstrap-expect=1 --http-addr ":8079"
Startup
Configuration is debian11, 4C16G, currently dkron has 45k scheduled jobs, and scheduled tasks are mostly concentrated at the 0th minute of each hour. Most crashes occur at the hour, when there are more scheduled tasks, such as 08:00, 09:00. It takes up about 5G memory during normal time, and about 9G-10G memory during peak time.
I think the memory usage is a bit too much.
Any suggestions?

![Image](https://github.com/user-attachments/assets/5bb70d86-f244-4171-b472-ecf5684bdb7f)

**Comment by vcastellm** [comment]
> Any suggestions?

Can you distribute the job executions between the hour?
