### ISSUE TITLE
API calls quota exceeded! maximum admitted 1 per Second.

### ISSUE THREAD

**Issue by AlexBlack2202** [distribworks/dkron#1266]
**Describe the bug**
i have 2 HTTP Executor cron run in same time, and 1 run, another not run,  it show API calls quota exceeded! maximum admitted 1 per Second. in console log

**To Reproduce**
1. create two http executor join in same cron
2. make it run
3. See error

**Expected behavior**
Run multiple HTTP Executor job  concurrent. or have config for API calls quota

** Specifications:**
 - OS: ubuntu 18.04
 - Version 3.2.1

Any one can help me to increase number API calls in 1 second? Thank

**Comment by vcastellm** [comment]
Ok, I see, the issue should be on the url endpoint not in Dkron, what service are you calling?

**Comment by AlexBlack2202** [comment]
i call my own api, it took 1-2 minute

for job 1
{
    "name":"job1",
    "schedule":"0 4 9,11,13,15,17,19,22 * * ?",
    "executor":"http",
    "executor_config" : {
 "method": "PUT", "url": "http://myownlomain.com/api/me/1",  "timeout": "900"
 }
}

for job2

{
    "name":"job2",
    "schedule":"0 4 9,11,13,15,17,19,22 * * ?",
    "executor":"http",
    "executor_config" : {
 "method": "PUT", "url": "http://myownlomain.com/api/me/2",  "timeout": "900"
 }
}

it almoust the same, the difference is job name and url

**Comment by AlexBlack2202** [comment]
> Ok, I see, the issue should be on the url endpoint not in Dkron, what service are you calling?

do you have any ideal about this

**Comment by vcastellm** [comment]
It looks like the issue is on `http://myownlomain.com` not in Dkron, there's not rate limits in Dkron.
