### ISSUE TITLE
Support to rename jobs

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#1309]
**Is your feature request related to a problem? Please describe.**

It's so weird that changing the name of job will create a new job.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vcastellm** [comment]
Name of the jobs are unique, they are the id of the job, as the storage is not a relational DB, changing names will have an impact in storage rebuild, you can always change the Display Name.

Use the Display Name for human naming and use an ID in `name`
