### ISSUE TITLE
Cannot pass multiple header values to server when using http executor

### ISSUE THREAD

**Issue by shivangivar** [distribworks/dkron#1313]
I am creating a simple job that will hit an Rest API using http executor but issue is coming as it is not able to pass **Authorization key** in the header, hence my request is not getting authorized. 

`{"message":"Something went wrong","exceptionClass":"org.springframework.security.authentication.AuthenticationCredentialsNotFoundException"}`

**Comment by cobolbaby** [comment]
Could you share your dkron-executor-http config?

**Comment by shivangivar** [comment]
@cobolbaby here is the http executor config
`"executor_config": {
  "body": "{}",
  "debug": "true",
  "expectCode": "200",
  "headers": "[\"Authorization:Basic YWJjOmFiYw==\",\"Content-Type:application/json\"]",
  "method": "POST",
  "timeout": "25200",
  "url": "http://abc.com/v2/test/demo/ap-southeast-1"
},`


If I pass other header also it doesn't forward them to the server

**Comment by vcastellm** [comment]
As you have `debug` activated, the request should be logged in logs, check the logs and search for the request/response headers.

Closing because I checked it in tests and all headers are being sent, so it should be a problem in the server side.

**Comment by shivangivar** [comment]
Hi @vcastellm as i am new to dkron i have installed it using binaries in linux ec2 can you tell me how can i enable logs or view logs ?

**Comment by cobolbaby** [comment]
Same as https://github.com/distribworks/dkron/issues/1181

**Comment by shivangivar** [comment]
My headers look like this in UI tried both way but still doesn't work @cobolbaby @vcastellm 

"headers":"["Authorization:Basic dGVzdGluZzpwdXJwb3Nl,"Content-Type:application/json"]"

**Comment by shivangivar** [comment]
Don't close this issue , as this is still not solved

**Comment by vcastellm** [comment]
> Hi @vcastellm as i am new to dkron i have installed it using binaries in linux ec2 can you tell me how can i enable logs or view logs ? 

Logs should be in journalctl if you installed using packages.

If not, output always is in stout so you can redirect to your needs

**Comment by vcastellm** [comment]
> This job is working with curl executor why not with http executor ? @vcastellm @niclash 

What you mean curl executor?

**Comment by shivangivar** [comment]
@vcastellm  I mean using shell executor to hit api using curl command, It is passing the header values but whereas in http executor my header value are not passed and api is throwing unauthorized error

**Comment by vcastellm** [comment]
Headers should look like this in the UI
<img width="422" alt="image" src="https://user-images.githubusercontent.com/47026/233866216-c65704fc-156e-41e4-9580-c7e8ea02e3ac.png">

Take a look to this job and its executions: http://test.dkron.io:8080/ui/#/jobs/multi-headers/show

Also take a look to the docs https://dkron.io/docs/usage/executors/http it should be formatted as a json string, but when using the UI it takes care of the escaping.

Closing because working as expected
