### ISSUE TITLE
Add field title to job meta in `/ui/#/jobs/:name/show` 

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#1317]
**Is your feature request related to a problem? Please describe.**

Job's tags and config don't have a Title, which makes the UI display more compact.

![2023-04-17 13-21-05屏幕截图](https://user-images.githubusercontent.com/11460848/232390827-4e3cb045-085c-4f42-b7e0-1acde9034b61.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vcastellm** [comment]
Are you suggesting to include a title?

**Comment by cobolbaby** [comment]
> Are you suggesting to include a title?

Yes

**Comment by vcastellm** [comment]
Field names are now showing in the 4.x UI and I included some missing fields, see https://github.com/distribworks/dkron/pull/1432/commits/aec162a8b3c0165c82365e44b2174977956c2a7a
