### ISSUE TITLE
Should output.TotalWritten be judged after cmd.Wait() is executed?

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#1319]
https://github.com/distribworks/dkron/blob/9982ceb9af37543d5133e506899d245e8fa53b6e/builtin/bins/dkron-executor-shell/shell.go#L130-L135

Should output.TotalWritten be judged after cmd.Wait() is executed?

**Comment by vcastellm** [comment]
Yes, it makes sense.
