### ISSUE TITLE
Not showing cron jobs already created 

### ISSUE THREAD

**Issue by johnnyaussi** [distribworks/dkron#1329]
Hi,

I installed Dkron as a docker container via this command:
`
docker run -d -p 8085:8080 -v ~/dkron.data:/dkron.data --name dkron dkron/dkron agent --server --bootstrap-expect=1 --data-dir=/dkron.data`

The problem is that the webGUi doesn't show cron jobs I had alread created before installing dkron.

Can it be fixed somehow?

Thanks

**Comment by vcastellm** [comment]
How about the API? are you getting jobs from the `/v1/jobs` endpoint?

**Comment by johnnyaussi** [comment]
> `/v1/jobs` endpoint

I don't know. Is showing existing jobs a feature that should already work in Dkron by default.
Thanks

**Comment by yvanoers** [comment]
> cron jobs I had alread created before installing dkron

I'm going to take a guess here and assume you mean cron jobs configured in `/etc/crontab` and accompanying config files.
If so, then no, Dkron does not detect or take over jobs from an existing local crontab.

Dkron is able to do the scheduling like a typical cron daemon can, and then some, but it is not a drop-in replacement in the sense that it picks up where another cron daemon left off.

Also, Dkron by itself is not able to import a regular crontab. You might be able to fashion a script that makes an API compatible JSON from crontab and import that, though.

**Comment by johnnyaussi** [comment]
> > cron jobs I had alread created before installing dkron
> 
> I'm going to take a guess here and assume you mean cron jobs configured in `/etc/crontab` and accompanying config files. If so, then no, Dkron does not detect or take over jobs from an existing local crontab.
> 
> Dkron is able to do the scheduling like a typical cron daemon can, and then some, but it is not a drop-in replacement in the sense that it picks up where another cron daemon left off.
> 
> Also, Dkron by itself is not able to import a regular crontab. You might be able to fashion a script that makes an API compatible JSON from crontab and import that, though.

ok, but I don't think it is worth  struggling with it. I'll go for the old way. Thanks anyway.
