### ISSUE TITLE
Servers have inconsistency between jobs

### ISSUE THREAD

**Issue by sananguliyev** [distribworks/dkron#1371]
I have test cluster where I spin-up 3 servers and 1 agent. I used API to create job. It's created on server one and on each refresh of web app load balancer hits different servers and if it's not server 1 it says no job. I do not know why jobs are not synced between servers.

**Comment by yvanoers** [comment]
My guess would be that your servers aren't actually in a cluster.
The UI should report the other nodes if the cluster is operating correctly.

There isn't enough information to do a proper analysis.

**Comment by sananguliyev** [comment]
@yvanoers thanks for your answer. Actually that was the weird part. it shown the nodes in ui but not sync the jobs. btw, I started with one node and added second one afterwards, and then 3rd. 

Actually since it was testing I just removed and recreate 3 at once and then it worked fine.
