### ISSUE TITLE
Restore API is not working 

### ISSUE THREAD

**Issue by vishwanadha-chintam** [distribworks/dkron#1376]
I am not able to restore the jobs that are taken from the version v1 of Dkron either in the current Dkron as well as the version v3 Dkron
I used the curl localhost:8080/v1/jobs > file.json which is working perfectly, even with all other REST APIs but when I use the restore command on the server, it is through a 404 error in version v1 of Dkron, I followed the official page and upgraded the Dkron version to V3. I used the same command that was mentioned on the official page to restore from the JSON file, even though it is not able to update, not even giving any error to find the issue, Please help me on this, thank you

**Comment by cobolbaby** [comment]
Could you share the test case?

**Comment by vishwanadha-chintam** [comment]
this command itself is not working **curl localhost:8080/v1/jobs > file.json**

**Comment by Viox-LJ** [comment]
i have the same problem.  I have my jobs v1 on a file. But when try to restore on v3 using the commando the endpoint /restore give me 404:

[ 0 ] ~ # curl localhost:8080/v1/restore --form 'file=@jobs-dkron.json'
[ 0 ] ~ # curl localhost:8080/v1/restore
404 page not found

Any idea? I need restore all my jobs.

Thx
BR

**Comment by cobolbaby** [comment]
Can you provide steps to reproduce the behavior? such as dkron version, startup options, filepath of jobs-dkron.json.

**Comment by Viox-LJ** [comment]
I have 1 Server with Dkron v1 with all my jobs. I do the export using this: https://gist.github.com/pjz/94f4bd81a0897fd64db44593078e2156

Im trying to import in a new server with Dkron v3

The backup is a json. But i cant import the jobs.
Im trying using the restore script and the command mention before but not work.

The file is in a path /root inside of the dkron server

**Comment by cobolbaby** [comment]
> Im trying to import in a new server with Dkron v3

What is the specific version of dkron v3?

> The file is in a path /root inside of the dkron server

If the jobs-dkron.json file is in the /root directory, did you also execute curl in this directory?

**Comment by vcastellm** [comment]
Closing for lack of response and no reproducability
