### ISSUE TITLE
`cmd.Process.Kill()` does not clean up the started process, causing the job to remain running.

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#1385]
**Describe the bug**

https://github.com/distribworks/dkron/blob/master/builtin/bins/dkron-executor-shell/shell.go#L119C1-L124

**To Reproduce**

**Expected behavior**

**Screenshots**

Init State:

![2023-09-18 16-58-21屏幕截图](https://github.com/distribworks/dkron/assets/11460848/94363bb3-9457-4e86-8e0f-077f1925b1c8)

After cmd.Process.Kill()

![1265843327](https://github.com/distribworks/dkron/assets/11460848/76895224-2ff1-4e01-b9f5-cf4b38acd2af)

**Specifications:**
 - OS: dkron/dkron:3.2.4
 - Version: [v3.2.4](https://github.com/distribworks/dkron/releases/tag/v3.2.4)

**Additional context**

**Comment by yvanoers** [comment]
Have you encountered a situation where the process didn't get killed?
If so, any insights into why?

**Comment by cobolbaby** [comment]
os.Process.Kill() only kill the parent process, not including the child processes.
