### ISSUE TITLE
Node targeting appears to be broken

### ISSUE THREAD

**Issue by durch** [distribworks/dkron#1402]
**Describe the bug**
As best I can describe is that node targeting does not work if the leader does not have targeted tags. Situation is the following four nodes in the cluster, 3 servers and one worker (I guess, not sure if workers need to be explicitly designated or is `server = false` enough). 

Three server nodes have `"region": "global"` tag, and worker has `"region": "us"` tag. Jobs targeted with `"region": "us:1"`, fail to run with `level=error msg="grpc: Error calling gRPC method" error="rpc error: code = Unknown desc = no target nodes found to run job tron" method=RunJob`, even tough worker has the correct tag, jobs targeted with `"region": "global:1"` run as expected

**Expected behavior**
Jobs should run on the correctly tagged worker

**Screenshots**

- Cluster setup:

<img width="1352" alt="Screenshot 2023-10-12 at 22 41 10" src="https://github.com/distribworks/dkron/assets/7261674/350507e8-d6c8-4070-9536-9233efc731a3">

**Specifications:**

 - OS: Ubuntu 22.04
 - Version: 3.2.6

**Comment by vcastellm** [comment]
Hey sorry for the delayed response, can you try without `:1` just `us`?

**Comment by vcastellm** [comment]
Fixed in https://github.com/distribworks/dkron/commit/41c82f3e7014d86313919dad8953bf7b4d76f7c1

**Comment by durch** [comment]
Thank you!
