### ISSUE TITLE
Installing Repo for Debian and yum not found

### ISSUE THREAD

**Issue by shivangivar** [distribworks/dkron#1437]
**Repo for Debian and Yum are giving error 404 not found**

![Capture](https://github.com/distribworks/dkron/assets/64467134/a6672718-18bc-4067-be6f-5c8a319824ad)

It is giving 404 not found for both yum and Debian

**Comment by vcastellm** [comment]
It works for me https://repo.distrib.works/ feel free to reopen in case of doubts
