### ISSUE TITLE
Click the `Run` / `Toggle` button, but no API request is sent 

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#1469]
**Describe the bug**

**To Reproduce**

<img width="1434" alt="截屏2024-02-09 08 29 34" src="https://github.com/distribworks/dkron/assets/11460848/22a1bf05-a8fb-4bb4-bafe-faae252e5eb9">

<img width="1440" alt="截屏2024-02-09 08 35 23" src="https://github.com/distribworks/dkron/assets/11460848/6a707151-894e-4674-8d6a-288bd8b559ab">

**Expected behavior**

**Screenshots**

** Specifications:**
 - OS: [e.g. linux]
 - Version: 4.0.0-beta3 

**Additional context**

**Comment by vcastellm** [comment]
Nice catch, thanks for reporting! The migration to reac-admin v4 has many breaking changes, fixed and added some improvements here https://github.com/distribworks/dkron/pull/1432/commits/86ce37ff390ee4de9717bd0a512a0e83d3a927f3
