### ISSUE TITLE
Font size in the `JobShow.tsx` is inconsistent

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#1475]
**Describe the bug**

**To Reproduce**

<img width="948" alt="截屏2024-02-12 07 49 50" src="https://github.com/distribworks/dkron/assets/11460848/c065606f-767d-434c-a6bd-66782f3bcc83">

**Expected behavior**

**Screenshots**

** Specifications:**
 - OS: [e.g. linux]
 - Version: 4.0.0-beta4

**Additional context**

**Comment by vcastellm** [comment]
You mean the font of the JSON fields?

**Comment by cobolbaby** [comment]
> You mean the font of the JSON fields?

Yes

**Comment by vcastellm** [comment]
Fixed in v4
