### ISSUE TITLE
Documentation lacking / UI - Busy menu / Time zones

### ISSUE THREAD

**Issue by fabltd** [distribworks/dkron#1530]
The Documentation appears to be lacking any details of the following:

In the UI the busy menu shows jobs that are completed?

- Should this be called History instead of busy?  

- Where is the data stored and is there a way to clear this History. My concen is that this will cuase the config file to grown in size without any control?

Second there appears to be no discussion around time zones. When creating a Job we can specify a timezone - example "timezone": "Europe/Berlin".

- Is this with or without DST applied? 
- What is the time zone reference? 
    - Local server time
    - UTC?

Thanks

**Comment by fabltd** [comment]
Any update on this. We were considering the pro licence but I think we need an alternative ?

**Comment by yvanoers** [comment]
> Any update on this. We were considering the pro licence but I think we need an alternative ?

You seem to have things backwards. If you [don't have a Pro license, you get community support](https://dkron.io/docs/pro/commercial-support) without any guarantees on response times or anything. [With a Pro license, conditions can be agreed upon](https://dkron.io/docs/pro/commercial-faq#can-i-request-a-change-to-the-license-terms).

Please note that I am in no way involved when it comes to Pro licenses, I am only part of the community.

> In the UI the busy menu shows jobs that are completed?

I'm unsure, it's been a while for me.
It used to be the case though that the execution history would keep only 100 previous executions, preventing it from hogging space.

> Is this with or without DST applied?

Whether DST applies depends on the time and the timezone, not the application using it. [Europe/Berlin has different offsets](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#BERLIN) for SDT and DST, so the correct time is automatigically applied.

> What is the time zone reference?

I don't understand the question, can you elaborate?

**Comment by fabltd** [comment]
In my experience the way a company treats issues is relative to there commerical support. Why would I pay for a commerical licence when the solution is untested.

> I'm unsure, it's been a while for me.
It used to be the case though that the execution history would keep only 100 previous executions, preventing it from hogging space.

This should be inculded in the docs !

> Is this with or without DST applied?

> Whether DST applies depends on the time and the timezone, not the application using it. [Europe/Berlin has different offsets](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#BERLIN) for SDT and DST, so the correct time is automatigically applied.

So it will adapt. Say the event is set to be at 8 PM the day before SDT is applied will the even occour at 9 PM or will it revert to 8 PM DST.  

We are looking at this for a scheduler for events so this is important. Some other tools we have looked at get this wrong.

> 
> What is the time zone reference?
> 
> I don't understand the question, can you elaborate?

Time zones are often calualted bases on the system timing being UTC. If the system time is not UTC ( time zone reference) then they can be off.

**Comment by yvanoers** [comment]
> Say the event is set to be at 8 PM the day before SDT is applied will the even occour at 9 PM or will it revert to 8 PM DST.

Suppose a schedule of `* 0 20 * * *` that is set to Europe/Berlin.
On Oct 26 2024, the job will run at 20:00 Berlin time, which is 18:00 UTC time.
On Oct 27 2024, the job will run at 20:00 Berlin time, which is 19:00 UTC time.

> Time zones are often calualted bases on the system timing being UTC. If the system time is not UTC ( time zone reference) then they can be off.

Dkron does not assume the system to be in any specific time zone. Schedules that have a time zone specified will run according to that time zone, regardless of the time zone the machine has.
When no time zone is specified, Dkron schedules jobs in the machine's local time zone.
See https://dkron.io/docs/usage/cron-spec#time-zones.

**Comment by fabltd** [comment]
Ok it seems the Time zone only works with cron specification. If any other method is used to specify the time this does not work?

Also why does a Job need an email address there appears to be no reference to if / when emails are sent?

**Comment by vcastellm** [comment]
> In the UI the busy menu shows jobs that are completed?

No, it shows the current running jobs.

> Where is the data stored and is there a way to clear this History. My concen is that this will cuase the config file to grown in size without any control?

Dkron only stores the last 100 executions to prevent and control disk exhaustion.

> Ok it seems the Time zone only works with cron specification. If any other method is used to specify the time this does not work?

Except for intervals, time zones can be used in both cron and RFC3339 specs, see https://dkron.io/docs/usage/cron-spec/

> Also why does a Job need an email address there appears to be no reference to if / when emails are sent?

@fabltd it doesn't need the email address, it's only used for notifications you can omit it if you it's not needed.

Feel free to reopen in case there are more doubts
