### ISSUE TITLE
Memory Leak/High Memory Usage when running jobs at scale.

### ISSUE THREAD

**Issue by krazykelv** [distribworks/dkron#1553]
**Describe the bug**
As we've gradually increased the number of jobs running on our cluster, we've now noticed that the dkron agent very quickly grows in memory usage to unsustainable levels.  After just a few hours, the memory usage of the dkron agent reaches 5-7GB, causing processes to be killed from the OS OOM manager.

**Server Specifications:**
 - OS: Ubuntu 20.04
 - Version: 3.2.6
 - EC2 m6g.xlarge nodes with 16GB memory

**Our Setup**
 - A cluster of 6 nodes
 - Around 1,000 scheduled jobs in the cluster with a large variation of run times and start schedules.
 - Most jobs are configured with concurrency=forbid, but around 100 jobs allow concurrency.
 - There could be around 500-700 jobs running at any given time, including duplicates from concurrency.
 - I've estimated we do about 2,000 job executions per hour
 - Executor: shell
 - Shell Output: The bulk of our logs go to an external logging system, so each job execution produces only 500 bytes of output.

**Expected behavior**
The dkron agent should have a method of releasing memory regularly over the course of its lifetime to prevent this kind of large memory usage.

Investigation should be done as to what is the primary cause of the large memory usage.  If it's from job execution data, there should be a method to remove old execution data over time.

**Comment by vcastellm** [comment]
Hi @krazykelv What version are you using?

**Comment by krazykelv** [comment]
Hi @vcastellm . Using version 3.2.6.  I've briefly tried version 3.2.7 and the latest 4.05 beta, however they have a different issue causing jobs to get stuck so they're never marked as completed

**Comment by vcastellm** [comment]
That should be ok @krazykelv I just wanted to check you're not in 2.x or something.

This is an interesting issue, if you check the execution logs in the UI it's just 500bytes? Dkron stores execution logs in the DB as you may know, but it's limited to the last 100 executions, so anything beyond that should be recycled and cleaned from mem.

If it's really 500 bytes that's 1000 * 100 * 500 that's ~50mb of data, if you can doublecheck what really ends up in Dkron DB so we can confirm, because it can easily skyrocket.

**Comment by krazykelv** [comment]
Ah that detail about storing the last 100 executions gave me a clue.  I found the issue was that our more recently added jobs had a bug causing huge logs to be stored.  Thanks for your help with this.

It might be helpful for others in the future if some of this detail was outlined on the Processors Docs page... https://dkron.io/docs/usage/processors/.  Something about storing output of the last 100 executions, and the fact that the log processor stores its data in memory, so not good for storing large logs. @vcastellm

**Comment by vcastellm** [comment]
Thanks @krazykelv I'm going to add the info to the docs.

Let me know if you have any further suggestion.
