### ISSUE TITLE
[k8s] One Dkron Server Pod Fails with "(panic: log not found)" Error During Raft Setup

### ISSUE THREAD

**Issue by panapol-p** [distribworks/dkron#1557]
**Describe the bug**
I've been testing dkron on Kubernetes and have noticed that one of the dkron server pods often becomes unusable. It shows a panic with a "log not found" error while setup Raft.

**To Reproduce**
install using dkron helm chart

**Screenshots**
panic log
<img width="1644" alt="image" src="https://github.com/user-attachments/assets/e81fb587-7828-4ea4-842a-157e426387ab">
one pod error
<img width="763" alt="image" src="https://github.com/user-attachments/assets/1e2503bc-7e31-49f0-bb97-42b9b4d6d9ff">
I also tried installing it in a different namespace, and one pod encountered the same error
<img width="760" alt="image" src="https://github.com/user-attachments/assets/0b63633a-f1c7-4a64-b248-a033d4540bd1">

** Specifications:**
 - Dkron version : [4.0.0-beta6-light](https://hub.docker.com/layers/dkron/dkron/4.0.0-beta6-light/images/sha256-a82fd798c259a754236c3f7524f1045080e9f0088a2a43f3b627b753bce86bd4?context=explore)

**Comment by panapol-p** [comment]
During the upgrade from Dkron v3 to v4, we encountered a bug that caused unexpected behavior in our cluster. After some investigation, I was able to resolve the issue by following these steps:

by the way I resolved this issue by step like this,
1. [backup job](https://dkron.io/docs/usage/upgrade/#backup--restore)
2. uninstall helm chart
3. delete old pvc
4. re-install helm chart
5. [restore job](https://dkron.io/docs/usage/upgrade/#backup--restore)

**Comment by vcastellm** [comment]
Thanks for reporting the procedure @panapol-p

**Comment by panapol-p** [comment]
I'm planning to fix the Helm chart by adding a better rollback strategy. The idea is to update new instances one by one and shut down old ones gradually, ensuring a new leader server is elected before taking down the old ones. If it works, I'll submit a PR to the Dkron Helm chart
