### ISSUE TITLE
Resouce Consideration

### ISSUE THREAD

**Issue by seanfulton** [distribworks/dkron#1560]
We have been using DKRON in 2 data centers/11 nodes for several years and it works great.
One issue we are having is with resource allocation. Some jobs are small but long-running; others are ginourmous and run for short periods of time.
I don't see anyway to allocation jobs based on resources (like marathon), or to send jobs to the least-busy node. 
Any idea how to do that?

**Comment by vcastellm** [comment]
This is a good question, resource based checks and scheduling is being considered for implementation, it's a matter of finding the most elegant implementation.

At this moment there's no such thing, but one workaround is to appropiately tag nodes to run different types of jobs. So for example tag `big` will accommodate big jobs while `small` tag can run small jobs, and so on and so forth.

That being said, I'm closing this issue but considering it as a support for this implementation.
