### ISSUE TITLE
Backup/Restore jobs

### ISSUE THREAD

**Issue by FallenRiteMonk** [distribworks/dkron#212]
Add the possibility to post multiple jobs (< job > array) at the same time.

Maybe also have a simple graphical way to backup all jobs (GET /jobs) and restore (POST /jobs) to and from a file.

**Comment by mridlen** [comment]
Backup is easy with curl.

Restoring I kludged together a quick script. Hope it is helpful to you.
restore_dkron_jobs.sh
`#!/bin/bash

LENGTH=$(jq length $1)
for (( i=0; i<$LENGTH; i++ ))
do
        echo "=== JOB $i ==="
        jq ".[$i]" $1
        jq ".[$i]" $1 > ./restore_dkron.tempfile
        curl -X POST "http://localhost:8080/v1/jobs" -H "accept: application/json" -H "Content-Type: application/json" -d @restore_dkron.tempfile
done`

**Comment by victorcoder** [comment]
Thanks @mridlen!

**Comment by pjz** [comment]
Slightly updated versions of the above can be found [here](https://gist.github.com/pjz/94f4bd81a0897fd64db44593078e2156).  Feel free to include or not; I needed them and am willing to share.

**Comment by victorcoder** [comment]
❤️  @pjz

**Comment by vision9527** [comment]
Can I provide a simple graphical way to backup all jobs and restore to and from a file. @victorcoder

**Comment by vision9527** [comment]
@victorcoder Hello, I have finished backend API of backup/restore jobs with file but I could't provide UI button because of my program skill. Can you help me?

**Comment by vision9527** [comment]
![image](https://user-images.githubusercontent.com/25179277/69915196-61130b80-1487-11ea-9c87-59a97897ce0a.png)
UI like this.

Export API
url: http://127.0.0.1:8080/v1/exportJobs
method: get
params: -
response: file

Import API
url: http://127.0.0.1:8080/v1/restoreJobs
method: post
params: file
response: string

**Comment by victorcoder** [comment]
Fixed in #727
