### ISSUE TITLE
Misleading information about task status

### ISSUE THREAD

**Issue by c0d34** [distribworks/dkron#379]
During a network partitioning between the servers, Dkron may report misleading information about task execution status.

For example in a deployment of 3 Dkron servers and 1 etcd server, if a network partition happened between the leader node and the other nodes (that is the communication is lost between them), and a task happened to be scheduled during this period of network partition, Dkron may report that the task has failed to execute on one of nodes, but in fact, it has been executed successfully on that node.

Would you please verify this behavior. note that it does not alway happen but often.

Thanks,

**Comment by victorcoder** [comment]
Was the task targeted to all 3 nodes? did the other nodes succeed?

**Comment by c0d34** [comment]
Actually, I was mistaken in my description.
The network partition is isolating the leader from all nodes not just one of them except for the etcd.

and for your questions, yes.
I tried to execute this task
```
curl -n -X POST 127.0.0.1:8080/v1/jobs \
  -H "Content-Type: application/json" \
 \
  -d '{
  "name": "cron_job2",
  "schedule": "@every 120m",
  "command": "echo `date` > /tmp/test.txt",
  "disabled": false,
  "shell": true,
  "tags": {
    "role": "web:3"
  }
}'
```

The status of the cluster
![](https://i.imgur.com/kYOmJhc.png)

The Job status (node 3 shows that it has failed to execute the task, but the file is created successfully on it. No information about other nodes)
![](https://i.imgur.com/zcgkTxr.png)

**Comment by victorcoder** [comment]
Actually the default success status is false when the job has no finished execution. Maybe it's a UI problem, it should say pending.

**Comment by victorcoder** [comment]
Done
