### ISSUE TITLE
Exponential Retries

### ISSUE THREAD

**Issue by prem2204** [distribworks/dkron#414]
Hi, This is not actually an issue. But I would like to explore on the possibilities of introducing the feature of configuring retries for a job (as like in some other distributed scheduling systems)
something like ..
"retries": {30, 60, 90, FAIL}
This can help in adding intelligence to our scheduled jobs which can have a delay (as configured or set in the request) before retrying on FAILURE(s)
At times certain scheduled API invocation might fail due to network issue or 500 error code
The API host might however get back to service after a while which the job will never come to know until next scheduling (which could be well after 24 hours)

I wish to explore myself on the above but wish to know if there's any similar development already lined up to be released in future.

**Comment by prem2204** [comment]
In the e.g. : _**"retries": {30, 60, 90, FAIL},**_

I meant, 1st retry : after 30 secs of first failure
2nd : after 60 secs of first failure
3rd: after 90 secs of first failure

**Comment by victorcoder** [comment]
There is no plan for this but I find it interesting, labeling as an enhancement.

**Comment by vcastellm** [comment]
Implemented in v4
