### ISSUE TITLE
github.com/victorcoder/dkron/plugin package could pull in less dependencies

### ISSUE THREAD

**Issue by jameshiew** [distribworks/dkron#435]
Currently the `github.com/victorcoder/dkron/plugin` uses some types and functions from the `github.com/victorcoder/dkron/dkron` package. The `github.com/victorcoder/dkron/dkron` package has many dependencies on big packages like Serf and Etcd which means the dependency graph for any package using `github.com/victorcoder/dkron/plugin` is extremely big. It would be useful if the subset of the `github.com/victorcoder/dkron/dkron` package which is depended on by `github.com/victorcoder/dkron/plugin` was separated out into its own package (maybe `github.com/victorcoder/dkron/types`?)

**Comment by victorcoder** [comment]
Sure this is something to improve, thanks for pointing it.

**Comment by victorcoder** [comment]
done
