### ISSUE TITLE
error count is 0,but there exists wrong execution

### ISSUE THREAD

**Issue by cpu6660** [distribworks/dkron#480]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
error count is 0,but there exists wrong execution 

## Actual Behavior
**special tips**： The task was executed quickly，you can imagine command `echo 'hello,world'`

**error log** :   time="2019-01-09T18:02:50Z" level=error msg="**store: Error trying to delete overflowed execution" error="Key not found in store"** execution=1547056727553940746-40b6959e84cd node=feaabeeb964f

![image](https://user-images.githubusercontent.com/13901890/50914096-c70e3300-1470-11e9-92f0-6a3b8c69ad45.png)

![image](https://user-images.githubusercontent.com/13901890/50914139-dee5b700-1470-11e9-90da-224a061fbb84.png)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:  1.0.0 
  - Platform: mac 
  - Backend store: etcd

**Comment by cpu6660** [comment]
@victorcoder help,ths

**Comment by genepix** [comment]
@cpu6660 jobs that aren't completed yet have a success state to "false".

**Comment by victorcoder** [comment]
@cpu6660 as @genepix states, if the job is not finished the success state is `false`, so to be failed should have `finished_at && success == false`

**Comment by cobolbaby** [comment]
Dear @victorcoder , 

Aiming at this problem, I just wonder what the cause of the pending state is. There is nothing unusual in the debug log. It always appear from time to time.

![2019-04-19 14-28-22屏幕截图](https://user-images.githubusercontent.com/11460848/56410385-83b53300-62af-11e9-9d4a-4b31b469e0a7.png)

**Comment by cobolbaby** [comment]
How can I find the root cause for the problem?

**Comment by victorcoder** [comment]
Are you still using v1? Could you check with latest version?

**Comment by cobolbaby** [comment]
@victorcoder  Has this issue been fixed in the new version?

**Comment by victorcoder** [comment]
Yes @cobolbaby
