### ISSUE TITLE
feature: streamable output

### ISSUE THREAD

**Issue by fopina** [distribworks/dkron#493]
It'd be really nice to have "streamable output" in the UI/API for the jobs instead of only getting the output in the end.
I was considering trying to make a PR but I got quite lost in the effort to accomplish this as, due to this being a plugin system, a lot of changes would be required just to be able to get pieces of information out of an execution without it being done...

Any hints/workarounds on how I could accomplish this?

**Comment by victorcoder** [comment]
Agree, it will be a nice feature @fopina, as you say, it could be a bit more complex to implement due to the usage of plugins but doable anyway.

I will start investigating on gRPC streaming or just capture the stdout of the plugins and refactor them to progressively send the output to the agent.

**Comment by fopina** [comment]
Awesome. I’m new to go and even newer (if possible) to this plugin structure but do let me know if I can help in some way

**Comment by fopina** [comment]
@victorcoder how would you store the streamed output? same as now (and keep updating that value on every stream update)?
It'd probably make sense to refactor the UI into opening a new window (with auto-refresh) for the output instead of that modal (with pre-loaded content), right?

Asking in case I decide to give it a go myself :)

**Comment by victorcoder** [comment]
@fopina yes, that makes sense!

**Comment by fopina** [comment]
In the meantime would you take a PR to change shell executor printing output at end of command to print as it goes?
That’d allow for the stderr/stdout to serve as an alternative, as currently there’s no way at all to know current output of a running job

**Comment by victorcoder** [comment]
Sure, makes sense

**Comment by fopina** [comment]
I was starting the change yesterday but realized that printing output as it goes will get mixed in stdout with the rest of dkron output. Before it was all together which still looked weird but with this changes it’s random lines in the middle without any info of where that output came from... any suggestions?

**Comment by victorcoder** [comment]
@fopina I have a plan for this, we can discuss it by mail.

**Comment by fopina** [comment]
reached out to the email in your commit history

**Comment by l-we** [comment]
Is there any progress?

**Comment by victorcoder** [comment]
Done in #719 #716
