### ISSUE TITLE
Expose metrics in prometheus format

### ISSUE THREAD

**Issue by sc0rp10** [distribworks/dkron#494]
Hi! I am using dkron for many tasks in my cluster - this is a great, simple and powerful software, thanks for it!
I have couple of feature requests that can be useful for another users.

It would be nice, if Dkron will expose metrics in prometheus format by some url like `/metrics` for advanced analytics/alerting/vizualizing jobs and their statuses.
I know about statsd + statsd_exporter, but IMO now prometheus is a industry standard and will be great if we can combine together dkron and prometheus without any another software.

**Comment by victorcoder** [comment]
Hi @sc0rp10, thanks for the proposal, I was thinking in improving the metrics method in Dkron and I have Prometheus on top of the list.

Expect some changes in the near future.

**Comment by victorcoder** [comment]
Done in #740
