### ISSUE TITLE
Dkron schedules not firing 10% of the time with DynamoDB

### ISSUE THREAD

**Issue by nnarendravijay** [distribworks/dkron#512]
## Expected Behavior
Schedules firing consistently 100% of the time.

## Actual Behavior
Schedules firing only 90% of the time.

## Steps to Reproduce the Problem

  1. Create a job with a schedule, say 0 0 15 * * TUE
  2. Observe with DynamoDB as the backend if the schedules fire consistently.
  3. If required, provision a hundred jobs with different schedules to see if it is a load issue.

## Specifications

  - Version: https://github.kdc.capitalone.com/CloudDetour2/dkron/commit/90edc5d647e6463e7f5d4f199e8ae358966aef2a
  - Platform: Linux
  - Backend store: DynamoDB

**Comment by victorcoder** [comment]
There could be several reasons why you are experiencing this, it is weird though.

Are you using the official dynamodb backend code or a custom one?

What the metrics of dynamodb indicates? Are they being throttled? Are you using provisioned or on demand capacity?

**Comment by fopina** [comment]
If the schedules don't actual `fire`, it's not the same issue, but just to check I also have an issue (using etcd) where jobs are scheduled at the right time (`Sending query` in the log) but then no worker picks it up. It happens rarely and haven't been able to reproduce it, so I haven't opened an issue.
Just to check if it's the same :)
