### ISSUE TITLE
TimeZones are not working on windows

### ISSUE THREAD

**Issue by Kunze** [distribworks/dkron#525]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
A task should be created.

## Actual Behavior
The server returns 422 (Unprocessable entity)

## Steps to Reproduce the Problem
curl --request POST \
  --url http://localhost:8080/v1/jobs \
  --header 'content-type: application/json' \
  --data '{
    "name": "name",
    "executor": "http",
    "timezone": "Europe/Berlin",
    "executorConfig": {
        "method": "POST",
        "url": "httpxxxxxx/email"},
    "schedule": "@at 2019-04-29T23:46:49Z"
}'

It works if I remove "timezone"

## Specifications

  - Version: 1.2.2
  - Platform: windows
  - Backend store: boltdb

**Comment by victorcoder** [comment]
Hi @Kunze, `executorConfig` should be `executor_config` let me know if that works

**Comment by Kunze** [comment]
Hi @victorcoder , it's still not working, the result is 422 (unprocessable entity). It does not work even if I use the example at https://dkron.io/basics/getting-started/
But it works when I remove the timezone.

**Comment by victorcoder** [comment]
@Kunze, weird it works in my tests, are you using the windows binary or the docker image?

**Comment by Kunze** [comment]
Hi @victorcoder , I am using windows binary.

**Comment by victorcoder** [comment]
I'm afraid windows is affected by https://github.com/golang/go/issues/21881

**Comment by ihershkovitz** [comment]
We have tried to use the latest version of dkron on windows and it seems that this issue hasn't fixed yet.
trying to set TimeZone for a job on windows and getting an error for bad request

**Comment by vcastellm** [comment]
In case of windows is probably better to use Docker to run Dkron, Windows is actually not supported, build is offered as is.
