### ISSUE TITLE
Dkron ran all jobs with recurring schedule twice

### ISSUE THREAD

**Issue by yvanoers** [distribworks/dkron#541]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
Jobs scheduled daily with a certain time or description (@midnight), and tagged as 'global:1' run once a day.

## Actual Behavior

On June 6th, for some reason, dkron started all jobs (59 in total) that are scheduled between @midnight and approx. 2:00AM (we have a job at 0:02, 0:04, 0:06, and so on) twice on the scheduled time.
The jobs running on an "@at" defined schedule around that time were run only once.

Some jobs ran twice on the same server, some ran on different servers.

The schedules for these jobs have been in there for weeks to months, and never have we noticed this before. Last night (day after occurrence) everything ran just once, as expected.

All jobs are tagged as global:1.
All jobs have concurrency: allow (all jobs and schedules are designed to run sequentially, and we never actively set this value: it has remained set to default).

Log excerpt attached:
[dkron-job-ran-twice.txt](https://github.com/victorcoder/dkron/files/3265562/dkron-job-ran-twice.txt)

## Steps to Reproduce the Problem

Wish I knew.

## Specifications

  - Version: 1.2.2
  - Platform: Linux/Debian 9 (no containers)
  - Backend store: etcd 3.2.18

**Comment by yvanoers** [comment]
My first suspicion was that ntpd and time slew might be the cause, but that was invalidated when I discovered not just the ones at midnight but during the following hours also ran twice. The server has been running ntpd for a long time now, and time drift wouldn't be that much that time slew would carry on for so long.

I've been going over the code to get a clue of what might have caused this behavior, but no luck so far.

**Comment by victorcoder** [comment]
Hi @yvanoers, how is etcd performing? seems like a split brain problem, where some dkron instances are connected to different stores and having two or more dkron leaders. Could this be the issue?

**Comment by yvanoers** [comment]
Hi @victorcoder, our dkron setup has 3 dkron servers and 2 etcd servers. Dkron01 and 03 talk to etcd1, dkron02 talks to etcd2.
Etcd1 is indeed complaining that it is is "probably overloaded". We are investigating this, but I'm guessing that this is caused by etcd being backed by HDD instead of SSD.

But the setup has been running for a while, and I would expect the incident to happen more often.

What I did uncover by going through the logs is that:
At 23:27, leadership switched from Dkron01 to Dkron03. I don't know why.
Jobs that ran twice often ran on Dkron01 and Dkron03, but also a few times twice on Dkron01 and a few times twice on Dkron03.
At 00:44, leadership was reacquired by Dkron01, and everything went back to normal.
Because some jobs ran twice on the <i>same</i> server (the leader even), wouldn't that disqualify a split brain problem?

**Comment by victorcoder** [comment]
Hi @yvanoers, do you have metrics on expvars for the cluster? would be useful to wath to the `scheduler_running` var at the time, that would indicate if the scheduler was running in more that one server at the same time.

**Comment by yvanoers** [comment]
Hi @victorcoder, sadly, no we don't have expvar metrics.

**Comment by yvanoers** [comment]
I'm chalking this up to an etcd box complaining about missing deadlines. That must first be resolved on our end and then happen again, before going any further.
