### ISSUE TITLE
Feature request: Job "display" name

### ISSUE THREAD

**Issue by knightsg** [distribworks/dkron#554]
First of all, thanks for developing this. We were looking for something simple but robust to handle our scheduled jobs and Dkron fits the bill perfectly.

One suggestion/idea we've had after the relatively short amount of time we've been using it is that it would be nice if we could specify an alternative display name/label for jobs that will be shown in the UI job list. I realise that the actual job name requires a specific format for use in the k/v store but it would be useful if there was another field you could use to set a more readable name that the UI would display if it was present.

**Comment by victorcoder** [comment]
Thanks @knightsg, TBH this will not be a priority right now but I gladly accept a PR implementing it.

Idea: Use the new metadata property in v2 to display a new column if it has the `name` metadata field.

**Comment by victorcoder** [comment]
Implemented in #568
