### ISSUE TITLE
v2.0.0-b4 add task failed

### ISSUE THREAD

**Issue by liumingc** [distribworks/dkron#569]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
add task should succeed.
curl localhost:8080/v1/jobs -XPOST -d '{
  "name": "job1",
  "schedule": "@every 10s",
  "timezone": "Europe/Berlin",
  "owner": "Platform Team",
  "owner_email": "platform@example.com",
  "disabled": false,
  "tags": {
    "server": "true"
  },
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "date"
  }
}' 

## Actual Behavior
when create job by curl, response with `422 Unprocessable Entity`
, and the error shows:
```
ERRO[2019-07-10T16:15:55+08:00] grpc: error dialing.                          error="context deadline exceeded" method=CallSetJob node=InfLiu-book-pro.local server_addr=
```

## Steps to Reproduce the Problem

  1. download dkron_2.0.0-b4_darwin_amd64.tar.gz, untar it, run it,
 2. run the create job example in tutorial

## Specifications

  - Version: 2.0.0-b4
  - Platform: Darwin
  - Backend store: etcd

**Comment by victorcoder** [comment]
@liumingc start using `dkron agent --server --bootstrap-expect=1`

**Comment by victorcoder** [comment]
Reopen if necessary
