### ISSUE TITLE
Feature Request: Execute a job on a specific year

### ISSUE THREAD

**Issue by kevin-wong-lifesite** [distribworks/dkron#570]
I am trying to execute a single job several years in the future to notify me when something expires, as in the case of a passport, or credit card. Are there any plans to add functionality to specify the year when the job should fire such as in a quartz format?

**Comment by yvanoers** [comment]
Hi @kevin-wong-lifesite ,
Are you trying to schedule a single occurrence (as opposed to a recurring job every couple of years)? That is already possible using an [`@at` schedule](https://dkron.io/usage/cron-spec/#fixed-times).

**Comment by kevin-wong-lifesite** [comment]
Yes perfect. Thank you
