### ISSUE TITLE
`retries` is not respected (v1.2.5)

### ISSUE THREAD

**Issue by thavlik** [distribworks/dkron#581]
## Expected Behavior
A job running every second with `"retries": 5` should cease executing after five failed attempts

## Actual Behavior
The job continues retrying forever

Here is the job JSON from the dashboard:
```
{
  "name": "2257422d-1317-4bb7-b38d-b977f97e4526",
  "timezone": "",
  "schedule": "@every 1000ms",
  "owner": "me",
  "owner_email": "",
  "success_count": 0,
  "error_count": 246,
  "last_success": "0001-01-01T00:00:00Z",
  "last_error": "2019-08-07T15:21:45.1889373Z",
  "disabled": false,
  "tags": null,
  "retries": 5,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": {
    "log": {
      "forward": true,
      "reporting_node": "3e7fc8979f48"
    }
  },
  "concurrency": "allow",
  "executor": "http",
  "executor_config": {
    "body": "2257422d-1317-4bb7-b38d-b977f97e4526",
    "debug": "true",
    "expectBody": "",
    "expectCode": "200",
    "method": "POST",
    "timeout": "15",
    "url": "http://localhost:6075/check"
  },
  "status": "failed",
  "next": "2019-08-07T15:21:46Z"
}
```

## Steps to Reproduce the Problem

  1. Create a job with a scheduled repeat and limited number of retries
  2. Witness the job never stop due to failure

The job URL is a local port that is not open. Perhaps this behavior is due to the error condition, which is ECONNREFUSED, and is interpreted (against my expectation) as an error that does not count against the retries. This sort functionality would actually be handy to configure, as it would provide a guarantee against retry failures due to temporary network outages.

## Specifications

  - Version: v1.2.5
  - Platform: Docker (`FROM dkron/dkron:v1.2.5`)
  - Backend store: presumably BoltDB (whatever the default is w/ the official docker image)

Thanks! :)

**Comment by yvanoers** [comment]
Hi @thavlik , I've tried reproducing this with the exact job as you've provided. The job also fails due to a connection refused error (according to the log).
However, each execution has precisely 6 runs each (1 job run + 5 retries). Of course, this job keeps running continuously, because it is scheduled every second.

Are you seeing dkron _retrying_ indefinitely, or _executing_ indefinitely? Can you perhaps provide a screenshot showing your problem?

**Comment by victorcoder** [comment]
Closing because of lack of response
