### ISSUE TITLE
Job’s Next Execution time is not initialized after creation

### ISSUE THREAD

**Issue by omerl13** [distribworks/dkron#587]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
Job’s Next Execution time should be set to the time of the next execution

## Actual Behavior
The next execution time is set to 0001-01-01, until the first run

## Steps to Reproduce the Problem

  1. Create a new job, without specifying next execution time (expected to be calculated automatically)

## Specifications

  - Version: 1.2.5 and 2.0.0-beta9
  - Platform: CentOS 7
  - Backend store: default

**Comment by yvanoers** [comment]
@omerl13 Indeed.

@victorcoder In `job.go` on lines 219-220 (v2.x), it says
```
// This should be only called on the actual scheduler execution
n, err := j.GetNext()
```
But it doesn't say why. It seems easy enough to create a fix for this issue by using `GetNext()` during job creation, but I'm hesitant because of this warning. Could you provide some insight into the reasoning behind it?

**Comment by omerl13** [comment]
> @omerl13 Indeed.
> 
> @victorcoder In `job.go` on lines 219-220 (v2.x), it says
> 
> ```
> // This should be only called on the actual scheduler execution
> n, err := j.GetNext()
> ```
> 
> But it doesn't say why. It seems easy enough to create a fix for this issue by using `GetNext()` during job creation, but I'm hesitant because of this warning. Could you provide some insight into the reasoning behind it?

Since the `GetNext` method only checks for the next execution time, it seems reasonable to use it to calculate the first run time on creation.

But I think the actual location that should be modified is the [`SetJob` method of store.go](/distribworks/dkron/blob/master/dkron/store.go#L93). I think that the job shouldn't get the `next` param from the client, but calculate it using current time + schedule. That is a side issue affected by this one - When I tried to make the `Next Exec` time show the correct time, I found out that setting the `next` parameter in the job's json makes it appear correctly in the UI, But it does not run when approaching the `next` given time if it is different from the correct schedule diff.

So, when setting manually the `next` field, dkron shows this data as the next execution time, but ignores it and calculate the correct schedule, Which leads to the only reasonable solution - calculate it on job's creation.

**Comment by victorcoder** [comment]
@yvanoers the comment refers to a previous bug where the `GetNext()` was called on `GetJob`, and it was refreshing the next schedule on every page reload #546

Makes sense to add it at job creation too.

Feel free to open a PR.

Thanks

**Comment by victorcoder** [comment]
Fixed in https://github.com/distribworks/dkron/commit/08f62f04666aee2ec88c33e60ef7409f4a5bdacd
