### ISSUE TITLE
Job’s next_execution time is not updated on schedule change

### ISSUE THREAD

**Issue by omerl13** [distribworks/dkron#590]
Similar to #587 but on job update. 

When changing job’s schedule, the next execution time remains as before, even though the job won’t run until new scheduled time. 

Checked on 2.0.0-rc1

**Comment by yvanoers** [comment]
@omerl13 This got fixed in 48c3a41 yesterday.
Nevertheless thanks for reporting it!

**Comment by victorcoder** [comment]
Expect a release soon. Closing in the meantime. Thanks!
