### ISSUE TITLE
Can not update job due to last_success precision

### ISSUE THREAD

**Issue by omerl13** [distribworks/dkron#591]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Description
Updating an existing job with ‘last_success’ field in it, cause a failure, with the following error:
“json: cannot unmarshal string into Go struct field Job.last_success of type ntime.NullableTime”

Last success is shown as “2019-08-26T05:55:58.004800877Z” in the UI. 

Removing this field before updating the job prevent from failing. 

## Steps to Reproduce the Problem

  1. Create a new job 
  1. Wait for it to run at least one time (or manually run it)
  1. Try to update the job via the UI

## Specifications

  - Version: 2.0.0-rc1
  - Platform: CentOS
  - Backend store: Default

**Comment by victorcoder** [comment]
Fixed in https://github.com/distribworks/dkron/pull/589

Expect a new release soon
