### ISSUE TITLE
Backend store for dkron v2.0.0-rc1

### ISSUE THREAD

**Issue by Demonian** [distribworks/dkron#593]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

Is there still ability to configure external storage in `dkron v2.0.0-rc1` instead of embedded one, It looks like `backend` and `backend-machine` settings are ignored. This feature is needed to be able to store all jobs if dkron pods are restarting, I think it was available in previous versions.

## Expected Behavior
Ability to customize storage exists.

## Actual Behavior
Embedded storage is used even if it is overriden with config file.

## Steps to Reproduce the Problem

1. Set  custom `backend` (e.g. zk) and `backend-machine` configuration in `dkron.yaml` or through `Environment variables`.
2. Start agent with debug log level.
3. See that embedded storage is used.

## Specifications

  - Version: v2.0.0-rc1
  - Platform: k8s
  - Backend store:

**Comment by victorcoder** [comment]
@Demonian, no in v2.0 the only storage is internal. You can use `data-dir` parameter to configure the path of the data to a persistent volume mounted in your pods, and reuse the data when the pod restarts.

Also you would want to establish a backup strategy for the content or for the volume itself.

Hope it makes sense

**Comment by Demonian** [comment]
@victorcoder It is not fully make sense to me, because previously it was much more easy to configure storage. Default embedded storage is very cool feature, but I don't understand why we cannot still support configuration of other storages. It will make dkron much more user friendly.

**Comment by victorcoder** [comment]
I understand your concerns, but with v2 you don't need to configure anything for using the internal store (I won't call it embedded).

v2 is a quite different beast, v1 was stateless and v2 is stateful, you can read the motivation of this change in https://www.victorcastell.com/posts/dkron-2-0-preview/

You can forget about the need of maintaining another piece of software, you only need to worry to backup a directory, that, will simplify your setup.

Also v2 feels, way faster and snappier when working with it.

All of this renders in a more cleaner, easy to maintain and well supported code

Hope this arguments makes you reconsider your expectations from dkron.

**Comment by Demonian** [comment]
@victorcoder Thanks for additional comments, very appreciate this.
