### ISSUE TITLE
Name contains illegal character 'C'.

### ISSUE THREAD

**Issue by pMonfared** [distribworks/dkron#594]
## Expected Behavior
I choose Name like this : invoice-create-Code12345
and i got exception with this value: 
"Name contains illegal character 'C'."

this bug resolve when make name tolower()
but i need to use name case Sensitive

## Specifications

  - Version: 2.0.0-rc1
  - Platform:
  - Backend store: Docker

**Comment by victorcoder** [comment]
This is intended, job names can only be slugs for correct internal working: https://github.com/distribworks/dkron/blob/v2.x/dkron/api.go#L264

You can use the `displayname` property to specify an alternative display name.

You also can use the `metadata` property to set additional info on a job and use that info to query the API.

What's your use case?

**Comment by pMonfared** [comment]
@victorcoder how can to use metadata and GET
`​/jobs​/{job_name}` or `/jobs/{job_name}/toggle`?

how can I get jobDetail or toggle with Metadata?

i use uniqe code like that for every job ("S3f4B") and maybe generate same code like that ("s3f4B") different between jobs only is 'S' and 's'.

how can use like that?
"invoice-create-S3f4B"
"invoice-create-s3f4B"

you say can't use like that! i don't know handle this!

**Comment by yvanoers** [comment]
@pMonfared 
To search using the metadata property, you first post a job that has such metadata:
```
{
  ...
  metadata: { "code": "invoice-create-S3f4B" },
  ...
}
```
Now you can query that job using `http://dkron-hostname:8080/v1/jobs?metadata[code]=invoice-create-S3f4B`. This match is case sensitive, so this will allow you to retrieve the appropriate job after putting it in dkron.

What is left is the need for a unique `name` property that is all lower-case.
Converting the characters in your text code to their byte codes in hex in lower case could be a solution to this. E.g.:
S3f4B &rarr; 5333663442
s3f4B &rarr; 7333663442
(too bad this particular example doesn't have any hex a-f in it)

If you use this trick or something similar to compute the job name, you may not even need the metadata search to find the job you're looking for.

<br>
Note: Dkron v1 did accept names with upper case, but it would convert everything to lower case and strip unusable characters out. Hence, Dkron v1 would treat "invoice-create-S3f4B" and "invoice-create-s3f4B" as the same job, whereas Dkron v2 rejects invalid names, preventing unintended overwrites.

**Comment by yvanoers** [comment]
Hi @pMonfared, seeing your tumbs up response, I'm assuming your issue is resolved.
In that case, would you mind closing this issue?

Thanks!

**Comment by victorcoder** [comment]
Assuming resolved, thanks @yvanoers
