### ISSUE TITLE
Custom TLS certificates for HTTP executor

### ISSUE THREAD

**Issue by Demonian** [distribworks/dkron#596]
Is there ability to make add custom certificate to `http-executor` or at least disable TLS verification? Is there a plan to make this possible in future?

## Expected Behavior
Successful call to services that are secured with custom TLS certificates from `http-executor`

## Actual Behavior
Call fails with TLS errors.

## Steps to Reproduce the Problem

  1. Create `http executor` Job with call to service secured with custom TLS certificated
  2. Trigger the Job.

## Specifications

  - Version: v2.0.0-rc1
  - Platform: k8s
  - Backend store: embedded

**Comment by yvanoers** [comment]
@Demonian As far as I can tell, the http-executor has no TLS configuration options.

The recommended way to go about, though, this is to add the CA of your self-signed certificate to the trusted Root CAs of the systems running Dkron.

Whether any TLS configuration options might get included I'll leave for @victorcoder to answer.

**Comment by victorcoder** [comment]
@Demonian IMO an option to ignore untrusted certificates could be added, will be disabled by default and enabled on users demand.

**Comment by victorcoder** [comment]
Fixed in #603
