### ISSUE TITLE
Can not run using pm2

### ISSUE THREAD

**Issue by omerl13** [distribworks/dkron#599]
I am trying to run dkron using pm2. 

Until v2 of dkron, the process ran successfully, but in the current version (2.0.0 rc3), the following error is thrown: “dkron: error initializing store” “manifest has unsupported version: 4 (we support 7)”

**Comment by yvanoers** [comment]
@omerl13 V2.x was recently upgraded to a newer rc version of BadgerDB. Judging from the error message, the newer version is not able to read stores created with the previous version that came in Dkron.
Have you upgraded an existing dkron v2.x version to 2.0.0-rc3?
If so, removing the old store should resolve the issue.

**Comment by victorcoder** [comment]
Right @yvanoers, latest BadgerDB doesn't support manifests < 7, @omerl13 just remove the directory with the node name under `dkron.data` dir, don't remove the `raft` subdirectory, that's the important one. You should end up with everything as before the upgrade.

**Comment by omerl13** [comment]
> Right @yvanoers, latest BadgerDB doesn't support manifests < 7, @omerl13 just remove the directory with the node name under `dkron.data` dir, don't remove the `raft` subdirectory, that's the important one. You should end up with everything as before the upgrade.

Seems like it solved the issue, Thanks!
