### ISSUE TITLE
I can not run an agent with a volume with previous data

### ISSUE THREAD

**Issue by mgleria** [distribworks/dkron#609]
Since the changes regarding backend storage on v2.0, I was doing some tests to ensure fault tolerance on my deployments. I was not capable to accomplish the simplest test: launch a new container, create some jobs, kill the container (docker rm) and create a new one binding the same volume to restore the previous data. 

## Expected Behavior
After running an agent with the following command:
```
docker run  -p 8080:8080 -d \
--log-opt mode=non-blocking --log-opt max-buffer-size=50m \
--name dkron \
-v <localPath>:/dkron.data \
registry.gitlab.com/distribworks/dkron-pro:v2.0.0-rc6 \
agent --server --data-dir=/dkron.data --bootstrap-expect=1
```

I expect that If I kill that container and create a new one with the same command, all the data created in the first container be correctly restored. 

## Actual Behavior
When I run an agent linked to a volume with previous execution data, I can not see my previous jobs and I can not create any more jobs. If I look at Dkron generated logs, I see repeatedly errors like this:
```
time="2019-10-17T19:55:46Z" level=error msg="dkron: failed to wait for barrier" error="leadership lost while committing log" node=27082cda3adf
time="2019-10-17T19:55:46Z" level=info msg="dkron: cluster leadership lost" node=27082cda3adf
time="2019-10-17T19:55:46Z" level=info msg="dkron: monitoring leadership" node=27082cda3adf
time="2019-10-17T19:55:47Z" level=info msg="dkron: cluster leadership acquired" node=27082cda3adf
time="2019-10-17T19:55:47Z" level=info msg="dkron: monitoring leadership" node=27082cda3adf
time="2019-10-17T19:55:47Z" level=error msg="dkron: failed to wait for barrier" error="node is not the leader" node=27082cda3adf
time="2019-10-17T19:55:47Z" level=info msg="dkron: cluster leadership lost" node=27082cda3adf
time="2019-10-17T19:55:47Z" level=info msg="dkron: monitoring leadership" node=27082cda3adf
time="2019-10-17T19:55:49Z" level=info msg="dkron: cluster leadership acquired" node=27082cda3adf
time="2019-10-17T19:55:49Z" level=info msg="dkron: monitoring leadership" node=27082cda3adf
```

## Steps to Reproduce the Problem

1. Launch a new agent on Docker with the command mentioned above. Make sure to generate a folder for persistence and put the path in the <localPath> on the docker run command.
1. Open the browser on the exposed port (8080) and create some jobs and run them if you want.
1. Observe that you have data on the folder created on your host to validate that the volume binding is working. 
1. Kill the container running `docker stop dkron && docker rm dkron`
1. Run a new container with the same command used on 1. 
1. Observe the logs with `docker logs  -f dkron` and try to create new jobs on the browser (or by API)

## Specifications

  - Version: dkron-pro:v2.0.0-rc6
  - Platform: Docker on Ubuntu 18.04
  - Backend store: -

**Comment by yvanoers** [comment]
@mgleria just FYI: we'll be looking into this.

**Comment by mgleria** [comment]
I found a workaround thanks to [this post](https://gitmemory.com/issue/distribworks/dkron/572/511740718). If I add to my run command the _--hostname_ option, I'm able to recover the data from the previously killed container and works fine.

**Comment by victorcoder** [comment]
Hi @mgleria, sorry for the late response.

Yes, this is because the node-name -that should be unique in a cluster- is used to identify a node in the internal Raft protocol, by default the node-name is the hostname of the machine running Dkron.

Docker will create a new hostname on each container start, so from the Raft PoV the machine trying to load the Raft log is a new cluster member and won't try to load the previous log entries.

This is why it's convenient to use the `node-name` parameter when using dkron with docker.

For example: `docker run --rm -p 8080:8080 --name dkron -v `pwd`/dkron.data:/dkron.data dkron/dkron agent --server --bootstrap-expect=1 --data-dir=/dkron.data --node-name foo`

Note that it's also important to tell dkron the correct data path using the `data-dir` directory.
