### ISSUE TITLE
Is this software capable of handling tens of thousands of crons? how much cpu and ram does it need?

### ISSUE THREAD

**Issue by hosnas** [distribworks/dkron#610]
Hello,

Sorry if I'm asking this question in the wrong place.

Is this software capable of handling tens of thousands of crons? how much cpu and ram does it need?

my usecase is to handle scheduled jobs like push notification, email automation and these kind of things for my customers.

**Comment by victorcoder** [comment]
First, be sure to think if you can be better served by using a Job queue system or a background job processing system.

> Is this software capable of handling tens of thousands of crons?

It depends, specially on periodicity, it's not the same to execute a few every second than a thousands.

**Comment by hosnas** [comment]
@victorcoder Thank you very much for your response. I'm searching the web for almost one week and couldn't find exactly what I want. what I exactly want is to a system to call a **url** with **queries** and **payload** at a given time (one time or periodically). If you can guide me to a better opensource solution, it would be awesome. And I prefer it to have a rest api to schedule job. 

> It depends, specially on periodicity, it's not the same to execute a few every second than thousands. It should work in the first case. And you can face scalability problems in terms of network in the second.

I have 100k active users and I want to have a cron that runs once per hour for each. so it would be near 30 jobs per seconds

**Comment by victorcoder** [comment]
I don't know of an opensource one with those characteristics that it's similar to Dkron, there is http://contribsys.com/faktory/ but you need development of the workers (should be easy), but if you need cron jobs you need to go for the paid version. Also think in the offers of the cloud providers like AWS or GCP, Azure, etc. They have scheduled job solutions but can be expensive for that amount of work.

Another option with contained costs, if you don't need HA guarantees, you can have several Dkron instances on single node mode, that should do the trick.
