### ISSUE TITLE
"--webhook-header" CLI option is ignored

### ISSUE THREAD

**Issue by davidgengenbach** [distribworks/dkron#619]
**Describe the bug**
When using the `--webhook-header` CLI option in v2, it gets ignored.

**To Reproduce**
1. Start Dkron with `--webhook-header 'Content-Type: application/json' --webhook-url ...`
1. Create a job and (manually) run it at least once
1. Look at the headers which are sent to the webhook

```shell
agent \
  --server \
  --log-level=debug \
  --bootstrap-expect=1 \
  --webhook-header 'Content-Type: application/json' \
  --webhook-url https://end8f6r18y357.x.pipedream.net/ \
  --webhook-payload '{"jobName":  "{{.JobName}}", "success": {{.Success}}, "finished_at": "{{.FinishedAt}}"}'
``` 
(https://requestbin.com/r/end8f6r18y357/1StjJ4FPGMQRDF1g30iQYv0WVjt)

**Expected behavior**
The CLI option should result in the header to be sent alongside the request.

**Screenshots**
![Screenshot_2019-10-30_00:01:46](https://user-images.githubusercontent.com/2621491/67815886-7d96df00-faa8-11e9-8b20-498bfd8098ad.png)

**Specifications:**
 - OS: Linux david 5.3.7-200.fc30.x86_64 #1 SMP Fri Oct 18 20:13:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Version: Dkron 2.0.0-rc7

**Additional context**
I think this is due to a typo in [config.go](https://github.com/distribworks/dkron/blob/5d540687d7bf8ebb66a7d55773c9adec75d08929/dkron/config.go#L144):

```WebhookHeaders []string `mapstructure:"webhook-headers"```

and in the CLI option definitions: 

```cmdFlags.StringSlice("webhook-header", []string{}, "Headers to use when calling the webhook URL. Can be specified multiple times")```

(it says `webhook-headers` instead of `webhook-header`) 

I am not that familiar with the code so this is just a hunch...

Apart from that: thanks for the software :+1: Your efforts are greatly appreciated - especially the  (nearly undocumented?) Webhook functionality is nice!

**Comment by davidgengenbach** [comment]
Update: using the `dkron.yml` configuration option `webhook-headers` works just fine.

**Comment by victorcoder** [comment]
Thanks for reporting @davidgengenbach, good catch! Indeed was a kind of typo/legacy code removed.

Fix incoming

**Comment by marsonmao** [comment]
Hi, could you please state where you put the dkron.yml? I'm not sure if the file should be at root folder. @davidgengenbach

**Comment by davidgengenbach** [comment]
> Hi, could you please state where you put the dkron.yml? I'm not sure if the file should be at root folder. @davidgengenbach

https://dkron.io/basics/configuration/

**Comment by victorcoder** [comment]
@marsonmao Look at https://github.com/distribworks/dkron/blob/master/cmd/dkron.go#L48-L50 

Adding it to the docs

**Comment by marsonmao** [comment]
@victorcoder fantastic, thanks!
By the way, is it better to add `viper.SetConfigType("yml")` here?
Although viper will try to match all supported extension name, but every doc in dkron states that the config file is **dkron.yml**.
