### ISSUE TITLE
"/jobs/{job_name}/executions" does not return `success` field for unsuccessful executions

### ISSUE THREAD

**Issue by davidgengenbach** [distribworks/dkron#620]
**Describe the bug**
When retrieving the executions of a Dkron job using the  `/jobs/{job_name}/executions` endpoint, the `success` field is only set when the execution is successful.

**To Reproduce**
1. Create a HTTP job with a non-existing URL 
1. Execute the job (it should fail!)
1. Go to  `/jobs/{job_name}/executions`

The `success` field is not defined.

**Expected behavior**
The `success` field should always be sent. 

**Specifications:**
 - OS: Linux david 5.3.7-200.fc30.x86_64 #1 SMP Fri Oct 18 20:13:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Version Dkron 2.0.0-rc7

**Comment by victorcoder** [comment]
Thanks for reporting, fix incoming
