### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by GauravRajSharma** [distribworks/dkron#625]
I am not sure what is happening. Hope someone can help me with this.
![Screen Shot 2019-11-14 at 12 27 44](https://user-images.githubusercontent.com/16515861/68833089-ba82e880-06da-11ea-9d30-509d51360e6b.png)

## How I got this!
1. I started `dkron agent --server --bootstrap-expect=1` as your docs specified for running a basic server.
2. I started pushing jobs to it, but `POST`ing to the `/v1/jobs/` endpoint. 
### I used this script for pushing JOBS.
![Screen Shot 2019-11-14 at 12 33 26](https://user-images.githubusercontent.com/16515861/68833178-f6b64900-06da-11ea-9c5f-baacb5550a4d.png)

Am I missing something?
Till now it has always SEGFAULTed on me. Sometimes, it takes more than 1000 (only, I need this for 15,000+ jobs) other times, under 200 task it SEGFAULTS.
I am not using any complex configuration. Just basic getting started.
Shouldn't it handle such low task amount with ease? Or I need complex configurations to do so?

**Comment by unique1o1** [comment]
I'm having the same exact problem, First i thought that the dkron server couldn't handle the request so, i used the docker compose file (provided) to launch mulitple server nodes but still the problem persists. And i'm seeing a lots of `restarting scheduler`, what's up with that?

**Comment by GauravRajSharma** [comment]
High Frequency of Tasks isn't being executed either.
Even though tasks which are scheduled later than these are being executed.
Is this system not consistent with high-frequency dynamic scheduling?

![Screen Shot 2019-11-14 at 14 40 45](https://user-images.githubusercontent.com/16515861/68841497-d3949500-06ec-11ea-8c87-3ea35335f775.png)
![Screen Shot 2019-11-14 at 14 40 48](https://user-images.githubusercontent.com/16515861/68841499-d4c5c200-06ec-11ea-9c25-ed5d338a4f45.png)

**Comment by yvanoers** [comment]
> And i'm seeing a lots of restarting scheduler, what's up with that?

@unique1o1 This is a side effect of having used an older version of cron. It will go away when #605 is fixed. FYI: Fixing that bug is a priority for us.

> High Frequency of Tasks isn't being executed either.

@GauravRajSharma This may also be related to #605, but the description is too brief for me to definitively conclude that. Could you have a look at #605 and see if that fits your scenario? If not, then please submit a new issue.

> Shouldn't it handle such low task amount with ease? Or I need complex configurations to do so?

@GauravRajSharma Yes, it should handle that load without issue, and no, any complex configuration should not be necessary.
I'd like to know the version of dkron you're using. I'm guessing latest RC, but just to be sure. If it's not RC7, please upgrade to that version first and see if it happens with that version as well, thanks.

**Comment by GauravRajSharma** [comment]
@yvanoers Thank you for your response.
Yes, I am using RC7.
Could you please elaborate on the Segmentation Fault Issue I mentioned above in my first issue.
Why does this segmentation fault occur?

I am mostly seeing this after updating the previous jobs. But even new jobs throw Segmentation Faults Occasionally. I am trying to isolate the issue but am unsuccessful.

The high-frequency task problem is similar to @unique1o1. Waiting for the fix, we really want to push into production. Thank you for your work!
I am confused about your response to @unique1o1, older version of cron?

**Comment by victorcoder** [comment]
@yvanoers thanks, you are right, the "scheduler restarted" issue is related to #605

@GauravRajSharma you can read about the "older version of cron" in #605

I did a quick test setting 5000 jobs with this script https://github.com/distribworks/dkron/blob/master/scripts/jobs.sh and I'm unable to reproduce the segmentation fault issue.

@GauravRajSharma @unique1o1 What's  the specs of your testing hardware, I've seen similar issues related to memory.

**Comment by yvanoers** [comment]
> Thank you for your work!

Kudoz go to @victorcoder here, he has done and does most of the work :1st_place_medal:

**Comment by GauravRajSharma** [comment]
@victorcoder Thank you for your response.
I am able to reproduce this Segmentation Fault in my MacBook Air 2017. I don't think it's a RAM issue as I am monitoring my RAM as well.

But the re-production isn't 100% as sometimes I cannot get to the segmentation fault and it works.
# Steps
1. Add a couple of tasks with very low execution times. Like under 15 seconds of creation.
2. Execute an update script for re-scheduling these same tasks, as they are executing.
Example:
if `task_1` is to be executed at 14:20:15 and if you try to re-schedule `task_1` at 14:20:15 to 14:20:20. This segmentation fault occurs mostly.

## Following python script is what I used to get these results.
![Screen Shot 2019-11-14 at 16 31 11](https://user-images.githubusercontent.com/16515861/68850466-2e81b880-06fc-11ea-8f49-4ca35f96a0ce.png)

## Segmentation Fault Error from Dkron logs
![Screen Shot 2019-11-14 at 16 32 08](https://user-images.githubusercontent.com/16515861/68850531-4f4a0e00-06fc-11ea-955f-30d69367ec02.png)

**Comment by victorcoder** [comment]
Thanks @GauravRajSharma nice starting point, we will investigate from here.

Could you please paste the script in text?

**Comment by GauravRajSharma** [comment]
@victorcoder 
```python
from datetime import datetime, timedelta
import time
import requests as req


def create_job(data):
    resp = req.post("http://localhost:8080/v1/jobs", json=data)
    print(resp.text)


for i in range(1500, 2000):
    c = datetime.now() + timedelta(seconds=15)
    # if i % 4 == 0:
    # time.sleep(0.7)
    data = {
        "name": f"w_{i}",
        "schedule": f"{c.second} {c.minute} {c.hour} {c.day} {c.month} *",
        "executor": "shell",
        "timezone": "Asia/Kathmandu",
        "executor_config": {"shell": "true", "command": "ls"},
    }


```

**Comment by victorcoder** [comment]
@GauravRajSharma I just released RC8, could you try it and check if it solves the issue?

**Comment by viperfx** [comment]
Just wanted to add to this, as I have been running DKRON alongside my current schedule to ensure it's robustness. 

I usually have supervisor to not allow for a restart after crash and every time I deploy (every week) I check on it, and it's usually crashed. Here is the trace:

```
time="2019-11-15T12:00:14Z" level=info msg="agent: Starting job" job=report_task_orqlyu node=ip-172-31-47-169
time="2019-11-15T12:00:14Z" level=info msg="agent: Received event" event="query: run:job" node=ip-172-31-47-169
time="2019-11-15T12:00:14Z" level=info msg="agent: Starting job" job=member_task_shmykv_6805 node=ip-172-31-47-169
time="2019-11-15T12:00:14Z" level=info msg="agent: Received event" event="query: run:job" node=ip-172-31-47-169
time="2019-11-15T12:00:14Z" level=info msg="agent: Starting job" job=member_task_shmykv_6804 node=ip-172-31-47-169
time="2019-11-15T12:00:14Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=ExecutionDone node=ip-172-31-47-169 server_addr="172.31.47.169:6868"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x86e732]

goroutine 9372846 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.19.1/clientconn.go:853 +0x42
github.com/distribworks/dkron/dkron.(*GRPCClient).ExecutionDone(0xc012ef5ae0, 0xc00a0c1ce0, 0x12, 0xc031412780, 0x2cec4c0, 0x45fae60)
        /dkron/dkron/grpc_client.go:71 +0x454
github.com/distribworks/dkron/dkron.(*Agent).invokeJob(0xc000146300, 0xc008f6cdc0, 0xc031412780, 0x0, 0x45b5200)
        /dkron/dkron/invoke.go:74 +0xc2b
github.com/distribworks/dkron/dkron.(*Agent).eventLoop.func1(0xc000146300, 0xc008f6cdc0, 0xc031412780)
        /dkron/dkron/agent.go:666 +0x5d
created by github.com/distribworks/dkron/dkron.(*Agent).eventLoop
        /dkron/dkron/agent.go:665 +0x1c86

```

**Comment by GauravRajSharma** [comment]
@victorcoder Thank you.
Yes, according to my tests, it seems like you have successfully solved the issue!
But,
Can DKRON handle a large number of JOBS executing at the same time?
Like 1500 jobs scheduled for 15:00:15? Can it reliably execute 1500 jobs?
While I was testing this, I found it crashed most of the time while executing a large volume of task
```python
from datetime import datetime, timedelta
import time
import requests as req


def create_job(data):
    resp = req.post("http://localhost:8080/v1/jobs", json=data)
    print(resp.text)


c = datetime.now() + timedelta(minutes=1)

for i in range(1500):
    data = {
        "name": f"e_{i}",
        "schedule": f"{c.second} {c.minute} {c.hour} {c.day} {c.month} *",
        "executor": "shell",
        "timezone": "Asia/Kathmandu",
        "executor_config": {"shell": "true", "command": "ls"},
    }
    create_job(data)
```
I scheduled 1500 tasks for execution at the same time. They scheduled perfectly but, while executing it produced this error:
![Screen Shot 2019-11-17 at 12 27 11](https://user-images.githubusercontent.com/16515861/69004122-f1086f80-0935-11ea-8420-f33d8cdfad9f.png)

**Comment by victorcoder** [comment]
@viperfx Could you open a new issue describing what are you experiencing? thanks

@GauravRajSharma Good to know that! Very good question, I don't have a clear answer on that, with the latest fixes speed and scalability got greatly improved precisely for use cases like yours and others, in theory running that amount of jobs at the same time should be possible but it will depend on several factors (networking and disk) and for sure will need some trade-offs.

The error you are seeing is coming from the Raft protocol, it was unable to process that amount of requests.

TBH In this case it will be difficult to scale to this workload. Dkron is designed to replace traditional crons in cloud native environments and ensuring no SOPOFs in your system, and it should handle 1500 and more without problem but not at the exact same time, your strategy should go towards distributing the executions in subsequent seconds or minutes.

Hope it makes sense.

**Comment by cobolbaby** [comment]
#257
