### ISSUE TITLE
Cannot Perform Debian/Ubuntu Installation

### ISSUE THREAD

**Issue by tonyamos** [distribworks/dkron#629]
**Describe the bug**
I followed the instructions for Debian installation found in [Installing the package](https://dkron.io/basics/installation/) so that I can install Dkron on Ubuntu 18.04. However Dkron cannot be found.

**To Reproduce**
1. Manually added the line "deb [trusted=yes] https://apt.fury.io/distribworks/ /" to the file /etc/apt/sources.list

2. run "sudo apt update", and got (omitted lines not related to Dkron):
...
Ign:6 https://apt.fury.io/distribworks  InRelease                                                                      
Ign:7 https://apt.fury.io/distribworks  Release                                               
...
Ign:10 https://apt.fury.io/distribworks  Packages                       
Ign:11 https://apt.fury.io/distribworks  Translation-en
Get:10 https://apt.fury.io/distribworks  Packages [14 B]
Ign:11 https://apt.fury.io/distribworks  Translation-en                   
Ign:11 https://apt.fury.io/distribworks  Translation-en
Ign:11 https://apt.fury.io/distribworks  Translation-en
Ign:11 https://apt.fury.io/distribworks  Translation-en
Ign:11 https://apt.fury.io/distribworks  Translation-en
Ign:11 https://apt.fury.io/distribworks  Translation-en
Fetched 14 B in 1s (14 B/s)                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

3. Run "sudo apt install dkron -y" and got:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dkron

** Specifications:**
 - OS: Ubuntu Linux
 - Version 18.04 Bionic

**Comment by victorcoder** [comment]
Sorry about this @tonyamos my bad, I replaced repository name but I was uploading the packages to the wrong location.

Should be fixed now

**Comment by tonyamos** [comment]
Thank you for the fast response. I'm up and running now.
