### ISSUE TITLE
Migration from v1 to v2.

### ISSUE THREAD

**Issue by agarwal-nitesh** [distribworks/dkron#632]
**Bug**
The Redis backend is not being picked by Dkron after migration to v2. It seems to be using /dkron.data to store info related to schedules.

**To Reproduce**
1. Update to Dkron v2 rc10
2. Migrate backed-up jobs to this new version using Dkron API-doc
3. Use /etc/dkron/dkron.yml file as mentioned in the doc to specify config.
```
backend: redis
backend-machine: redis-telephony.com:6379
```

**Expected behavior**
It should create keys in Redis as it used in v1.

** Specifications:**
 - OS: centos

**Additional context**
The documentation for v2 is also confusing. It says JSON file yet the example is a YAML file.
But it seems to be using the YAML file anyways as the Slack notifications are still working.

**Comment by victorcoder** [comment]
Dkron v2 doesn't use external storage anymore. Please refer the [upgrade guide](https://dkron.io/upgrading/from_v1_to_v2/) for help in how the storage works in v2.

Can you link me where it says JSON for configuration? thanks
