### ISSUE TITLE
Can I create new job by importing file like json file...?

### ISSUE THREAD

**Issue by vision9527** [distribworks/dkron#636]
Due to migrate my server, I need one way to let the jobs migrate to new server.I want to import file for solving this.There are other any ways?  Thanks.

**Comment by victorcoder** [comment]
You can reimport jobs using a bash script, this is a good start https://gist.github.com/pjz/94f4bd81a0897fd64db44593078e2156

Feel free to reopen if you have any doubt.

**Comment by vision9527** [comment]
> You can reimport jobs using a bash script, this is a good start https://gist.github.com/pjz/94f4bd81a0897fd64db44593078e2156
> 
> Feel free to reopen if you have any doubt.

I got it. Thank you. I wanna provide the feature that the jobs can be imported with json file by web UI. Can I?

**Comment by victorcoder** [comment]
@vision9527  PRs are welcome
