### ISSUE TITLE
HTTP jobs stop executing after some time

### ISSUE THREAD

**Issue by davidgengenbach** [distribworks/dkron#647]
**Describe the bug**
When using the Dkron v2 Docker image, we experience a complete failure of Dkron job execution after some time.
The HTTP jobs execute just fine for approx. one day and fail completely afterwards with no meaningful error message.

The HTTP jobs fail while producing this error message:
```
time="2019-11-27T21:20:00Z" level=info msg="agent: Sending query" job_name=5ddba51f22eb4c1854264022 node=dkron-scheduler-5d4b4f7886-grwn8 query="run:job"
time="2019-11-27T21:20:00Z" level=info msg="agent: Received event" event="query: run:job" node=dkron-scheduler-5d4b4f7886-grwn8
time="2019-11-27T21:20:00Z" level=error msg="invoke: command error output" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin185612057: connect: connection refused\"" job=5dde5a12e9aeb42714a1fdc0 node=dkron-scheduler-5d4b4f7886-grwn8 plugin="&{0xc0001543e8}"
```
The file `/tmp/plugin185612057` exists.

This is the used config:
```
    server: true
    log-level: info
    bootstrap-expect: 1
```
:pencil: We only use one server - the job data is actually persisted in another service. But this should not be due to there only being one server?

**To Reproduce**
1. Create a HTTP job to be executed all X minutes
2. Let the system run for approx. a day
3. Wait for the errors

**Expected behavior**
The jobs should execute after one day of running the system.

**Specifications:**
 - OS: Docker on Kubernetes
    - Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
    - Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
 - Dkron 2.0.0, Agent Protocol: 5 (Understands back to: 2)
   - using the `dkron/dkron:v2` Docker image

**Comment by victorcoder** [comment]
@davidgengenbach This is probably the http-executor process being killed, could you check if it's running in this state? `ps aux | grep dkron-http-executor` 

I was aware of some similar reports, and it was due to memory problems, how much memory does the container have?

**Comment by davidgengenbach** [comment]
@victorcoder It has `650Mi`. Unfortunately, I had to kill the container as it did not work anymore, so I can not look whether the process is running. I will increase the memory too `1000Mi` (which is **quite** a lot?) and look what happens!

But thousand thanks for the very fast answer :+1:

**Comment by davidgengenbach** [comment]
@victorcoder I am not sure whether this is helpful, but one of the last entries in the logs - before all jobs went haywire - were about compaction (= BadgerDB?).
Maybe during the compaction, there is a lot of additional memory needed? Unfortunately the logs of the failing container are deleted, so I can not get you the log lines...
Can I trigger the compaction manually somehow to test whether this is an issue?

**Comment by victorcoder** [comment]
Ok, memory will depend a lot on usage, more jobs more memory. Let's observe the memory usage now. Compaction shouldn't be a problem.

**Comment by davidgengenbach** [comment]
> Ok, memory will depend a lot on usage, more jobs more memory. Let's observe the memory usage now. Compaction shouldn't be a problem.

There were no new jobs created at the time (or within hours for that matter) of the failure. They were executing normally (maybe creating more execution-entries which result in more memory used?)

I am monitoring the memory usage now... and will report when something new happens.

**Comment by davidgengenbach** [comment]
I did not encounter the problem any more. I think it was a memory-related issue as you suggested! 

It might be interesting to have a health-check in Dkron which checks whether the plugins are running or whether their processes have been killed?

**Comment by victorcoder** [comment]
Dying plugins is a real danger, but currently there are more benefits of using them than not using them, but sure they need more checks in order to offer more confidence.
