### ISSUE TITLE
Concurrency Forbid being ignored (again) since upgrade to 2.0

### ISSUE THREAD

**Issue by geoffjukes** [distribworks/dkron#655]
Hi @victorcoder 

Since upgrading to 2.0 (currently 2.0.1) we have an issue where the `concurrency: forbid` is being ignored after running for some time.

![image](https://user-images.githubusercontent.com/1959570/70476157-fff0c680-1a8a-11ea-886c-002c9cb15783.png)

I'm not sure how to start debugging the issue.

**Comment by victorcoder** [comment]
Thanks for reporting @geoffjukes I will investigate.

**Comment by geoffjukes** [comment]
@victorcoder Were you able to identify an issue? or can I do anything to help debug?

For now I have disabled the affected jobs, and am firing them manually.

**Comment by victorcoder** [comment]
@geoffjukes yes, the feature was broken in https://github.com/distribworks/dkron/pull/630/files#diff-9719285e240fa82e7f8e90770c4df6f0L338 , It's fixed but I'm adding an integration test to ensure it doesn't happen again.

Release coming in the following hours.

**Comment by geoffjukes** [comment]
@victorcoder Awesome, glad I wasn't losing my mind :) Thanks for the prompt response.
