### ISSUE TITLE
Dkron UI allows empty job name

### ISSUE THREAD

**Issue by smiller393** [distribworks/dkron#656]
Version: 
2.0.1

Problem: 
User is able to create a new dkron job with the name being an empty string. After creating this job, it is not possible delete the job (returns a 404), and it is not possible to update the name. When attempting to create a new job with an empty name, the new job will simply override the old job without warning. Adding a display name will show a value on the jobs list, but clicking on that job display name results in a 404.

Expectation: 
Jobs with an empty string name should not be allowed

Steps to reproduce:

1. Create a basic job with the job name being an empty string and use a valid parent job. (no parent or empty parent field will return an error that it cannot be its own parent)
2. Attempt to delete the newly created job from the jobs list

**Comment by victorcoder** [comment]
Good catch @smiller393, something is going on in validate job. I will take a look at it, thanks for reporting.

**Comment by yvanoers** [comment]
@victorcoder I got this.
