### ISSUE TITLE
where can we find docs for connecting to etcd ?  

### ISSUE THREAD

**Issue by listaction** [distribworks/dkron#662]
**Describe the bug**
I'd like for dkron to use etcd and can't seem to find docs for this in this repo.

@victorcoder :  would be great if you could tip this issue and share how to configure dkron to use etcd.

**Comment by yvanoers** [comment]
@listaction The recently released Dkron v2 has a built-in database and no longer needs to nor is it able to connect to an external store.
Dkron v1 did need an external store, but it is now deprecated and it is heartily recommended to use v2 instead.

**Comment by victorcoder** [comment]
@yvanoers is correct, you don't need to maintain another piece of software.

@listaction I will close the issue but feel free to share your use case if that's not an option for you.
