### ISSUE TITLE
How to run dkron commands from docker instance?

### ISSUE THREAD

**Issue by a-klimashevsky** [distribworks/dkron#664]
I've run dkron via docker, how do I run commands like doc or keygen ?

**Comment by yvanoers** [comment]
Shell into the container using

`docker exec -it <container ID or name> bash`

and run the command you want to run.
To do it non-interactively, have docker execute the dkron command directly, something like this:

`docker exec -it <container ID or name> dkron doc`

though you may need to include the path to dkron, I didn't check.

**Comment by victorcoder** [comment]
@a-klimashevsky dkron Dockerfile entrypoint is set to `dkron` so you can call directly the subcommand like: `docker run -ti dkron/dkron keygen`
