### ISSUE TITLE
Error when try run 'dkron' raft list-peers

### ISSUE THREAD

**Issue by pohsiu** [distribworks/dkron#670]
**Describe the bug**
When run the command of dkron raft list-peers.
Always shown this message below
```Config File \"dkron\" Not Found etc.```

**To Reproduce**
run dkron raft list-peers

**Expected behavior**
list the node of peers
```
$ dkron raft list-peers
Node                   ID               Address          State     Voter
dkron-server01.global  10.10.11.5:4647  10.10.11.5:4647  follower  true
dkron-server02.global  10.10.11.6:4647  10.10.11.6:4647  leader    true
dkron-server03.global  10.10.11.7:4647  10.10.11.7:4647  follower  true
```

**Screenshots**
```INFO[0000] No valid config found: Applying default values.
error="Config File \"dkron\" Not Found in \"[/etc/dkron /root/.dkron /opt/local/dkron/config]\""
ERRO[2020-01-21T08:18:55Z] grpc: error dialing.
error="context deadline exceeded" method=RaftGetConfiguration node=15cfa6cb7e39 server_addr="127.0.0.1:6868"
Error: context deadline exceeded
Usage:
  dkron raft list-peers [flags]

Flags:
  -h, --help   help for list-peers

Global Flags:
      --config string     config file path
      --rpc-addr string   gRPC address of the agent (default "127.0.0.1:6868")

context deadline exceeded
```

** Specifications:**
docker-compose.yml

```
version: '3'
services:
  dkron:
    image: dkron/dkron
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    command: agent --server --log-level=debug --bootstrap-expect=1
    volumes:
      - ../data/:/opt/local/dkron/dkron.data/
  dkron-server:
    image: dkron/dkron
    ports:
      - "8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: agent --server --retry-join=dkron:8946 --log-level=debug --bootstrap-expect=3
  dkron-agent:
    image: dkron/dkron
    ports:
      - "8946"
    environment:
      - GODEBUG=netdns=go
    command: agent --retry-join=dkron:8946 --log-level=debug
```
**Additional context**
None

**Comment by pohsiu** [comment]
@victorcoder any clue of this issue?

**Comment by victorcoder** [comment]
@pohsiu it always try to load the config file though in this case is not necessary, this is what the message indicates. It's not related with the command not working properly. 

I see you are using docker to run dkron, how are you trying to run the command? I mean, are you running it with `docker exec`?

**Comment by pohsiu** [comment]
@victorcoder Thanks for replying. Sure I ran this command within docker container.

In the latest trying, I used volume create the dkron.yml in the /opt/local/dkron/config within docker, still kept getting error msg of this below

```
ERRO[2020-01-21T08:18:55Z] grpc: error dialing.
error="context deadline exceeded" method=RaftGetConfiguration node=15cfa6cb7e39 server_addr="127.0.0.1:6868"
Error: context deadline exceeded
Usage:
  dkron raft list-peers [flags]

Flags:
  -h, --help   help for list-peers

Global Flags:
      --config string     config file path
      --rpc-addr string   gRPC address of the agent (default "127.0.0.1:6868")

context deadline exceeded
```

Just without config part, the others are same.

**Comment by victorcoder** [comment]
@pohsiu Dkron RPC port binds to the assigned local IP 172.19... you should specify that with the `--rpc-addr` param.

Regarding the other issue, it's somewhat difficult to maintain a cluster in docker because docker assign an IP on start and that could change, it seems that it's your case, the node was bootstrapped with another IP, and the next time it started it's not recognised as the former member. 

You will need to assign a fixed IP to the containers in the cluster or you will need to deal with the raft commands as you are already trying to do.

**Comment by pohsiu** [comment]
@victorcoder I tried to add ```--rpc-addr``` param, but seems like don't exit this param.
```
dkron-server_1  | Error: unknown flag: --rpc-addr
dkron-server_1  | Usage:
dkron-server_1  |   dkron agent [flags]
dkron-server_1  | 
dkron-server_1  | Flags:
dkron-server_1  |       --advertise-addr string        Address used to advertise to other nodes in the cluster. By default, the bind address is advertised. The value supports go-sockaddr/template format.
dkron-server_1  |       --advertise-rpc-port int       Use the value of rpc-port by default
dkron-server_1  |       --bind-addr string             Specifies which address the agent should bind to for network services, including the internal gossip protocol and RPC mechanism. This should be specified 
...
```

**Comment by pohsiu** [comment]
@victorcoder Thanks, it works!!!

```
dkron raft list-peers --rpc-addr=10.5.0.6:6868
```
And it show the peers of node without name, turns out that's the backup data I ran in single server only.

I remove the dkron.data and restart ...

then, list-peers
```
Node  ID    Address        State     Voter
foo   foo   10.5.0.6:6868  leader    true
foo2  foo2  10.5.0.7:6868  follower  true
```
That solved my another issue.
