### ISSUE TITLE
Tmp folders left in /etc/dkron/dkron.data/raft/snapshots

### ISSUE THREAD

**Issue by pnlarsson** [distribworks/dkron#674]
Was getting warnings for low disk space and started to hunt down the culprit, surprisingly the log folders was ok, and I finally found 1.5 GB of tmp folders (i assume) in /etc/dkron/dkron.data/raft/snapshots:
```
root@event:/etc/dkron/dkron.data/raft/snapshots# du -sh *
64M     1295-903807-1578141152709.tmp
199M    1477-1092855-1578932076129.tmp
33M     2365-1668931-1580454569113.tmp
122M    3114-1751333-1580624392074.tmp
122M    3118-1751347-1580624574876.tmp
125M    3191-1784281-1580691921143.tmp
145M    4210-1874933-1580878890504.tmp
147M    4224-1881000-1580896294103
147M    4224-1883257-1580895997297.tmp
148M    4259-1889276-1580908558155
149M    4259-1897520-1580925307170
107M    598-772299-1577600470525.tmp
80M     656-780506-1577634235482.tmp
```
On the other node there is 4 folders - about 549 mb of data.

 - OS: Debian 9
 - Version 2.0.1? -> 2.0.4

Is this excepted behavior? The logs have been truncated by systemd, so I have nothing to show what happened at the time. According to systemctl status - the service has been running for 12 hours and this folders has been created after the start (10:47):
```
drwxr-xr-x  2 root root 4096 Feb  5 10:46 4224-1883257-1580895997297.tmp
drwxr-xr-x  2 root root 4096 Feb  5 10:51 4224-1881000-1580896294103
drwxr-xr-x  2 root root 4096 Feb  5 14:15 4259-1889276-1580908558155
drwxr-xr-x  2 root root 4096 Feb  5 18:55 4259-1897520-1580925307170
```

**Comment by victorcoder** [comment]
Those tmp folders shouldn't be there, the expected snapshot folders is set to 3, looks like something went wrong when the node tried to write the snapshot, I guess you can safely remove them, you can try that, if it fails, my recommendation would be to replace the node. 

Let me know in case you get some logs to try to reproduce the error.

**Comment by pnlarsson** [comment]
For some time now - there is  snapshot folders, so all is well again
