### ISSUE TITLE
--raft-multiplier is ignored

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#694]
**Describe the bug**
--raft-multiplier cmd line parameter is ignored, when specified both, in config or cmd parameters.
I tried to investigate this, but didn't have any luck to pinpoint where it happens.

After bad luck with investigation, I tried to hardcode the default value for RaftMultiplier to dkron/config.go and it works just fine.

**Comment by victorcoder** [comment]
@andreygolev Could it be this? https://github.com/distribworks/dkron/blob/master/dkron/agent.go#L245

**Comment by andreygolev** [comment]
Yes, exactly :) Everything from code looks in place, but it simply not working by unknown reason :)
Of course I'm using the value in the range of 1 - 10.
Try to print value of RaftMultiplier to stdout, and you should see that it's the default one, despite you're setting option.
I noticed it, because I started to see check failover and times were same, despite a value I set in a Multiplier via command line.
But it works just fine If hardcode it into a code :) This is how it works today, still in our infra.
