### ISSUE TITLE
job update endpoint removes dependent_jobs

### ISSUE THREAD

**Issue by fopina** [distribworks/dkron#707]
In Dkron 1, I could easily make a post to create a job with basic fields, such as name, schedule and command.

If I created a "child" one, I could see it as `dependent_job`.
Updating that parent job with only name, schedule and command would not affect depedent_jobs.

Now with Dkron2, the same update sets `dependent_jobs` to null, effectively disabling them...
Is that intended? Should `PATCH` be implemented to effectively update only mentioned fields?

**Comment by victorcoder** [comment]
This could be a regression, let me do some tests.

**Comment by fopina** [comment]
Cool I finally onboarded the cluster I had to (with some bugs), so I’ll be able to try to take a look at this as well

**Comment by victorcoder** [comment]
I think this is fixed, could you recheck? 

You can not update schedule in a child job.
