### ISSUE TITLE
Skipped Jobs

### ISSUE THREAD

**Issue by agarwal-nitesh** [distribworks/dkron#708]
A job is not picked for the next run and so miss all subsequent runs.

This happens at irregular intervals but happens all the time. It happens for a job, you make an update call, and it starts working. Then this bug appears in some other job.
I have created a Prometheus-exporter that sends alerts related to this and my Slack Channel is full of these alerts.
<img width="397" alt="Screenshot 2020-03-20 at 2 11 34 AM" src="https://user-images.githubusercontent.com/37532307/77113098-2fcb4500-6a50-11ea-9d43-a6467c9f54d2.png">

OS: centos

Version Dkron 2.0.0-rc10

**Comment by victorcoder** [comment]
Hi @agarwal-nitesh, have you tried with a recent, non-RC version? That will be the first step.

Another question, what is that monitor checking?

**Comment by agarwal-nitesh** [comment]
Hi @victorcoder, thanks for responding. I will upgrade the version and then monitor it but did you fix this specific issue in versions after Dkron 2.0.0-rc10? 
The above alert checks if the next execution time is less than the current time. 
```
     diff_date = next_date - datetime.datetime.now(datetime.timezone.utc)
     if diff_date < datetime.timedelta(minutes=-1):
         metric.add_metric([name], {'success': False})
```
