### ISSUE TITLE
service failed to start after update to 2.1.1

### ISSUE THREAD

**Issue by alotofshit** [distribworks/dkron#722]
Dkron service failed to start after update to 2.1.1 from 2.0.1. The оther part from the cluster is with 2.0.1
 

1.  the upgrade was done through dkron_2.1.1_linux_x86_64.rpm
2. upload my  config 

server: true
join:
   - exec-1
   - exec-2
   - exec-3
   - exec-4
   - exec-5

3. the logs from journalctl -u dkron

Apr 08 10:02:06 exec-1 dkron[33208]: time="2020-04-08T10:02:06+03:00" level=info msg="agent: Received event" event="query: run:job" node=exec-1
Apr 08 10:02:06 exec-1 dkron[33208]: time="2020-04-08T10:02:06+03:00" level=info msg="agent: Starting job" job=upload_DB node=exec-1
Apr 08 10:02:06 exec-1 dkron[33208]: time="2020-04-08T10:02:06+03:00" level=error msg="grpc: Error calling gRPC method" error="rpc error: code = Unimplemented desc = unknown service types.Dkron" method=GetJ
Apr 08 10:02:06 exec-1 dkron[33208]: time="2020-04-08T10:02:06+03:00" level=error msg="agent: Error on rpc.GetJob call" error="rpc error: code = Unimplemented desc = unknown service types.Dkron" node=exec-1

** Specifications:**
 - OS: CentOS 7.6
 - Version 2.1.1

**Comment by victorcoder** [comment]
@alotofshit check the changelog for breaking changes, from 2.0.x to 2.1.x https://github.com/distribworks/dkron/blob/master/CHANGELOG.md#breaking-changes

You will need to rotate your current cluster nodes

Are you using custom plugin?

**Comment by alotofshit** [comment]
I`m starting to rotate all nodes to 2.1.1 but  stucking on that:   Raft layer failed to start" error="new raft: failed to load any existing snapshots". Where is stored snapshots?

**Comment by victorcoder** [comment]
With rotate I mean, replacing old nodes, if you try to install 2.1.x over 2.0.x it will crash because snapshots are not compatible. 

Snapshots are located in the `--data-dir` check the docs in the command line or in https://dkron.io/cli/dkron_agent/

You can not upgrade a node from 2.0.x to 2.1.x, you need to add a new node with 2.1.1 then remove the old one.

**Comment by alotofshit** [comment]
thanks.
