### ISSUE TITLE
Scheduled Jobs do not run sporadically

### ISSUE THREAD

**Issue by MarkLie** [distribworks/dkron#728]
**Describe the bug**
Sporadically some of our scheduled jobs do not run. In our log, we can find the following message for these jobs:
`msg="invoke: command error output" error="Not reach the expected code"`

We have absolutely no idea, what could be the reason for this. Can you please give us a hint on this?

**Specifications:**
 - Docker Container dkron/dkron:v1.2.5
 - Using Consul backend, as shown by the following Docker CMD
`agent --server --http-addr=**** --backend=consul --backend-machine=****`

**Comment by victorcoder** [comment]
@MarkLie just to confirm, are you still using v1? it's not supported anymore. Would it be possible for you to use v2.2?

**Comment by MarkLie** [comment]
Yes, unfortunately we still use v1. Is this a known bug in v1? Has a similar behaviour been observed for v2?

**Comment by victorcoder** [comment]
First report of this issue, what executor are you using?

Will it be possible for you to upgrade to v2.2?

It will probably be quite straightforward to migrate using the new `/restore` endpoint

**Comment by MarkLie** [comment]
We are using HTTP executor.
I need to discuss an upgrade with v2.2 with my colleagues.
