### ISSUE TITLE
Scheduled jobs sometimes not being executed

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#731]
**Describe the bug**
Hi,
There's a one issue that I can't pinpoint and need the help.
We have around 50 jobs that are being scheduled at different times and we're using master version.
Sometimes, by no reason (so far) random jobs at random times are not executed, despite visible they're scheduled.
I've modified logs a bit to see a flow of a job from time being scheduled to end of execution.
During the issue the flow is the following:

```
time="2020-04-21T02:00:00Z" level=debug msg="scheduler: Run job" job=sync_local_ip_list_dms_0 node=dkron-server-1 schedule="0 0 2 * * *"
time="2020-04-21T02:00:00Z" level=debug msg="store: Retrieved job from datastore" job=sync_local_ip_list_dms_0 node=dkron-server-1
time="2020-04-21T02:00:00Z" level=info msg="agent: Sending query" job_name=sync_local_ip_list_dms_0 node=dkron-server-1 query="run:job"
time="2020-04-21T02:00:00Z" level=debug msg="store: Setting job" job=sync_local_ip_list_dms_0 node=dkron-server-1
time="2020-04-21T02:00:00Z" level=debug msg="store: Retrieved job from datastore" job=sync_local_ip_list_dms_0 node=dkron-server-1
time="2020-04-21T02:00:00Z" level=debug msg="agent: Filtered nodes to run" job_name=sync_local_ip_list_dms_0 job_name_from_function=sync_local_ip_list_dms_0 node=dkron-server-1 nodes="[dms-dkron-kapp-5dbf554656-vr99b]"
time="2020-04-21T02:00:00Z" level=debug msg="agent: Filtered tags to run" job_name=sync_local_ip_list_dms_0 job_name_from_function=sync_local_ip_list_dms_0 node=dkron-server-1 tags="map[dms:cron region:global]"
time="2020-04-21T02:00:00Z" level=debug msg="agent: Sending query" job_name=sync_local_ip_list_dms_0 json="{\"execution\":{\"job_name\":\"sync_local_ip_list_dms_0\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"success\":false,\"group\":1587434400017697229,\"attempt\":1},\"rpc_addr\":\"172.25.4.133:6868\"}" node=dkron-server-1 query="run:job"
time="2020-04-21T02:00:08Z" level=debug msg="agent: Done receiving acks and responses" fields.time=8.014626936s job=sync_local_ip_list_dms_0 node=dkron-server-1 query="run:job"
```

In normal cases, before "Done receiving acks and responses" step, there are also steps:
"agent: Received ack" and "agent: Received response"

It looks like chosen agent node in step "Filtered nodes to run" by some reason is ignoring or not receiving broadcasted query.

From the view of agent node, there is simply no log message "Running job" for a given job.
Though there are visible log messages from serf like
```
time="2020-04-21T02:00:00Z" level=info msg="2020/04/21 02:00:00 [DEBUG] serf: messageQueryType: run:job"
```
Due to an intense workload, it's hard to tell if that log message is generated from a missed job.

What can we do about this? To pinpoint the problem and fix it.

**Expected behavior**
No misses!

**Comment by andreygolev** [comment]
Could it be because of: https://github.com/distribworks/dkron/blob/8485b514e6801d8a8950329d93ca3c97ecd92060/dkron/agent.go#L415

We have quite a big activity.

**Comment by victorcoder** [comment]
@andreygolev thanks for the investigation, I observed this just once in the past, I suspected this but did not confirm it back then. So seems Serf is missing the event.

Does this happens frequently to you?

From the line you mentioned, yeah it looks like this buffer is too small, let's try with bigger value.

**Comment by victorcoder** [comment]
For the record: If #732 don't fix the issue we will reopen

**Comment by andreygolev** [comment]
Yeah, this happens sometimes multiple times per day.
Anyway, let's see how it goes.

I'm testing since yesterday with 256 buffer size.
I stole values from Consul code :)

```

**Comment by victorcoder** [comment]
@andreygolev me too but as I see in consul they use 2048 https://github.com/hashicorp/consul/blob/b5c7d292e48f9aed4b8eaefa355c573dbd753e58/agent/consul/server.go#L85, could you point to where 256 is used?

**Comment by andreygolev** [comment]
https://github.com/hashicorp/consul/blob/master/agent/consul/client.go#L40

**Comment by victorcoder** [comment]
In our case the size applies to both "server" and "client", let's see how it works for you with 256, and with 2048 in the release

**Comment by andreygolev** [comment]
Yeah. I can actually switch to 2048 right away and test with it

**Comment by andreygolev** [comment]
So, 2048 didn't help at all. I deployed on both servers and agents. No changes at all. Same behaviour.

**Comment by andreygolev** [comment]
One more idea I had in mind, that this may happen because of serf.QueryParam. There's no timeout set. It's using default one. Which 500ms for a LAN profile. Though I'm using WAN profile, because of some sporadic failovers on a stable LAN type network.
Maybe it's worth testing with some higher timeout value.

Also there are logs like this:
```

**Comment by andreygolev** [comment]
Tried to pause worker agent process to simulate situation. Server node was throwing "Done receiving acks and responses" without any "agent: Received ack" messages. Expected, but, after I unpause worker agent process it seems that it's getting all Serf messages from some queue and finds the message for a job and starts executing it.

**Comment by victorcoder** [comment]
@andreygolev, can you try with the code in this branch https://github.com/distribworks/dkron/tree/fix_missing_executions it implements retries in case of missing job executions ACKs.

Please, let me know if it mitigates the issue.

**Comment by andreygolev** [comment]
Hmmm, I'm already testing with my version of retries :)
So far, there are no missing jobs with my implementation.
Though things look really weird...
Serf messages are actually not missing in a black hole. Nodes are responding, but somewhere like after 30 secs, or a minute. It's random.
And sometimes it's required to make up to 3 retries in order to catch an Ack.

My implementation is a bit different than yours.
I'm sending expected query response time along with Serf query payload. Otherwise, job can execute multiple times on agent.
I'll try to create PR tomorrow to show you what crap I've done :D

P.S. I've sent an email to you few days ago. The problem I've described in there is more fatal :)

**Comment by sysadmind** [comment]
We are having the same issue in our deployment. We have pushed the `fix_missing_executions` branch to our development environment and as long as there are no issues, we plan to push to production where we see this issue commonly tomorrow. I will report back with any findings.

**Comment by andreygolev** [comment]
I've opened PR today, just to show how I'm fixing missing issues: https://github.com/distribworks/dkron/pull/745

So far, it works good for a week without any misses. We're sending last execution timestamps of jobs to Prometheus, and have alerts if the job was not executed in expected time range. (Alerts for prometheus are auto-generated from CI, based on job schedule definitions)

Could you pls share your branch for a sake of curiosity? :)

**Comment by victorcoder** [comment]
@andreygolev I think @sysadmind refers to my branch https://github.com/distribworks/dkron/tree/fix_missing_executions It is just a naive try to fix the issue.

FYI I'm working on a definitive fix, refactoring by removing Serf queries at all and moving all run request to gRPC calls, using the great features in gRPC like the retries, that will give us much more reliability and at least better visibility on what went wrong in case of network errors.

Expect something in the following days.

I'm already testing it in http://test.dkron.io:8080/dashboard/ so far so good, like a clock :)
