### ISSUE TITLE
Shifting UI status panel makes it nearly impossible to enable/disable many jobs sequentially

### ISSUE THREAD

**Issue by drauschenbach** [distribworks/dkron#733]
**Describe the bug**
An operator needs to enable or disable 20 or 30 jobs in a row. As they click on each pause icon, the screen shifts downwards as the status panel appears inline up in the page's header area. The user either clicks on the wrong icon next, because the screen has shifted, or has to wait for a timeout period before the screen shifts a second time as the status panel disappears. This problem is exacerbated by a 2nd bug (#734), which is that after a status change the icon oftentimes does not reflect the change until a page reload.

**To Reproduce**
1. Enable or disable a job.
2. Enable or disable the next job. Chances are you end up clicking on the wrong job, because the screen has shifted by 2 or 3 jobs.

**Expected behavior**
An operator should be able to enable or disable dozens of jobs just as fast as they can click on them.

**Workaround**
After each enabling or disabling of any job:
1. Reload the page to accurately display the enable/disable status of jobs
2. Re-enter the active search
3. Navigate back to the given paginator page

**Specifications:**
 - Server OS: linux
 - Version 2.2.0 Pro
- Client OS: Windows
- Client browser: Chrome

**Additional context**
This behavior occurs on a 3-node cluster.

**Comment by victorcoder** [comment]
Thanks for reporting @drauschenbach, certainly these glitches needs to be addressed. WIP
