### ISSUE TITLE
A new UI search fails unless you start on page 1 of the paginator

### ISSUE THREAD

**Issue by drauschenbach** [distribworks/dkron#735]
**Describe the bug**
New UI searches fail to reset the paginator. Or, to put it anohter way, they re-use the paginator from the list view, and apply it to future searches, which causes new searches to typically show no results because you don't realize you're on page 2 or 10 or 15 of the search results, even though you just entered the search.

**To Reproduce**
1. Navigate to page 2 of a list of jobs
2. Enter a new search
3. Observe that you are seeing search results for page 2 of the search, which typically means that you cannot see the search results.

**Expected behavior**
A new search should reset the paginator, so that expected search results are shown. A paginator should not be re-used between different contexts, such as a list view and a search view.

**Specifications:**
 - OS: linux
 - Version 2.2.0 Pro
 - Browser OS: Windows
 - Browser: Chrome

**Comment by victorcoder** [comment]
Fixed in the new UI in v3.1.0
