### ISSUE TITLE
Active streaming jobs are not displayed in the UI

### ISSUE THREAD

**Issue by drauschenbach** [distribworks/dkron#736]
**Describe the bug**
Since 2.2.0, the new streaming executions capability added a new section of the UI where active jobs are displayed. After several weeks of use, our team only saw one job displayed here, for only a brief moment. Our jobs run long (1 minute, or up to 3 hours), so we typically have jobs running.

**To Reproduce**
1. Launch a long running job via the Dkron UI.
2. Switch to the new active running jobs view, and observe that none are displayed.
3. Click on the job that was started, and observe that the history indicates that the job was started, and that it correctly shows that it has not yet finished.
4. Wait for the job to finish
5. Reload the job page, and observe that the last entry in the history has correctly captured the entire stdout, and that it has recorded the proper exit code.

**Expected behavior**
Running jobs are shown in the new UI section that is supposed to display them. Also, I'd expect that the job last run status icon would change from the question mark to the green success indicator without me having to page reload.

**Specifications:**
 - OS linux
 - Version 2.2.0 Pro
 - Browser OS: Windows
 - Browser: Chrome

**Additional context**
Using a 3-node cluster.

**Comment by victorcoder** [comment]
This is weird you can almost always observe running jobs here http://test.dkron.io:8080/dashboard/busy

Can you post the relevant log of the job run? You are probably experiencing some network issue.

**Comment by drauschenbach** [comment]
Indeed, that link above is working very well for me from my iPhone, my Mac on a residential network, and my Windows PC on a corporate VPN.

I'll see what I can find out that makes my 3-server cluster on a corporate network unique. I think it will have something to do with the fact that the xhr's only seem to hold open their connections if I open my dev tools tab in chrome, whereas otherwise a different behavior is observed. Same for Safari.

**Comment by drauschenbach** [comment]
The list of jobs on that test page shows very fast. Because of this, it is not demonstrating whether the active jobs list display is initially seeded with jobs in progress. Perhaps it is only showing the status of jobs whose state has changed since after the browser route was loaded?

**Comment by victorcoder** [comment]
No @drauschenbach, the list is not rendered on page load, it's an xhr request, check your browser calls in the developer tools.

The jobs you mention in your installation, what's their running time? Can you check the response of the UI xhr request in the Busy page?
