### ISSUE TITLE
Missing ExecutionDone events on server restart

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#737]
**Describe the bug**
When agent node wants to send ExecutionDone, it looks at LocalServers and chooses one of them to send event.
After you restart any of server agents, it immediately joins cluster, and reports that it's alive, but Raft is still not replicated and applied.
This results to the following spike of errors:
```
time="2020-04-24T09:25:52Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=ExecutionDone node=dkron-server-0 server_addr=
```
After Raft is applied, errors are gone and everything is working as usual.
As a result, some ExecutionDone events are missed on restart of any server member.

**Expected behavior**
No missing events.
Maybe responses from worker agents should be sent only to leader node?

**Additional context**
In our case, we don't use persistent storage on server agents. That means that whole Raft is being replicated on each server restart. We have a lot of Raft events, and that takes like 10-20 seconds to fully replicate Raft.

**Comment by andreygolev** [comment]
Maybe that's not relevant with Streaming executions which I gonna test very soon :)

**Comment by victorcoder** [comment]
#749 is now merged
