### ISSUE TITLE
Nodefilter sometimes return wrong nodes

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#761]
**Describe the bug**
It looks that new nodefilter with Intersect method sometimes returns wrong list of destination nodes.
All our jobs do have tag filter: "worker": "cron:1"

And according to execution groups, sometimes some jobs are not executing on a single node, but on all in the cluster, including servers. Though also visible, that status of all executions in an execution group is "False", while if execution is scheduled correctly on a single node, it's with status Success: true.

**Comment by victorcoder** [comment]
And does this happens randomly? Does the executions in other nodes finish?

**Comment by victorcoder** [comment]
I tested with the tags you specified and I can not reproduce, we need to find the exact combination of tags that can make this fail.

Can you dump all tags you are using?

**Comment by andreygolev** [comment]
Well, that's just that single tag. One group of agents are running with:
```
    tags:
      instalment: cron
```

and other group of nodes:
```
    tags:
      dms: cron
```

**Comment by andreygolev** [comment]
What I've found so far, that there's a line that is setting tag
https://github.com/distribworks/dkron/blob/master/dkron/agent.go#L693

When I don't have any agents with my tags, then processfilterednodes returns all server nodes in cluster, because all agents in a cluster have region tag set by default.

**Comment by victorcoder** [comment]
Good catch! need to fix this and add a test for it.
