### ISSUE TITLE
Jobs not persisting when using docker volumes

### ISSUE THREAD

**Issue by peterbradford** [distribworks/dkron#768]
Using the example at https://dkron.io/v2.0/basics/installation/ I spin up a docker container and create a job or two, but after i restart that container, to simulate a failure or upgrade, my jobs never persist across the restart. 

I have two comments at this point
1) the command to start the docker container uses an internal directory /dkron.data but that doesn't get used for me without using the 'data-dir=/dkron.data' option in the docker run command. i.e.
'docker run -d -p 8080:8080 -v ~/dkron.data:/dkron.data --name dkron dkron/dkron agent --server --bootstrap-expect=1 --data-dir=/dkron.data'
 
2) when using the above changes, I see the internal docker directory /dkron.data/raft/raft.db update when i first create the job, and it updates again when i restart the container but the job isn't there on restart. I also see those updates on the host directory at ~/dkron.data/raft/raft.db. 
I assume that on restart dkron is overwriting raft.db with an empty set of jobs rather than pulling from those jobs at raft.db

looks like the version of dkron in that docker container is 3.0.2

I can provide screenshots or additional info, and if i've got something wrong please let me know. Thanks!

**Comment by victorcoder** [comment]
@peterbradford start the container using a node name:

`docker run -d -p 8080:8080 --name dkron dkron/dkron agent --server --bootstrap-expect=1 --node-name=node1`

Explanation: On each restart docker assign a new hostname, Dkron uses the hostname for the node-name by default, Raft protocol stores the node-name to identify the node. On the second start it can not find the previous node.

I will modify the docs to reflect this.

**Comment by peterbradford** [comment]
awesome! thanks @victorcoder for the quick response, that worked
