### ISSUE TITLE
Service start error

### ISSUE THREAD

**Issue by sicchieri** [distribworks/dkron#769]
we have a issue when try start the service
presenting the error below.

DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-elasticsearch]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-elasticsearch
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-elasticsearch pid=2992
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-elasticsearch
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin720013124 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-elasticsearch timestamp="2020-05-21T18:31:29.415Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-email]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-email
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-email pid=2999
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-email
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin672084099 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-email timestamp="2020-05-21T18:31:29.424Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-files]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-files
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-files pid=3006
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-files
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin478533326 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-files timestamp="2020-05-21T18:31:29.433Z"
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-fluent]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-fluent
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-fluent pid=3012
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-fluent
DEBU[2020-05-21T18:31:29Z] time="2020-05-21T18:31:29Z" level=warning msg="empty value for environment variable FLUENTBIT_HOST"  node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-fluent
DEBU[2020-05-21T18:31:29Z] time="2020-05-21T18:31:29Z" level=warning msg="empty value for environment variable FLUENTBIT_PORT"  node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-fluent
DEBU[2020-05-21T18:31:29Z] time="2020-05-21T18:31:29Z" level=warning msg="empty value for environment variable FLUENTBIT_TAG"  node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-fluent
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin323391667 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-fluent timestamp="2020-05-21T18:31:29.443Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-log]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-log
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-log pid=3019
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-log
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin041498457 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-log timestamp="2020-05-21T18:31:29.451Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-slack]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-slack
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-slack pid=3026
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-slack
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin641007499 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-slack timestamp="2020-05-21T18:31:29.460Z"
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-processor-syslog]" node=ip-172-32-45-2 path=/usr/bin/dkron-processor-syslog
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-processor-syslog pid=3032
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-processor-syslog
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin533809634 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-processor-syslog timestamp="2020-05-21T18:31:29.468Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-executor-docker]" node=ip-172-32-45-2 path=/usr/bin/dkron-executor-docker
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-executor-docker pid=3039
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-executor-docker
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin788876748 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-executor-docker timestamp="2020-05-21T18:31:29.480Z"
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-executor-ecs]" node=ip-172-32-45-2 path=/usr/bin/dkron-executor-ecs
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-executor-ecs pid=3045
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-executor-ecs
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin571695996 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-executor-ecs timestamp="2020-05-21T18:31:29.491Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-executor-http]" node=ip-172-32-45-2 path=/usr/bin/dkron-executor-http
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-executor-http pid=3052
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-executor-http
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin919326472 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-executor-http timestamp="2020-05-21T18:31:29.499Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
DEBU[2020-05-21T18:31:29Z] starting plugin                               args="[/usr/bin/dkron-executor-shell]" node=ip-172-32-45-2 path=/usr/bin/dkron-executor-shell
DEBU[2020-05-21T18:31:29Z] plugin started                                node=ip-172-32-45-2 path=/usr/bin/dkron-executor-shell pid=3060
DEBU[2020-05-21T18:31:29Z] waiting for RPC address                       node=ip-172-32-45-2 path=/usr/bin/dkron-executor-shell
DEBU[2020-05-21T18:31:29Z] plugin address                                address=/tmp/plugin757067715 network=unix node=ip-172-32-45-2 subsystem_name=plugins.dkron-executor-shell timestamp="2020-05-21T18:31:29.507Z"
DEBU[2020-05-21T18:31:29Z] using plugin                                  node=ip-172-32-45-2 version=1
INFO[2020-05-21T18:31:29Z] agent: Dkron agent starting                   node=ip-172-32-45-2
INFO[2020-05-21T18:31:29Z] 2020/05/21 18:31:29 [INFO] serf: EventMemberJoin: ip-172-32-45-2 ::
INFO[2020-05-21T18:31:29Z] agent: joining: [] replay: true               node=ip-172-32-45-2
**FATA[2020-05-21T18:31:29Z] listen tcp: lookup <nil>: no such host        node=ip-172-32-45-2**

** Specifications:**
 - OS: Centos
 - Version release 7.7.1908 (Core)

![image](https://user-images.githubusercontent.com/25644946/82590581-530b9100-9b74-11ea-8e20-d8ac8f8b8577.png)

![image](https://user-images.githubusercontent.com/25644946/82590624-628ada00-9b74-11ea-9da6-ac0dc7007c9f.png)

**Comment by victorcoder** [comment]
Can you post the configuration file or the command line params you are using?

**Comment by sicchieri** [comment]
follow the configuration file:

# Dkron example configuration file
 server: true
 bootstrap-expect: 1
# data-dir: dkron.data
 log-level: debug
bind-addr: "{{ GetPrivateIP }}:8946"
# tags:
#   dc: east
# encrypt: a-valid-key-generated-with-dkron-keygen
# retry-join:
#   - 10.0.0.1
#   - 10.0.0.2
#   - 10.0.0.3
# raft-multiplier: 1
# webhook-url: https://hooks.slack.com/services/XXXXXX/XXXXXXX/XXXXXXXXXXXXXXXXXXXX
# webhook-payload: "payload={\"text\": \"{{.Report}}\", \"channel\": \"#foo\"}"
# webhook-headers: Content-Type:application/x-www-form-urlencoded
# mail-host: email-smtp.eu-west-1.amazonaws.com
# mail-port: 25
# mail-username": mailuser
# mail-password": mailpassword
# mail-from": cron@example.com
# mail-subject_prefix: [Dkron]

command:
dkron agent --server --bootstrap-expect=1
service dkron start
