### ISSUE TITLE
Node crashes in ExecutionDone after leadership change

### ISSUE THREAD

**Issue by drauschenbach** [distribworks/dkron#771]
**Describe the bug**
In the Dkron UI a job appeared to still be running, but the script that was invoked did in fact complete. A review of the Dkron log (captured by systemd) indicated a leadership change occurred, then a following attempt to record the ExecutionDone resulted in a nil pointer deference causing a crash of the process. We configure systemd to restart the process; however, the Dkron UI still shows the job as running, since its disposition was never properly recorded.

**To Reproduce**
1. Cause a network disruption during the running of a job on the leader node.
2. Observe that occasionally this will lead to a crash of the process.

**Expected behavior**
No nil pointer dereferences should ever occur, leading to an uncontrolled process crash.

**Specifications:**
 - OS: Oracle Linux (a Fedora)
 - Version: Dkron Pro 2.2.2

**Additional context**
[capture.log](https://github.com/distribworks/dkron/files/4669520/capture.log)

**Comment by victorcoder** [comment]
Hi @drauschenbach, this issue doesn't apply to the latest > 3.x branch, have you been able to test it?

**Comment by drauschenbach** [comment]
Hi @victorcoder, this issue has not occurred since we upgraded to 3.x. I've read through the commits and I'm nearly certain that this is fixed now. But I could not pinpoint the precise commit. Thanks!
