### ISSUE TITLE
can i pass multiple cron jobs in /jobs post api

### ISSUE THREAD

**Issue by chenchunaidu** [distribworks/dkron#775]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenchunaidu** [comment]
How can i passing array of cron jobs in jobs api.now if i pass array of cron jobs i am getting error saying Unable to parse payload: json: cannot unmarshal array into Go value of type dkron.Job.

**Comment by victorcoder** [comment]
Use the `/restore` endpoint to bulk load jobs. See https://dkron.io/usage/upgrade/#backup--restore
