### ISSUE TITLE
How do I build a cluster of three nodes on a single machine

### ISSUE THREAD

**Issue by myyukiho** [distribworks/dkron#782]
I'm trying to build a three-node cluster of dkron on a single machine, as what I used to do with etcd cluster, but somehow I couldn't make it work.
Here are command line params:
node01:
`dkron agent --server --bind-addr="0.0.0.0:8946" --rpc-port=6868 --http-addr=":6080" --advertise-addr="0.0.0.0:8946"`

node02:
`dkron agent --server --bind-addr="0.0.0.0:8947" --rpc-port=6869 --http-addr=":6081" --advertise-addr="0.0.0.0:8947"`

node03:
`dkron agent --server --bind-addr="0.0.0.0:8948" --rpc-port=6870 --http-addr=":6082" --advertise-addr="0.0.0.0:8948"`

dkron.yml:
```
server: true
bootstrap-expect: 3
retry-join:
  - 0.0.0.0:8946
  - 0.0.0.0:8947
  - 0.0.0.0:8948
```

After I bootstrapped three nodes, I could only access web UI at `localhost:6080`, but port `6081` and `6082` cannot be accessed. And there was only one node appeared in the cluster. Is there anything wrong with my configuration?

**Comment by victorcoder** [comment]
@myyukiho good catch, with the latest changes in bind-addr config, using 0.0.0.0 rendered unusable for retry-join. Please see #783
