### ISSUE TITLE
one node had down by runtime error

### ISSUE THREAD

**Issue by JKeyZ** [distribworks/dkron#784]
I found node down in the morning. The error msg was runtime error.Follow is detail info:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x942c8a]

goroutine 538899 [running]:
google.golang.org/grpc.(*Server).Stop(0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1482 +0x4a
github.com/distribworks/dkron/v3/plugin.(*ExecutorClient).Execute(0xc0004a4900, 0xc0029c66c0, 0x350a0e0, 0xc00041e6a0, 0xc0022a4e80, 0xc0004e8301, 0xc)
	/dkron/plugin/executor.go:65 +0x190
github.com/distribworks/dkron/v3/dkron.(*AgentServer).AgentRun(0xc000208288, 0xc00063f650, 0x3570120, 0xc001c7f490, 0x0, 0x0)
	/dkron/dkron/grpc_agent.go:78 +0x59c
github.com/distribworks/dkron/v3/plugin/types._Agent_AgentRun_Handler(0x2520f00, 0xc000208288, 0x356a8a0, 0xc000268e40, 0x4b079e0, 0xc00279d500)
	/dkron/plugin/types/dkron.pb.go:1862 +0x109
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000da0b60, 0x3578280, 0xc001856f00, 0xc00279d500, 0xc00063e960, 0x4aa7d60, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcbc
google.golang.org/grpc.(*Server).handleStream(0xc000da0b60, 0x3578280, 0xc001856f00, 0xc00279d500, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xc64
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001f6c7c0, 0xc000da0b60, 0x3578280, 0xc001856f00, 0xc00279d500)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1

**Comment by victorcoder** [comment]
Could you share a bit more context of what was happening before the crash? thanks!

**Comment by JKeyZ** [comment]
always crash os was centos6, so I change to centos7 is ok

**Comment by vcastellm** [comment]
oldie
