### ISSUE TITLE
Streaming execution GRPC errors on long running jobs with no output

### ISSUE THREAD

**Issue by andreygolev** [distribworks/dkron#792]
**Describe the bug**
We have long running jobs that produce output only at the end of job.
And it seems like GRPC may close connection on one side due to idling in stream, because no output is produced during streaming execution. This makes think DKRON that job execution failed, and it retries it, which is not desired behaviour.

On server side error:
```
time="2020-06-26T08:57:55Z" level=error msg="grpc: Error on execution streaming, agent connection was abruptly terminated" error="rpc error: code = Internal desc = grpc: failed to unmarshal the received message unexpected EOF" node=dkron-server-0
```

On agent side:  grpc: Error on execution streaming, agent connection was abruptly terminated

**To Reproduce**
It reproduces on 20 minute running jobs in our case.

**Expected behavior**
No failed execution when everything is alive.

**Comment by andreygolev** [comment]
According to error "unexpected EOF" it looks more that OS is closing idle connections.
That makes me think, that some sort of heartbeat messages from agent/executor plugins are required.

**Comment by andreygolev** [comment]
What I've found so far is that Streaming executions are using hashicorp's go-plugin which was designed to work only on reliable networks (localhost?). According to their code, they don't have any heartbeat options possible.

**Comment by andreygolev** [comment]
After tackling issue a bit more, it appears that problem happens when job has a large output to stdout/stderr.

**Comment by ntloi95** [comment]
Thank you @andreygolev for tackling the issue :bowing_man:
