### ISSUE TITLE
Set a timeout for long running jobs with the ability to have them automatically killed.

### ISSUE THREAD

**Issue by jonathanhle** [distribworks/dkron#8]
1) Being able to set a time out on jobs
2) Being able to kill the job if it’s timed out.

**Comment by victorcoder** [comment]
This should be implemented in executors

**Comment by yvanoers** [comment]
Considering this is a very old feature request, I think this is now a feature request for the shell executor plugin.

Timeouts on shell jobs can be facilitated:
on Linux, using the `timeout` command,
on MacOS, using the `gtimeout` command from coreutils homebrew,
on Windows, using a tool such as [tuxliketimeout](https://github.com/cernoch/tuxliketimeout).

IMHO this feature request would violate the design philosophy of doing one thing and doing it well.

**Comment by victorcoder** [comment]
This could be implemented quite easily with the latest changes in the arch. I don't know if it's a demanded feature. Please vote.

**Comment by yvanoers** [comment]
This was added by #906 and was released in Dkron v3.1.5.
