### ISSUE TITLE
Repeated execution for one-time cron job

### ISSUE THREAD

**Issue by songyanho** [distribworks/dkron#801]
**Describe the bug**
We use API to schedule cron job on dKron with the following specs and dKron execute this task at all of the nodes. What we expect is a single execution on one node only. This results in duplication of execution and results.

Spec:

```
{
  "name": "xxx",
  "schedule": "@at 2020-07-13T23:55:00Z",
  "owner": "xxx",
  "owner_email": "xxx",
  "disabled": false,
  "executor": "http",
  "executor_config": {
    "body": "{\"conf\":{\"id\":1010}}",
    "debug": "true",
    "expect_body": "",
    "expect_code": "304",
    "header": "[\"Content-Type: application/json\",\"Cache-Control: no-cache\"]",
    "method": "POST",
    "timeout": "30",
    "url": "http://xxx"
  }
}
```

dKron dashboard:

**To Reproduce**
1. Create the job with the spec above
2. dKron execute the cron with all the nodes

**Expected behavior**
Single execution on a node

**Screenshots**
![image](https://user-images.githubusercontent.com/6477789/87651012-18456400-c785-11ea-8f38-3f9fd0be0d64.png)

** Specifications:**
 - Docker: dkron/dkron:v3.0.4
 - Kubernetes deployment: 3 servers, total 6 nodes

**Comment by Arkhamp** [comment]
I think the behavior is normal, you are not using the tag flied, I recommend to check it out this link https://dkron.io/usage/target-nodes-spec/

**Comment by songyanho** [comment]
Thanks for your help. It has been resolved.
