### ISSUE TITLE
how to link?

### ISSUE THREAD

**Issue by f4ntash** [distribworks/dkron#802]
Hello good morning, I am having trouble knowing how to link dkron to my react app.

I am a novice in react and I was asked to use dkron for auto jobs. but i didn't find documentation on how to link my react front to dkron. Could someone help me please?

**Comment by victorcoder** [comment]
Hi @f4ntash, given that you have a working Dkron installation, you will need to call the API to manipulate jobs in Dkron, the API spec is in [this section](https://dkron.io/api/) of the documentation.

Using the API should be enough to link your React app to Dkron.
