### ISSUE TITLE
Pagination support in get job list api

### ISSUE THREAD

**Issue by lakhan000** [distribworks/dkron#816]
I want to do some procession on all the jobs, for which I need pagination so that my app don't need to load all the data in the memory.

**Comment by cobolbaby** [comment]
Considering that the back-end storage uses a kv structure database, which field is used to sort data when implementing paging?

**Comment by victorcoder** [comment]
There is no pagination at the moment for API calls, the pagination on WebUI is done on the client

**Comment by victorcoder** [comment]
Already implemented
