### ISSUE TITLE
All cron expressions are not working

### ISSUE THREAD

**Issue by shivaprasad573** [distribworks/dkron#823]
**Describe the bug**
We are not able to create a job with the custom expressions. Ex: I was trying to create a job that should run 1st Monday of every month. To achieve this went into [Cronmaker](http://www.cronmaker.com/?1) and collected the cron expression as `0 0 12 ? 1/1 MON#1 *`
**To Reproduce**
Steps to reproduce the behavior: Run the bellow curl command which has above CRON.
`
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{

  "name": "joblocal",
  "schedule": "0 0 12 ? 1/1 MON#1 *",
  "tags": {
    "server": "true:1"
  },
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "curl --request POST --url \''http://localhost:8564/\''"
  }
}' \
 'http://localhost:8080/v1/jobs'
`
When i run the above API am getting the response as.

`Job contains invalid value: can't parse job schedule: expected exactly 6 fields, found 7: [0 0 12 ? 1/1 MON#1 *].`

**Expected behavior**
I was expecting a job to be created.

** Specifications:**
 - OS: Ubuntu
 - Version: 18.04LTS

**Comment by yvanoers** [comment]
Cronmaker uses Quartz cron expression format. Dkron uses a similar but still different cron expression format (see the [dkron documentation of the cron spec](https://dkron.io/usage/cron-spec/).

The cron expression I'd use for running a job every first Monday of the month at noon would be
`0 0 12 1-7 * mon`
(did not test)

PS:
If you want to schedule a web call, like your example suggests, dkron can do it directly by means of a [HTTP executor](https://dkron.io/usage/executors/http/).

**Comment by viperfx** [comment]
Hey @yvanoers is it possible to trigger on the 2nd Monday of every 2 weeks? 

Is there any plans to expand to using some more flexible such as RRULE?

**Comment by yvanoers** [comment]
@viperfx
> is it possible to trigger on the 2nd Monday of every 2 weeks?

I understand this as every two weeks, starting from a specific date.
You could also interpret it as very 2nd and 4th Monday in a month, but I'm going with the aforementioned here.

This schedule can't be expressed by the cron expressions used in Dkron at this time. To have Dkron do this, you could opt to use
`@every 336h`
and manually start this job once on the first appropriate day. It will henceforth run every two weeks.
This is somewhat fragile though: If the cluster goes down, it resets the starting date.

A reliable solution would be to run it every Monday and have code determine whether or not it is the appropriate Monday. This could be done either in the code being scheduled, or as part of a script inlined in the Dkron job.

None of these is a very elegant solution, though.

> Is there any plans to expand to using some more flexible such as RRULE?

Not that I'm aware of, but please raise your wishes in a feature request and we can take a look at it!

**Comment by viperfx** [comment]
Yea exactly @yvanoers there are many workarounds to this, but CRON does not reach an actual solution. When it concerns trying to do an action at a specific schedule, its not accurate enough.

RRULE is what most calendars use when specifying schedules and possible to represent many types of recurring schedules.

**Comment by victorcoder** [comment]
I didn't know about RRULE, I think it should be possible to implement a schedule parser to handle RRULE expressions, the other alternative I'm inclined for in terms of expression expressivity is using https://en.wikipedia.org/wiki/ISO_8601 repeating interval notation.

**Comment by yvanoers** [comment]
Feature request moved to #1048 - initial issue has been dealt with.
