### ISSUE TITLE
High level Architecture diagrams for dkron with dkron-agent communications

### ISSUE THREAD

**Issue by smlingesh** [distribworks/dkron#830]
Hi Team, 

Is there a place where we can see the high-level architecture diagrams of dkron system, where it represents availability, scalability, and communication between different components? Hope this kind of diagram useful for architects can suggest this product to their product and vendor usage. Any thoughts on the same.

**Comment by yvanoers** [comment]
The short answer is: No (not that I'm aware).

The long answer would be that Dkron can be set up in a variety of ways, having different degrees of availability and scalability. It is designed to be used in a redundant setup, but that is not a necessity. You can go with a single node that does everything, to using lots of nodes that are all capable of becoming a leader and are all capable of doing any job. You can have some dedicated leaders and/or some dedicated agents (using tags). And depending on where you deploy dkron nodes, it is possible to be geo-redundant.
The architecture of a Dkron cluster is yours to create.

As for communications:
All nodes need to be able to talk to each using two ports for serf and raft/gRPC ([see docs](https://dkron.io/basics/getting-started/#usage) for defaults). It is convenient to be able to talk to at least one node in a cluster from the outside on a third port for the dashboard and API.
I consider this to be too high a degree of detail for high level architecture diagrams. But, to each his own.

**Comment by smlingesh** [comment]
Thanks for your details @yvanoers.

**Comment by victorcoder** [comment]
Thanks @yvanoers, you nailed it, I sometimes miss an internal architecture diagram though.

**Comment by cobolbaby** [comment]
Is it possible to provide a more detailed architecture diagram?
