### ISSUE TITLE
Migration to another AWS account & region

### ISSUE THREAD

**Issue by vishalsngl** [distribworks/dkron#834]
We have a standalone Dkron server in one of our AWS accounts. We plan to live-migrate the same to another AWS account. To do the same we came up with the following approach:

- Convert it to a cluster by adding the new node in the other AWS account, let's call this Node B.
- Since the nodes are in different accounts as well as different regions, we're using the public IPs in the cluster configuration
- Following are the configurations on both the nodes, 

Node A (Current)
```
bootstrap-expect: 2
retry-join:
  - <myPrivateIP>
  - <PublicIP of node B>
```

Node B (Destination)
```
bootstrap-expect: 2
retry-join:
  - <myPrivateIP>
  - <PublicIP of node A>
```
- With this configuration, the clustering is happening but not properly, both the nodes are able to accept jobs and are syncing the jobs and other metrics, both their dashboards show the updated live metrics, but they don't show up in the nodes list in the dashboard, while only one is elected leader and the other shows empty leader section.
- The next step would be to reconfigure the Node B to a standalone server and stopping Node A, we did that, the data was synced on the new node but it was not running the jobs anymore, neither was it able to elect itself as the leader.

Feel free to suggest an alternate approach and/or issues with our current approach. Our intention is to migrate it with no or minimum downtime.

**Comment by yvanoers** [comment]
Which version of Dkron do you use? Or, more to the point, are you using the same version on both ends?

> but they don't show up in the nodes list in the dashboard

Fix this first. If a cluster does not list all nodes, you should not expect it to work.

This description has a lot of unknowns, making it hard to troubleshoot. Might I suggest setting up a test cluster in the first region - when that works, set up a test cluster using both regions. After that works, see what the difference is with the production configuration and fix whatever's wrong.

Also, consider using at least two nodes in your final cluster. It should allow you to make changes to the cluster without it ever going down. Disclaimer: I'm not speaking from experience in this regard.

**Comment by vishalsngl** [comment]
Both the nodes are on v3.0.5

These are all actually my findings on a test cluster where I was trying to imitate the behavior. I was actually able to create the fully working cluster while using their private IPs in the config, both the nodes were getting listed in each other's dashboards, accepting jobs, displaying common stats and all. But, as soon as I changed the other node's IP to a public IP, to imitate the behavior of the nodes being in different region and not able to access each other on private network, I started facing the issues as mentioned earlier.

**Comment by yvanoers** [comment]
Ok, that helps.
Firewall of some sorts would be my first guess, then.
Are all ports of one reachable by the other AND vice versa?

What do the server logs say?

**Comment by vishalsngl** [comment]
I've ensured that port 6868 is accessible to each other both over the public and private networks. I was not able to find any documentation for what all ports should be accessible, just used 6868 as the same is the default port for RPC communication and is visible on the dashboard as well. Let me know if any other port should be accessible to each other.

Couldn't see anything worth checking out in the server logs, both the nodes show a joining log with the list of nodes provided followed by the joined log of the node itself. After that, both of them start operating.

Noticed another weird thing that even after reverting back to single-node configuration, they were still somehow communicating as the metrics visible on both the dashboards were the same.

Also, wanted to know the difference between, `retry-join` and `join` options in the config file, `retry-join` comes in the default config file while `join` is mentioned in the [documentation](https://dkron.io/usage/clustering/).

**Comment by yvanoers** [comment]
You also need to open port 8946 for serf (see [Usage](https://dkron.io/basics/getting-started/#usage)).

> the difference between, `retry-join` and `join` options in the config file

`join` will attempt to connect to the listed addresses. If that fails, the agent exits with an error.
`retry-join` attempts to connect as well, but keeps retrying until it succeeds. Behaviour of `retry-join` can be changed using `retry-max` (max attempts, default unlimited) and `retry-interval` (time between retries in seconds, default 30s).

**Comment by vishalsngl** [comment]
Okay, still facing issues. This time I kept both the ports 8946 & 6868 open to each other over the private network, clustering happened as expected. Then, I stopped one of them and removed its configuration from the other node, now the standalone server doesn't know who is the leader and is not accepting jobs, getting context deadline error while creating jobs. Also, this time I upgraded both these test nodes to the latest v3.0.6 release.

Anyway, for my actual instance, I decided to take a downtime and move the EC2 instance itself, which worked for most parts, did face one issue with that as well, which is, after re-launching the instance in a new region, the default hostname of the machine changed, because of which Dkron was not able to start, had to keep the hostname same as in the original instance to get it running. Seems like the hostname is also part of the storage.

**Comment by victorcoder** [comment]
@vishalsngl I this will be getting complicated, why not exporting jobs, disable them, loading on the new single-node cluster, then toggle job one by one?

**Comment by vishalsngl** [comment]
@victorcoder Exporting and adding them to a new cluster was not an option as the job count was high, doing that manually was not possible, or automating that in itself would've been time-consuming, which is why I took a downtime, launched a new instance using an AMI of the original instance as mentioned in my previous comment. 

Feel free to close this issue if you want as I'm not looking for any further assistance for now. Do let me know if there is a better way to do the migration whenever you get the chance.
