### ISSUE TITLE
Can job execution restricted to single node 

### ISSUE THREAD

**Issue by smlingesh** [distribworks/dkron#836]
Hi Team, 

Can job excution restricted to a single node rather than multiple times in a multinode cluster?

**Comment by yvanoers** [comment]
Yes, that is possible.
Target a job with a tag and append ":1" to the tag value. This will make the job run on only 1 of the agents having the tag.
An example can be found in [the documentation](https://dkron.io/usage/target-nodes-spec/#target-only-one-nodes-of-a-group-of-nodes-with-a-tag).

**Comment by smlingesh** [comment]
Thanks for your details @yvanoers !! which is interesting like restrict a job by tag-based one.
