### ISSUE TITLE
UI displays different timezones in the job list and the execution history

### ISSUE THREAD

**Issue by alexanderfefelov** [distribworks/dkron#839]
Dkron 3.0.5:

![1](https://user-images.githubusercontent.com/5790321/97155782-e9c52500-1786-11eb-988d-2cb03e4f46d6.png)

![2](https://user-images.githubusercontent.com/5790321/97155797-ecc01580-1786-11eb-8ada-a2397c04c3db.png)

**Comment by yvanoers** [comment]
Looks like the same feature request as #526.

**Comment by victorcoder** [comment]
Duplicate of #526
