### ISSUE TITLE
Unbalanced task schedule

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#848]
**Describe the bug**

As more and more tasks need to be scheduled in the production env, we find that task scheduling is getting more and more unbalanced. 

Could describe the implementation of task scheduling, so that we can locate the root causes of unbalanced scheduling?

**Comment by cobolbaby** [comment]
There is still a lot to do with scheduling issues. I really want to know what kind of plans we have in the future. Will we refer to applications such as APS (Advanced Planning & Scheduling System)?

**Comment by victorcoder** [comment]
@cobolbaby regarding what are you finding unbalance? Target nodes are balanced pseudo-randomly should work well enough.

What scheduling issues you are referring to?

**Comment by cobolbaby** [comment]
@victorcoder We implemented the front-end display layer based on the dkron interface, which contains statistic feature to display the number of tasks running on each node. Refer to the snapshot as below. 

Each line represents a Dkron node. From the figure, you can see the task load of the node. It is obvious that one node is running more tasks than other nodes.

![2020-11-10 09-47-14屏幕截图](https://user-images.githubusercontent.com/11460848/98617346-c9c26380-2339-11eb-87d6-1650bea9e90c.png)

**Comment by cobolbaby** [comment]
> What scheduling issues you are referring to?

I mean intelligent scheduling. Because the scale of tasks is increasing, manual scheduling depends on experience, and perhaps a more intelligent mode is needed, similar to the APS in a factory.

**Comment by cobolbaby** [comment]
Is the scheduling method of dkron 1.x the same as 3.x?

**Comment by victorcoder** [comment]
No @cobolbaby correct randomness was introduced at some point, are your graphs from 3.x?

**Comment by cobolbaby** [comment]
It is based on 1.x

**Comment by victorcoder** [comment]
Let me know if 3.x works as you expect. I'm closing the issue in the meantime.
