### ISSUE TITLE
Cannot see the content of log files from the web interface

### ISSUE THREAD

**Issue by tobia** [distribworks/dkron#857]
**Is your feature request related to a problem? Please describe.**
If I configure the "files" processor, in order not to overload the Raft database with large logs, I lose the ability to see the output of jobs from the web interface.

**Describe the solution you'd like**
In the Job Executions page of the web interface, when the processor is "files", the link under the Output column should open a new tab with the contents of the log file (with Content-Type: text/plain) instead of a popup with the filename, which is kind of useless.

**Comment by victorcoder** [comment]
@tobia the files processor stores the output in a file in one of the nodes, as this is a distributed system, when  the using the web ui from one node, the file could not exists in the same node, no?

To address this, the file should be transferred in realtime to the requesting node.

The file plugin is meant to be used in conjunction with a log file forwarder like Elastic Beats or similar, for automation, not for viewing the files directly in the UI.

I will close this request as it's out of the scope of the files processor.

**Comment by tobia** [comment]
@victorcoder I disagree, because there are such things as NFS shares, which are useful for this very purpose.
