### ISSUE TITLE
The job filter does not work the first time

### ISSUE THREAD

**Issue by alexanderfefelov** [distribworks/dkron#867]
Open the dashboard. Click `Successful Jobs` (or `Failed Jobs`). You will see an __unfiltered__ list. Click `Successful Jobs` (or `Failed Jobs`) again, and the list will be filtered.

Dkron 3.0.8

**Comment by victorcoder** [comment]
This is now implemented in the new UI as a filter https://github.com/distribworks/dkron/pull/872

I will close this as the old UI is now deprecated.

**Comment by alexanderfefelov** [comment]
> as the old UI is now deprecated
But new UI is not ready for production use yet.

**Comment by victorcoder** [comment]
Why not? Did you try it? It brings the same functionality as the old one and without bugs

**Comment by alexanderfefelov** [comment]
> Did you try it

Yes, i did.

**Comment by victorcoder** [comment]
Great, and why do you think it's not production ready? Could you give constructive feedback?
