### ISSUE TITLE
Dark theme does not survive page reload

### ISSUE THREAD

**Issue by alexanderfefelov** [distribworks/dkron#870]
Dkron 3.1.0

Enable the dark theme. Reload (`F5` or `Ctrl+R`) any page. The current theme will be switched to light.

**Comment by victorcoder** [comment]
Yes it seems 🤔 , notice that I'm super noob with React and react admin, I just copied the config from the demo https://marmelab.com/react-admin-demo/#/configuration and it behaves the same, so I need more work to solve this 😅
