### ISSUE TITLE
3.1 Broken

### ISSUE THREAD

**Issue by jjsaunier** [distribworks/dkron#871]
### Note: Will dig tomorow on fresh & clean setup, looks like also happened after downgrade aswell

**Describe the bug**

Topology : 1 primary, 1 secondary running on k8s. Everything works in 3.0.x, the only difference is the docker image tag and the flag `--ui` 

Logs: 

```bash
level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=master-g5s7c server_addr=
level=info msg="[GIN] 2020/12/19 - 17:15:08 | 500 | 10.000590768s |       127.0.0.1 | POST     \"/v1/jobs\"" node=master-g5s7c
```

**To Reproduce**

- try to add new job from API 

```bash
curl 'http://dkron-web.dkron:8080/v1/jobs' \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  --data-binary '{"name":"00303b3f-002c-4282-9943-3c91b8d4a165","schedule":"* * * * * *","displayname":"test","owner":"00303b3f-002c-4282-9943-3c91b8d4a165","owner_email":"test@gmail.com","concurrency":"allow","tags":{"type":"scrapfly:1"},"metadata":{"name":"test"},"executor":"http","executor_config":{"method":"GET","url":"http:/test/schedule/c4500625-c804-413c-afbd-b30d8674d352/2be7a652-be7f-4619-9d1e-b9f29ee502ea","headers":"[\"test: 0abe373f-26ee-4006-8232-de9ce4ff2a99\"]","body":"","timeout":"300","expectCode":"200,429,503","expectBody":""},"retries":0}' \
  --compressed \
  --insecure ;
```

Give

```
context deadline exceeded
```
  

**Expected behavior**

200.

**Screenshots**
No infrastructure problems, they see each other, same as before and errors in logs expect the 500 of the HTTP API
![image](https://user-images.githubusercontent.com/1763341/102679657-730a3e00-41b1-11eb-8a73-4ba51d0ebdae.png)

** Specifications:**
 - OS: Linux / k8s
 - Version 5.8.18 / 1.9

**Additional context**
Using retry-join feature on k8s, but do not seems to related to infrastructure

**Comment by victorcoder** [comment]
I can not reproduce it, I just sent your job to the test cluster and it works http://test.dkron.io:8080/ui/#/jobs/00303b3f-002c-4282-9943-3c91b8d4a165/show it seems something is wrong in your cluster.

Notice that your worker node appear as failed.

**Comment by jjsaunier** [comment]
Yep I will check on fresh cluster. Status 4 in UI means that worker failed right ?

**Comment by victorcoder** [comment]
Yes, I need to translate that code in ui
