### ISSUE TITLE
Regression search jobs in 3.0 UI

### ISSUE THREAD

**Issue by denrou** [distribworks/dkron#877]
Dkron 3.0 introduces a nice new UI. In the previous UI (< 3.0), the search bar to look through jobs would search for any keyword in the body. In the last UI (>= 3.0), the search bar seems to only look in the Id of the jobs.

1. Go to Jobs
2. In the search bar, type `success`
3. Table returns No results found whereas some jobs should have been found

**Expected behavior**
The search should return all jobs with `success` in their body (all jobs with `status: success`) for example.

**Additional context**
I've seen the new `Add filter` button with the possibility to filter regarding with the status. The example given here was for simplicity but we used this capability to filter metadata given in the executor config originally.

**Comment by victorcoder** [comment]
Previous behaviour was like a fuzzy search, one possibility is to search in more fields with the current search but I would be more inclined to add more specific field filters instead.

**Comment by victorcoder** [comment]
Filter is now able to search by job status
