### ISSUE TITLE
ensure a task or job is always running

### ISSUE THREAD

**Issue by dch** [distribworks/dkron#881]
**Is your feature request related to a problem? Please describe.**

I would like dkron to ensure a job is always running on the cluster

**Describe the solution you'd like**

- additional `predefined schedule` of `@always` or `@continuous` or `@daemon` for example
- if the job is still running for the given target nodes, then don't start it
- if the job has finished on the target nodes, then restart it
- 
- this would effectively ensure that if the job spec finished, or exited prematurely, it would always be restarted shortly afterwards

**Describe alternatives you've considered**

- running a job every minute, that has a shell script that simply exits if there's a job already running

**Additional context**

**Comment by yvanoers** [comment]
You're describing a watchdog. Dkron is not a monitoring service and therefore lacks additional features you are probably going to want next, such as limits and back-offs when a process won't restart immediately, reporting on downtime, etc.

I would really advise against using Dkron for this.
But, if you are insistent on doing this, you already can with a job configured with
```
schedule: "@every 1s" (or something less aggressive)
concurrency: "forbid"
```
and no tags.

**Comment by dch** [comment]
point taken, but all of that I can handle elsewhere. I'm just interested in having a distributed daemonised task, that is restarted within a few seconds if it's down. The rest is already taken care of.

The example above is sufficient for my case, thanks for the suggestion of `currency: forbid`.
