### ISSUE TITLE
Web interface not working after 3.0.8

### ISSUE THREAD

**Issue by guybluebat** [distribworks/dkron#895]
**Describe the bug**

The web interface returns "404 page not found" for any version of dkron above 3.0.8.

**To Reproduce**

1. Install any version of Dkron greater than 3.0.8.
2. Browse to http://[node-ip]:8080.

**Expected behavior**
Browsing to http://[node-ip]:8080 should redirect to http://[node-ip]:8080/dashboard and display the web interface, eg:

![image](https://user-images.githubusercontent.com/13126195/105439926-92661200-5c1a-11eb-9bc9-cbbb9a1a6fb9.png)

**Screenshots**

*Browsing to web root:*

![image](https://user-images.githubusercontent.com/13126195/105439692-284d6d00-5c1a-11eb-9607-ecbf0ca82f76.png)

*Browsing direct to dashboard URI:*

![image](https://user-images.githubusercontent.com/13126195/105439731-3602f280-5c1a-11eb-9467-795e064a9b36.png)

**Specifications:**

 - Server OS: Ubuntu 18.04.4
 - Dkron Version(s): 3.10, 3.1.1, 3.1.2, 3.1.3
 - Client OS: Windows 10 Pro 64-bit
 - Browsers tested: Firefox (v84.0.2), Chrome (v87.0.4280.141)

**Additional context**

Attempted the following:
* Restarted dkron service
* Restarted server instance(s)

**Comment by victorcoder** [comment]
The URL for the new UI is /ui and there is no redirection from the root path anymore.

**Comment by guybluebat** [comment]
Ok, good to know.
