### ISSUE TITLE
Add a job filter by "disable" state

### ISSUE THREAD

**Issue by educlos** [distribworks/dkron#912]
**Is your feature request related to a problem? Please describe.**
There is this really rare issue where all jobs stop being schedule, and to solve it we need to just disable and re-enable the jobs.
A new filter on the "disable" status of a job would help in this case (We can currently filter by status only)

**Describe the solution you'd like**
Add a new filter, similar to the "Status" one, to show only enabled or disabled jobs

**Additional context**
I checked the code to try to add it myself, but was not successful :disappointed:

**Comment by victorcoder** [comment]
Thank you for the suggestion @educlos, I just fixed a missing dir that prevented UI development in #919 check if that helps.
