### ISSUE TITLE
Source missing: ui/public/

### ISSUE THREAD

**Issue by yvanoers** [distribworks/dkron#914]
I suspect there's a directory missing in the repository. When I try to use `npm start` or `make ui`, it complains that index.html is missing:

```
$ npm start

> webui@0.1.0 start /home/yvanoers/src/dkron_git/dkron/ui
> react-scripts start

Could not find a required file.
  Name: index.html
  Searched in: /home/yvanoers/src/dkron_git/dkron/ui/public
```

Could you add the missing file(s)?
Or update the README.md appropriately?

**Comment by victorcoder** [comment]
You are right, thanks for noticing @yvanoers! fixed in #919
