### ISSUE TITLE
Logs are not visible in windows when dkron is started as a task. What is the location of dkron logs in windows ? How i direct the logs to customer location and create separate log files for each job

### ISSUE THREAD

**Issue by simplyrahul1** [distribworks/dkron#915]
**Describe the bug**
Logs are not visible in windows when dkron is started as a task. What is the location of dkron logs in windows ?
How do I direct the logs to custom location and create separate log files for each job ?

**To Reproduce**
1. Go to Task Scheduler
2. Create Job to start dkron after reboot
3. Folder D:\dkron_3.1.4\ doesn't have any logs
4. 
**Expected behavior**
Create main dkron process logs in  : D:\dkron_3.1.4\
Create separate folders for job  D:\dkron_3.1.4\job\<job-id>\<job-name>.log

**Screenshots**

** Specifications:**
 - OS: Windows Server
 - Version : 2019

**Additional context**

**Comment by yvanoers** [comment]
What is your reasoning for thinking Dkron would create log files in D:\dkron_3.1.4\ or anywhere else?
Dkron writes logging to stderr, not to file. If you want it in a file, you have to redirect it there.

As for separate logs for each job: have a look at [output processors](http://dkron.io/usage/processors/file/).
