### ISSUE TITLE
Make some dashboard table field values nullable

### ISSUE THREAD

**Issue by orihomie** [distribworks/dkron#920]
![image](https://user-images.githubusercontent.com/29889683/110422166-dd939180-80af-11eb-909a-6aab5b14bd5f.png)

Hi, I'm requesting to make fields "Finished At" and "Success" some kind of type of nullable, then, for example, "Success" would have a 3 possible values: true, false, null. Its for that purpose of knowing exactly:
* job did finished (successfully or not)
* job did failed to execute

Same for "Finished At" field.

**Comment by yvanoers** [comment]
The screenshot shows an older version of Dkron. The current version has a new UI that does a better job of displaying the execution state. Could you please have a look and leave a note saying whether that meets your needs.

**Comment by victorcoder** [comment]
@yvanoers is right, closing.
