### ISSUE TITLE
Typo in Executors / NATS documentation

### ISSUE THREAD

**Issue by tomercagan** [distribworks/dkron#928]
**Describe the bug**
Typo in executors documentation - Shell executor is listed twice instead of shell and NATS

**To Reproduce**
1. Go to the website
2. Navigate to Usage > Executors
3. Observe there are two links to "Shell Executors"
4. Click first "Shell Executor" to navigate into the NATS executor
5. Observe typo in title "Shell Executor"

**Expected behavior**
Index page should show link to "NATS Executor"
NATS Executor page should have a title "NATS Executor"

**Screenshots**
Index page showing wrong link title
![dkron_executors_index](https://user-images.githubusercontent.com/4086469/111761369-7d1f0400-88a8-11eb-93dc-79b8bcd8248f.png)

NATS page showing wrong title
![dkron_executors_nats](https://user-images.githubusercontent.com/4086469/111761426-8dcf7a00-88a8-11eb-9f48-85a432ed85ed.png)

**Specifications:**
N/A

**Additional context**
I thought this would be faster than forking and making a PR :-)

**Comment by yvanoers** [comment]
@tomercagan Thanks for your watchfulness!
