### ISSUE TITLE
The new UI is a real mess

### ISSUE THREAD

**Issue by alexanderfefelov** [distribworks/dkron#932]
![1](https://user-images.githubusercontent.com/5790321/112304707-daeb8b80-8cae-11eb-8793-57e000bde3c1.png)

Rich here, poor there.

I drew cell borders for clarity.

Dkron 3.1.6

**Comment by alexanderfefelov** [comment]
Let see screenshot taken from Portainer:

![2](https://user-images.githubusercontent.com/5790321/112429795-3751b800-8d4e-11eb-9dd5-a78755cd5b33.png)

Selectable colums with variable width looks pretty.

**Comment by joshshn** [comment]
+1. 
Is there any plan to fix the UI? The bad UI table rendering makes the viewing of jobs difficult.

**Comment by yvanoers** [comment]
@alexanderfefelov
Has the latest release alleviated this issue? This issue is not very clearly defined, so hard for us to determine whether this is resolved.

**Comment by alexanderfefelov** [comment]
UI has become more convenient with 3.1.8.

**Comment by alexanderfefelov** [comment]
Thanx.
