### ISSUE TITLE
How to single-step debug the dkron plugin?

### ISSUE THREAD

**Issue by cobolbaby** [distribworks/dkron#934]
Before single-step debugging the dkron, I just need to execute `go install ./...` to install plugins. But if I want to debug the plugin, the way of plugin loading is obviously not friendly to the debugging. 

Is there any debug method?

**Comment by yvanoers** [comment]
How to do this exactly depends largely on your choice of tools. However, the general direction for stepping through a plugin would be to start Dkron and attach your debugger to the running plugin process you want to debug.

**Comment by cobolbaby** [comment]
@yvanoers The IDE I currently use is vscode. Because dkron actually invokes the plugin by executing a binary file, how can I step through it?

**Comment by yvanoers** [comment]
Assuming you're using Linux:
Build dkron from your source and run it as an agent from a command line (you may need some more parameters like bootstrap-expect), e.g.:
```
$ scripts/run agent
```
This will run dkron with its plugins. Now use another console to get the pid of the plugin you want to debug, e.g.:
```
$ pidof dkron-executor-shell
1234
```
Then in VSCode, with the dkron source folder open, do Run &rarr; Add Configuration.
This should open a launch.json file and present you with a couple of options. Choose 'Go: Attach to local process'.
It will generate a new entry like this:
```
{
  "name": "Attach to Process",
  "type": "go",
  "request": "attach",
  "mode": "local",
  "processId": 0
}
```
Change `processId` to the pid of the plugin (`1234` in the example above) and save the file.
Set a breakpoint in the plugin code, e.g. in `shell.go` at the start of the `Execute(...)` function.
Start debugging (Run &rarr; Start Debugging; F5). This should attach the VSCode debugger to the plugin.
If this fails, it will say why in the debug console. In my case, I need to do (as root)
```
# echo 0 > /proc/sys/kernel/yama/ptrace_scope
```
first.

Now when a job is triggered that uses this plugin, execution will break at your breakpoint and you can step through.

**Comment by yvanoers** [comment]
I take it from the thumbs-up that your question has been answered.
If not, feel free to reopen the issue.
