### ISSUE TITLE
Leadership reacquision problem

### ISSUE THREAD

**Issue by mayank98108** [distribworks/dkron#939]
**Describe the bug**
- after setting up the cluster for the Dkron, the reacquisition of the leadership is not working.

- instead of election of new leader it says, no leader after disconnecting the leader.

**Comment by bittrance** [comment]
A bit of context would be good:
- the actual dkron invocation (i.e. cli args)
- config file, if any
- log output, preferrably at debug level
- short description of execution environment

**Comment by vcastellm** [comment]
Closing because lack of information
