### ISSUE TITLE
How to add a new node in a clustering?

### ISSUE THREAD

**Issue by RyanHuang1102** [distribworks/dkron#940]
DKRON v3.0.4

there are 3 VMs in a cluster.

vm1. 

- dkron agent -- server --bootstrap-expect=3 --join='192.168.0.1' --join='192.168.0.2' --join='192.168.0.3'

vm2.

- dkron agent -- server --bootstrap-expect=3 --join='192.168.0.1' --join='192.168.0.2' --join='192.168.0.3'

vm3.

- dkron agent -- server --bootstrap-expect=3 --join='192.168.0.1' --join='192.168.0.2' --join='192.168.0.3' 

**if I want to add a vm4 in this cluster, how to do?**

> dkron agent -- server --bootstrap-expect=4 --join='192.168.0.1' --join='192.168.0.2' --join='192.168.0.3' --join='192.168.0.4'

it will show 

> **time="2021-03-19T13:17:29+08:00" level=error msg="peer has a conflicting expect value. All nodes should expect the same number"**

if I use it in a wrong way, please kindly give me a hint.

Thanks!

**Comment by fopina** [comment]
you should always use the same bootstrap expect

**Comment by RyanHuang1102** [comment]
thanks your response,

so what I should do is 

- dkron agent -- server --bootstrap-expect=3 --join='192.168.0.1' --join='192.168.0.2' --join='192.168.0.3' --join='192.168.0.4'

right? (I want to add vm4 in this cluster, but I don't want to kill vm1~vm3 dkron process)

**Comment by fopina** [comment]
Yes, not entirely sure that specifying bootstrap expect is even required, but I always do it due to configuration provisioning simplicity :)

**Comment by RyanHuang1102** [comment]
OK, if there is no other ideas in next week I will close this issue.
Thanks u.

**Comment by victorcoder** [comment]
@RyanHuang1102 yes, you should use the same bootstrap-expect value for all nodes, that's only for bootstrapping, the first time you start the cluster, just use the same value for an existing cluster.

**Comment by RyanHuang1102** [comment]
ok, thank u guys!
