### ISSUE TITLE
dkron slack processor onsuccess wrong

### ISSUE THREAD

**Issue by Mikki-black** [distribworks/dkron#942]
When not defining the onsuccess parameter the documentation states that no messages should be sent, however the slack channel gets a notification on success. This is not as described in the documentation: https://dkron.io/pro/processors/slack/ 

When defining onsuccess: false it does not send a notification. 

**To Reproduce**
Define a job with slack processor without the onsuccess parameter
run the job

**Expected behavior**
On success nothing should be reported as stated in documentation when not defined.

** Specifications:**
 - OS: debian 10
 - dkron pro 3.1.3

**Comment by vcastellm** [comment]
Fixed in v3.2.0
