### ISSUE TITLE
Many race conditions

### ISSUE THREAD

**Issue by sysadmind** [distribworks/dkron#951]
**Describe the bug**
Recently I have been looking through the code of dkron to help diagnose some of our issues:
- No leader elected indefinitely
- Leader kicks off job and agent can not look up job details

During my investigations I have tried running the test suite. I have race detection turned on by default and this brought up several race conditions.

**To Reproduce**
1. From the root directory of the project, execute `go test -timeout 30s github.com/distribworks/dkron/v3/dkron -count=1 -race`

**Expected behavior**
Tests pass with no race conditions found

** Specifications:**
 - OS: Any
 - Version: git hash 0de02f70c247c32816d6c7b76fe9461ab3b8d10e (v3.1.6)

**Additional context**
Some of these may be a test suite parallelization symptom, but ultimately I believe all of the functions should be more concurrency safe. One such example is `dkron/log.go` where log is a package scoped var so any time `InitLogger` is called, that log value gets overwritten. An alternative approach would be for functions that need a logger to take the logger as a parameter ( a more pure function/functional programming approach). That would prevent needing a package scoped var that is so susceptible to race conditions in general. 

I would be happy to help on this effort if there is support of changing function signatures to accept the logger or other resources that may be involved in a data race.

**Comment by victorcoder** [comment]
Refactor logging is something that I wanted to do since long ago, a PR will be very welcome, thanks.
