### ISSUE TITLE
Predefined schedule "@minutely" does not work

### ISSUE THREAD

**Issue by ddanila** [distribworks/dkron#969]
**Describe the bug**
Despite mentioned in the documentation here (https://dkron.io/v2.0/usage/cron-spec/) the @minutely predefined schedule is not supported.

**To Reproduce**
1. Try to create a job with @minutely schedule.

**Actual behavior**
Job is not created, error returned.

**Expected behavior**
Job created, runs every 60 seconds.

** Specifications:**
 - Version 3.1.6

**Additional context**
As I can see, https://github.com/robfig/cron/blob/master/parser.go#L365 (library used to parse the cron specs) clearly does not have the @minutely support (I relate to the main version, but it's the same for the one used in Dkron 3.1.6)

So it looks like a bug in the documentation.

**Comment by yvanoers** [comment]
I checked: @minutely was lost in 2019 when robfig/cron got imported directly in favor of the local (and modified) copy of it. So this is a bug!

**Comment by ddanila** [comment]
Thanks for fixing.
I was thinking about the fix too, and lost the battle inside my brain -- either adding it on the level up (where manually is) or patching the library / sending them a PR. There I stopped and made an issue here instead of PR.
