### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by NortH21** [distribworks/dkron#981]
**Describe the bug**
The server has several addresses, but the service starts only on one address

**To Reproduce**
1. Error: dkron agent --server --node-name=node2 --bind-addr=10.11.32.53:8946 --rpc-port=6868 --http-addr=0.0.0.0:8080 --bootstrap-expect=1 --data-dir=/tmp

    INFO[2021-06-11T15:32:49+03:00] agent: Dkron agent starting                   node=node2
    INFO[2021-06-11T15:32:49+03:00] agent: joining: [] replay: true               node=node2
    FATA[2021-06-11T15:32:49+03:00] listen tcp 10.11.32.53:6868: bind: address already in use  node=node2

2. Success: dkron agent --server --node-name=node2 --bind-addr=10.29.17.131:8946 --rpc-port=6868 --http-addr=0.0.0.0:8080 --bootstrap-expect=1 --data-dir=/tmp

    INFO[2021-06-11T15:35:59+03:00] agent: Dkron agent starting                   node=node2
    INFO[2021-06-11T15:35:59+03:00] agent: joining: [] replay: true               node=node2
    INFO[2021-06-11T15:35:59+03:00] api: Running HTTP server                      address="0.0.0.0:8080" node=node2
    INFO[2021-06-11T15:35:59+03:00] dkron: monitoring leadership                  node=node2
    INFO[2021-06-11T15:35:59+03:00] agent: registering usage stats for cluster ID 'OLGPQoXRSWab/DpvraHslRJ1uZzWTcE3bga0/jlT2ag='  node=node2
    INFO[2021-06-11T15:35:59+03:00] agent: Listen for events                      node=node2
    INFO[2021-06-11T15:36:00+03:00] agent: Received event                         event=member-update node=node2
    INFO[2021-06-11T15:36:00+03:00] dkron: cluster leadership acquired            node=node2
    INFO[2021-06-11T15:36:00+03:00] dkron: monitoring leadership                  node=node2
    INFO[2021-06-11T15:36:00+03:00] agent: Starting scheduler                     node=node2

4. IP address

    inet 127.0.0.1/8 scope host lo
    inet 10.11.32.53/32 brd 10.11.32.53 scope global dummy0
    inet 10.29.17.131/26 brd 10.29.17.191 scope global ens127f0.55

**Expected behavior**
Binded address 0.0.0.0 or any other address

** Specifications:**
 - OS: CentOS Linux release 8.2.2004 (Core)
 - Version: 3.1.7

**Comment by vcastellm** [comment]
The first example fails because the port is already used.
