### ISSUE TITLE
How do you run a command line?

### ISSUE THREAD

**Issue by seanfulton** [distribworks/dkron#986]
I've chosen "shell" as the executor, and under executor config, I have:

"command":"echo test | mail sean@myaddress.com"

But all it runs is "echo test"

I have some fairly complex command lines and I don't want to have to write bash scripts for all of them. Do you have any documentation on how to write these???

Looking to run something like:
java my.jar config.conf >>logfile.log

sean

**Comment by yvanoers** [comment]
You need to add
```
"shell": "true"
```
to your executor config.
Note: It **has** to be `"true"` (a string). `true` (a boolean) will not work.

`shell` defaults to false, in which case dkron runs the command as a program followed by arguments.
Setting it to true runs the command in a shell context, like this: `/bin/sh -c 'yourcommand'`. This allows pipes, redirects and other shelly goodness.

**Comment by victorcoder** [comment]
Let us know if that solved the issue @seanfulton

**Comment by seanfulton** [comment]
Thank you, that worked. I didn't get from the docs that it was required. I ran into two other issues in testing though:
1) Job edits don't always save; I noticed that if I edited the command and the tags, it would claim that the changes saved but they did not
2) I ran 1 test job reliably. I killed the master, the job failed over and continued to run nicely. I restarted the old master, and as soon as it joined the cluster, the job stopped working. It retained its old "next run" time, even though the time was two hours old. I could not get it to run. I re-saved it, paused and un-paused it, but it would not run. I deleted the job and created a new one, did the whole kill the leader and restart the old leader and everything worked fine. 
Also, I notice that if you try to save a job and there is an error, it just says there is an error, it doesn't tell you which field is the problem.

**Comment by yvanoers** [comment]
@seanfulton 
Ok, great! I'll see if I can clarify the doc regarding the shell configuration.

Regarding the other points: Would you mind putting both the UI bugs in their own issues? That way it is easier to keep track of what is fixed and what is still an open issue.
If the cluster stopped running, that could also be worth its own issue, especially if you can reproduce it. Please keep in mind though that a raft cluster like dkron can reliably recover from outage with a minimum of 3 servers (IIRC).
